dist-upgrade to baureo-backports

diff --git a/bin/zdiff b/bin/zdiff
--- a/bin/zdiff
+++ b/bin/zdiff
@@ -1,12 +1,12 @@
 #!/bin/bash
 # sh is buggy on RS/6000 AIX 3.2. Replace above line with #!/bin/ksh
 
-# Copyright (C) 1998, 2002, 2006, 2007 Free Software Foundation
+# Copyright (C) 1998, 2002, 2006, 2007, 2009 Free Software Foundation
 # Copyright (C) 1993 Jean-loup Gailly
 
 # This program is free software; you can redistribute it and/or modify
 # it under the terms of the GNU General Public License as published by
-# the Free Software Foundation; either version 2 of the License, or
+# the Free Software Foundation; either version 3 of the License, or
 # (at your option) any later version.
 
 # This program is distributed in the hope that it will be useful,
@@ -18,16 +18,20 @@
 # with this program; if not, write to the Free Software Foundation, Inc.,
 # 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.
 
-PATH=${GZIP_BINDIR-'/bin'}:$PATH
+bindir='/bin'
+case $1 in
+--__bindir) bindir=${2?}; shift; shift;;
+esac
+PATH=$bindir:$PATH
 
 case $1 in
   --__cmp) shift
-	prog=cmp;  cmp='${CMP-cmp}'  ;;
+        prog=cmp;  cmp='${CMP-cmp}'  ;;
   *)    prog=diff; cmp='${DIFF-diff}';;
 esac
 
-version="z$prog (gzip) 1.3.12
-Copyright (C) 2007 Free Software Foundation, Inc.
+version="z$prog (gzip) 1.5
+Copyright (C) 2009, 2011-2012 Free Software Foundation, Inc.
 This is free software.  You may redistribute copies of it under the terms of
 the GNU General Public License <http://www.gnu.org/licenses/gpl.html>.
 There is NO WARRANTY, to the extent permitted by law.
@@ -84,76 +88,78 @@ if test $# -eq 1; then
     exit 2;;
   esac
 elif test $# -eq 2; then
-	case "$1" in
-	*[-.]gz* | *[-.][zZ] | *.t[ga]z | -)
+        case "$1" in
+        *[-.]gz* | *[-.][zZ] | *.t[ga]z | -)
                 case "$2" in
-		*[-.]gz* | *[-.][zZ] | *.t[ga]z | -)
-		    if test "$1$2" = --; then
-			gzip_status=$(
-			  exec 4>&1
-			  (gzip -cdfq - 4>&-; echo $? >&4) 3>&- |
-			    eval "$cmp" - - >&3
-			)
-		    elif
-			# Reject Solaris 8's buggy /bin/bash 2.03.
-			echo X |
-			 (echo X | eval "$cmp" /dev/fd/5 - >/dev/null 2>&1) \
-				5<&0
-		    then
-			gzip_status=$(
-			  exec 4>&1
-			  (gzip -cdfq -- "$1" 4>&-; echo $? >&4) 3>&- |
-			    ( (gzip -cdfq -- "$2" 4>&-; echo $? >&4) 3>&- 5<&- </dev/null |
-			       eval "$cmp" /dev/fd/5 - >&3) 5<&0
-			)
-			case $gzip_status in
-			  *[1-9]*) gzip_status=1;;
-			  *) gzip_status=0;;
-			esac
-		    else
-			F=`expr "/$2" : '.*/\(.*\)[-.][zZtga]*$'` || F=$prog
-			tmp=
-			trap '
-			  test -n "$tmp" && rm -f "$tmp"
-			  (exit 2); exit 2
-			' HUP INT PIPE TERM 0
-			if type mktemp >/dev/null 2>&1; then
-			  tmp=`mktemp -t -- "$F.XXXXXX"` || exit 2
-			else
-			  set -C
-			  tmp=${TMPDIR-/tmp}/$F.$$
-			fi
-			gzip -cdfq -- "$2" > "$tmp" || exit 2
-			gzip_status=$(
-			  exec 4>&1
-			  (gzip -cdfq -- "$1" 4>&-; echo $? >&4) 3>&- |
-			    eval "$cmp" - '"$tmp"' >&3
-			)
+                *[-.]gz* | *[-.][zZ] | *.t[ga]z | -)
+                    if test "$1$2" = --; then
+                        gzip_status=$(
+                          exec 4>&1
+                          (gzip -cdfq - 4>&-; echo $? >&4) 3>&- |
+                            eval "$cmp" - - >&3
+                        )
+                    elif
+                        # Reject Solaris 8's buggy /bin/bash 2.03.
+                        echo X |
+                         (echo X | eval "$cmp" /dev/fd/5 - >/dev/null 2>&1) \
+                                5<&0
+                    then
+                        gzip_status=$(
+                          exec 4>&1
+                          (gzip -cdfq -- "$1" 4>&-; echo $? >&4) 3>&- |
+                            ( (gzip -cdfq -- "$2" 4>&-; echo $? >&4) 3>&- 5<&- </dev/null |
+                               eval "$cmp" /dev/fd/5 - >&3) 5<&0
+                        )
                         cmp_status=$?
-			rm -f "$tmp" || gzip_status=$?
-			trap - HUP INT PIPE TERM 0
-			(exit $cmp_status)
-		    fi;;
-		*)
-		    gzip_status=$(
-		      exec 4>&1
-		      (gzip -cdfq -- "$1" 4>&-; echo $? >&4) 3>&- |
-		        eval "$cmp" - '"$2"' >&3
-		    );;
+                        case $gzip_status in
+                          *[1-9]*) gzip_status=1;;
+                          *) gzip_status=0;;
+                        esac
+                        (exit $cmp_status)
+                    else
+                        F=`expr "/$2" : '.*/\(.*\)[-.][zZtga]*$'` || F=$prog
+                        tmp=
+                        trap '
+                          test -n "$tmp" && rm -f "$tmp"
+                          (exit 2); exit 2
+                        ' HUP INT PIPE TERM 0
+                        if type mktemp >/dev/null 2>&1; then
+                          tmp=`mktemp -t -- "$F.XXXXXX"` || exit 2
+                        else
+                          set -C
+                          tmp=${TMPDIR-/tmp}/$F.$$
+                        fi
+                        gzip -cdfq -- "$2" > "$tmp" || exit 2
+                        gzip_status=$(
+                          exec 4>&1
+                          (gzip -cdfq -- "$1" 4>&-; echo $? >&4) 3>&- |
+                            eval "$cmp" - '"$tmp"' >&3
+                        )
+                        cmp_status=$?
+                        rm -f "$tmp" || gzip_status=$?
+                        trap - HUP INT PIPE TERM 0
+                        (exit $cmp_status)
+                    fi;;
+                *)
+                    gzip_status=$(
+                      exec 4>&1
+                      (gzip -cdfq -- "$1" 4>&-; echo $? >&4) 3>&- |
+                        eval "$cmp" - '"$2"' >&3
+                    );;
                 esac;;
         *)      case "$2" in
-		*[-.]gz* | *[-.][zZ] | *.t[ga]z | -)
-			gzip_status=$(
-			  exec 4>&1
-			  (gzip -cdfq -- "$2" 4>&-; echo $? >&4) 3>&- |
-			    eval "$cmp" '"$1"' - >&3
-			);;
-		*)	eval "$cmp" '"$1"' '"$2"';;
+                *[-.]gz* | *[-.][zZ] | *.t[ga]z | -)
+                        gzip_status=$(
+                          exec 4>&1
+                          (gzip -cdfq -- "$2" 4>&-; echo $? >&4) 3>&- |
+                            eval "$cmp" '"$1"' - >&3
+                        );;
+                *)	eval "$cmp" '"$1"' '"$2"';;
                 esac;;
-	esac
+        esac
 else
-	echo >&2 "$0: invalid number of operands; try \`$0 --help' for help"
-	exit 2
+        echo >&2 "$0: invalid number of operands; try \`$0 --help' for help"
+        exit 2
 fi
 
 cmp_status=$?
diff --git a/bin/zforce b/bin/zforce
--- a/bin/zforce
+++ b/bin/zforce
@@ -6,12 +6,12 @@
 # 12345678901234 is renamed to 12345678901.gz
 
 
-# Copyright (C) 2002, 2007 Free Software Foundation
+# Copyright (C) 2002, 2007, 2010 Free Software Foundation
 # Copyright (C) 1993 Jean-loup Gailly
 
 # This program is free software; you can redistribute it and/or modify
 # it under the terms of the GNU General Public License as published by
-# the Free Software Foundation; either version 2 of the License, or
+# the Free Software Foundation; either version 3 of the License, or
 # (at your option) any later version.
 
 # This program is distributed in the hope that it will be useful,
@@ -23,10 +23,14 @@
 # with this program; if not, write to the Free Software Foundation, Inc.,
 # 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.
 
-PATH="${GZIP_BINDIR-'/bin'}:$PATH"; export PATH
+bindir='/bin'
+case $1 in
+--__bindir) bindir=${2?}; shift; shift;;
+esac
+PATH=$bindir:$PATH; export PATH
 
-version="zforce (gzip) 1.3.12
-Copyright (C) 2007 Free Software Foundation, Inc.
+version="zforce (gzip) 1.5
+Copyright (C) 2010-2012 Free Software Foundation, Inc.
 This is free software.  You may redistribute copies of it under the terms of
 the GNU General Public License <http://www.gnu.org/licenses/gpl.html>.
 There is NO WARRANTY, to the extent permitted by law.
@@ -40,7 +44,7 @@ not compress them twice.
 Report bugs to <bug-gzip@gnu.org>."
 
 if test $# = 0; then
-  echo "$usage"
+  echo >&2 "$0: invalid number of operands; try \`$0 --help' for help"
   exit 1
 fi
 
diff --git a/bin/znew b/bin/znew
--- a/bin/znew
+++ b/bin/znew
@@ -1,11 +1,11 @@
 #!/bin/bash
 
-# Copyright (C) 1998, 2002, 2004, 2007 Free Software Foundation
+# Copyright (C) 1998, 2002, 2004, 2007, 2010 Free Software Foundation
 # Copyright (C) 1993 Jean-loup Gailly
 
 # This program is free software; you can redistribute it and/or modify
 # it under the terms of the GNU General Public License as published by
-# the Free Software Foundation; either version 2 of the License, or
+# the Free Software Foundation; either version 3 of the License, or
 # (at your option) any later version.
 
 # This program is distributed in the hope that it will be useful,
@@ -17,10 +17,14 @@
 # with this program; if not, write to the Free Software Foundation, Inc.,
 # 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.
 
-PATH="${GZIP_BINDIR-'/bin'}:$PATH"; export PATH
+bindir='/bin'
+case $1 in
+--__bindir) bindir=${2?}; shift; shift;;
+esac
+PATH=$bindir:$PATH; export PATH
 
-version="znew (gzip) 1.3.12
-Copyright (C) 2007 Free Software Foundation, Inc.
+version="znew (gzip) 1.5
+Copyright (C) 2010-2012 Free Software Foundation, Inc.
 This is free software.  You may redistribute copies of it under the terms of
 the GNU General Public License <http://www.gnu.org/licenses/gpl.html>.
 There is NO WARRANTY, to the extent permitted by law.
@@ -37,7 +41,7 @@ Options:
   -v     Verbose; display name and statistics for each file compressed.
   -9     Use the slowest compression method (optimal compression).
   -P     Use pipes for the conversion to reduce disk space usage.
-  -K     Keep a .Z file when it is smaller than the .gz file.
+  -K     Keep a .Z file when it is smaller than the .gz file; implies -t.
       --help     display this help and exit
       --version  output version information and exit
 
@@ -93,7 +97,7 @@ do
 done
 
 if test $# -eq 0; then
-  echo "$usage"
+  echo >&2 "$0: invalid number of operands; try \`$0 --help' for help"
   exit 1
 fi
 
@@ -102,7 +106,7 @@ case "$opt" in
   *t*) check=1; opt=`echo "$opt" | sed 's/t//g'`
 esac
 case "$opt" in
-  *K*) keep=1; opt=`echo "$opt" | sed 's/K//g'`
+  *K*) keep=1; check=1; opt=`echo "$opt" | sed 's/K//g'`
 esac
 case "$opt" in
   *P*) pipe=1; opt=`echo "$opt" | sed 's/P//g'`
@@ -129,9 +133,9 @@ for i do
   else
     if test $check -eq 1; then
       if cp -p "$n.Z" "$n.$$" 2> /dev/null || cp "$n.Z" "$n.$$"; then
-	:
+        :
       else
-	echo cannot backup "$n.Z"
+        echo cannot backup "$n.Z"
         res=1; continue
       fi
     fi
@@ -146,10 +150,10 @@ for i do
       :
     else
       if test $check -eq 1; then
-	mv "$n.$$" "$n.Z" && rm -f "$n"
+        mv "$n.$$" "$n.Z" && rm -f "$n"
         echo error while recompressing $n
       else
-	# compress $n  (might be dangerous if disk full)
+        # compress $n  (might be dangerous if disk full)
         echo error while recompressing $n, left uncompressed
       fi
       res=1; continue
@@ -157,13 +161,11 @@ for i do
   fi
   test $keep -eq 1 && new=`wc -c < "$n$ext"`
   if test $keep -eq 1 && test `expr \( $old + $block - 1 \) / $block` -lt \
-			      `expr \( $new + $block - 1 \) / $block`; then
+                              `expr \( $new + $block - 1 \) / $block`; then
     if test $pipe -eq 1; then
       rm -f "$n$ext"
-    elif test $check -eq 1; then
-      mv "$n.$$" "$n.Z" && rm -f "$n$ext"
     else
-      gzip -d "$n$ext" && compress "$n" && rm -f "$n$ext"
+      mv "$n.$$" "$n.Z" && rm -f "$n$ext"
     fi
     echo "$n.Z smaller than $n$ext -- unchanged"
 
diff --git a/etc/init.d/skeleton b/etc/init.d/skeleton
--- a/etc/init.d/skeleton
+++ b/etc/init.d/skeleton
@@ -116,8 +116,8 @@ case "$1" in
 	esac
 	;;
   status)
-       status_of_proc "$DAEMON" "$NAME" && exit 0 || exit $?
-       ;;
+	status_of_proc "$DAEMON" "$NAME" && exit 0 || exit $?
+	;;
   #reload|force-reload)
 	#
 	# If do_reload() is not implemented then leave this commented out
@@ -144,7 +144,7 @@ case "$1" in
 		esac
 		;;
 	  *)
-	  	# Failed to stop
+		# Failed to stop
 		log_end_msg 1
 		;;
 	esac
diff --git a/etc/init.d/udev b/etc/init.d/udev
--- a/etc/init.d/udev
+++ b/etc/init.d/udev
@@ -5,7 +5,6 @@
 # Required-Stop:     
 # Default-Start:     S
 # Default-Stop:
-# X-Interactive:     true
 # Short-Description: Start udevd, populate /dev and load drivers.
 ### END INIT INFO
 
@@ -28,7 +27,7 @@ mount_tmpfs() {
   fi
 
   if ! mount -n -o $dev_mount_options -t tmpfs tmpfs /dev; then
-    log_failure_msg "udev requires tmpfs support, not started."
+    log_failure_msg "udev requires tmpfs support, not started"
     log_end_msg 1
   fi
 
@@ -43,11 +42,22 @@ create_dev_makedev() {
   fi
 }
 
+# If the initramfs does not have /run, the initramfs udev database must
+# be migrated from /dev/.udev/ to /run/udev/.
+move_udev_database() {
+  [ -e "$udev_root/.udev/" ] || return 0
+  [ ! -e /run/udev/ ] || return 0
+  [ -e /run/ ] || return 0
+  mountpoint -q /run/ || return 0
+
+  mv $udev_root/.udev/ /run/udev/ || true
+}
+
 supported_kernel() {
   case "$(uname -r)" in
     2.[012345].*|2.6.[0-9]|2.6.[0-9][!0-9]*) return 1 ;;
-    2.6.1[0-9]|2.6.1[0-9][!0-9]*) return 1 ;;
-    2.6.2[0-5]|2.6.2[0-5][!0-9]*) return 1 ;;
+    2.6.[12][0-9]|2.6.[12][0-9][!0-9]*) return 1 ;;
+    2.6.3[0-1]|2.6.3[0-1][!0-9]*) return 1 ;;
   esac
   return 0
 }
@@ -77,19 +87,6 @@ warn_if_interactive() {
   sleep 60
 }
 
-create_dev_root_rule() {
-  local udevroot="$1"
-  [ -e $udevroot/rules.d/61-dev-root-link.rules ] && return 0
-
-  eval $(udevadm info --export --export-prefix=ROOT_ --device-id-of-file=/ \
-    || true)
-  [ "$ROOT_MAJOR" -a "$ROOT_MINOR" ] || return 0
-
-  echo 'ACTION=="add|change", SUBSYSTEM=="block", ENV{MAJOR}=="'$ROOT_MAJOR'", ENV{MINOR}=="'$ROOT_MINOR'", SYMLINK+="root"' \
-    > $udevroot/root-link-rule
-  mv $udevroot/root-link-rule $udevroot/rules.d/61-dev-root-link.rules
-}
-
 ##############################################################################
 
 [ -x /sbin/udevd ] || exit 0
@@ -107,33 +104,40 @@ fi
 . /lib/lsb/init-functions
 
 if ! supported_kernel; then
-  log_failure_msg "udev requires a kernel >= 2.6.26, not started."
+  log_failure_msg "udev requires a kernel >= 2.6.32, not started"
   log_end_msg 1
 fi
 
 if [ ! -e /proc/filesystems ]; then
-  log_failure_msg "udev requires a mounted procfs, not started."
+  log_failure_msg "udev requires a mounted procfs, not started"
   log_end_msg 1
 fi
 
 if ! grep -q '[[:space:]]tmpfs$' /proc/filesystems; then
-  log_failure_msg "udev requires tmpfs support, not started."
+  log_failure_msg "udev requires tmpfs support, not started"
   log_end_msg 1
 fi
 
 if [ ! -d /sys/class/ ]; then
-  log_failure_msg "udev requires a mounted sysfs, not started."
+  log_failure_msg "udev requires a mounted sysfs, not started"
   log_end_msg 1
 fi
 
 if [ ! -e /sys/kernel/uevent_helper ]; then
-  log_failure_msg "udev requires hotplug support, not started."
+  log_failure_msg "udev requires hotplug support, not started"
   log_end_msg 1
 fi
 
 if ! ps --no-headers --format args ax | egrep -q '^\['; then
   log_warning_msg "udev does not support containers, not started"
   exit 0
+fi
+
+if [ -d /sys/class/mem/null -a ! -L /sys/class/mem/null ] || \
+   [ -e /sys/block -a ! -e /sys/class/block ]; then
+  log_warning_msg "CONFIG_SYSFS_DEPRECATED must not be selected"
+  log_warning_msg "Booting will continue in 30 seconds but many things will be broken"
+  sleep 30
 fi
 
 ##############################################################################
@@ -156,13 +160,9 @@ if [ "$udev_root" != "/dev" ]; then
 
 case "$1" in
     start)
-    if [ -e "$udev_root/.udev/" ]; then
-	if mountpoint -q $udev_root/; then
-	    log_failure_msg "udev is already active on $udev_root."
-	    log_end_msg 1
-	else
-	    log_warning_msg ".udev/ already exists on the static $udev_root!"
-	fi
+    if mountpoint -q $udev_root/; then
+	log_failure_msg "$udev_root is already mounted"
+	log_end_msg 1
     fi
 
     echo > /sys/kernel/uevent_helper
@@ -173,13 +173,14 @@ case "$1" in
     if udevd --daemon; then
 	log_end_msg $?
     else
-	log_end_msg $?
+	log_warning_msg $?
+	log_warning_msg "Waiting 15 seconds and trying to continue anyway"
+	sleep 15
     fi
 
-    mkdir -p $udev_root/.udev/rules.d/
-    create_dev_root_rule $udev_root/.udev/
+    /lib/udev/write_dev_root_rule
 
-    log_action_begin_msg "Synthesizing initial hotplug events"
+    log_action_begin_msg "Synthesizing the initial hotplug events"
     if udevadm trigger --action=add; then
 	log_action_end_msg $?
     else
@@ -189,7 +190,7 @@ case "$1" in
     ;;
     stop)
     log_daemon_msg "Stopping the hotplug events dispatcher" "udevd"
-    if start-stop-daemon --stop --name udevd --quiet --oknodo --retry 5; then
+    if start-stop-daemon --stop --name udevd --user root --quiet --oknodo --retry 5; then
 	log_end_msg $?
     else
 	log_end_msg $?
@@ -205,16 +206,31 @@ case "$1" in
     ;;
 
     restart)
-    $0 stop
-    $0 start
+    log_daemon_msg "Stopping the hotplug events dispatcher" "udevd"
+    if start-stop-daemon --stop --name udevd --user root --quiet --oknodo --retry 5; then
+	log_end_msg $?
+    else
+	log_end_msg $? || true
+    fi
+
+    log_daemon_msg "Starting the hotplug events dispatcher" "udevd"
+    if udevd --daemon; then
+	log_end_msg $?
+    else
+	log_end_msg $?
+    fi
     ;;
 
     reload|force-reload)
     udevadm control --reload-rules
     ;;
 
+    status)
+    status_of_proc /sbin/udevd udevd && exit 0 || exit $?
+    ;;
+
     *)
-    echo "Usage: /etc/init.d/udev {start|stop|restart|reload|force-reload}"
+    echo "Usage: /etc/init.d/udev {start|stop|restart|reload|force-reload|status}" >&2
     exit 1
     ;;
 esac
@@ -230,26 +246,28 @@ fi # udev_root != /dev
 
 case "$1" in
     start)
-    if [ -e "$udev_root/.udev/" ]; then
-	if mountpoint -q $udev_root/; then
-	    TMPFS_MOUNTED=1
-	else
-	    log_warning_msg ".udev/ already exists on the static $udev_root!"
-	fi
-    else
+    if mountpoint -q $udev_root/; then
+	TMPFS_MOUNTED=1
+    elif [ -e "$udev_root/.udev/" ]; then
+	log_warning_msg ".udev/ already exists on the static $udev_root"
+    fi
+
+    if [ ! -e "$udev_root/.udev/" -a ! -e "/run/udev/" ]; then
 	warn_if_interactive
     fi
 
     echo > /sys/kernel/uevent_helper
 
+    move_udev_database
+
     if [ -z "$TMPFS_MOUNTED" ]; then
 	unmount_devpts
 	mount_tmpfs
 	[ -d /proc/1 ] || mount -n /proc
-    else
-	# and clean up the database of the initramfs udev
-	rm -rf /dev/.udev/
     fi
+
+    # clean up parts of the database created by the initramfs udev
+    udevadm info --cleanup-db
 
     # set the SELinux context for devices created in the initramfs
     [ -x /sbin/restorecon ] && /sbin/restorecon -R /dev
@@ -261,11 +279,12 @@ case "$1" in
     if udevd --daemon; then
 	log_end_msg $?
     else
-	log_end_msg $?
+	log_warning_msg $?
+	log_warning_msg "Waiting 15 seconds and trying to continue anyway"
+	sleep 15
     fi
 
-    mkdir -p /dev/.udev/rules.d/
-    create_dev_root_rule /dev/.udev/
+    /lib/udev/write_dev_root_rule
 
     log_action_begin_msg "Synthesizing the initial hotplug events"
     if udevadm trigger --action=add; then
@@ -287,7 +306,7 @@ case "$1" in
 
     stop)
     log_daemon_msg "Stopping the hotplug events dispatcher" "udevd"
-    if start-stop-daemon --stop --name udevd --quiet --oknodo --retry 5; then
+    if start-stop-daemon --stop --name udevd --user root --quiet --oknodo --retry 5; then
 	log_end_msg $?
     else
 	log_end_msg $?
@@ -296,7 +315,7 @@ case "$1" in
 
     restart)
     log_daemon_msg "Stopping the hotplug events dispatcher" "udevd"
-    if start-stop-daemon --stop --name udevd --quiet --oknodo --retry 5; then
+    if start-stop-daemon --stop --name udevd --user root --quiet --oknodo --retry 5; then
 	log_end_msg $?
     else
 	log_end_msg $? || true
@@ -314,8 +333,12 @@ case "$1" in
     udevadm control --reload-rules
     ;;
 
+    status)
+    status_of_proc /sbin/udevd udevd && exit 0 || exit $?
+    ;;
+
     *)
-    echo "Usage: /etc/init.d/udev {start|stop|restart|reload|force-reload}"
+    echo "Usage: /etc/init.d/udev {start|stop|restart|reload|force-reload|status}" >&2
     exit 1
     ;;
 esac
diff --git a/etc/init.d/urandom b/etc/init.d/urandom
--- a/etc/init.d/urandom
+++ b/etc/init.d/urandom
@@ -1,7 +1,7 @@
 #! /bin/sh
 ### BEGIN INIT INFO
 # Provides:          urandom
-# Required-Start:    $local_fs
+# Required-Start:    $local_fs $time
 # Required-Stop:     $local_fs
 # Default-Start:     S
 # Default-Stop:      0 6
@@ -10,12 +10,24 @@
 #                    It is called from the boot, halt and reboot scripts.
 ### END INIT INFO
 
+## Assumption 1:  We assume $SAVEDFILE is a file (or a symlink
+## to a file) that resides on a non-volatile medium that persists
+## across reboots.
+## Case 1a: Ideally, it is readable and writeable.  Its is unshared,
+## i.e. its contents are unique to this machine.  It is protected so
+## that its contents are not known to attackers.
+## Case 1b: Less than ideally, it is read-only.  Its contents are
+## unique to this machine and not known to attackers.
+SAVEDFILE=/var/lib/urandom/random-seed
+
 [ -c /dev/urandom ] || exit 0
 
 PATH=/sbin:/bin
-SAVEDFILE=/var/lib/urandom/random-seed
-POOLSIZE=512
-[ -f /proc/sys/kernel/random/poolsize ] && POOLSIZE="$(cat /proc/sys/kernel/random/poolsize)"
+if ! POOLBYTES=$((
+  ($(cat /proc/sys/kernel/random/poolsize 2>/dev/null) + 7) / 8
+)) ; then
+  POOLBYTES=512
+fi
 . /lib/init/vars.sh
 
 . /lib/lsb/init-functions
@@ -31,34 +43,49 @@ do_status () {
 case "$1" in
   start|"")
 	[ "$VERBOSE" = no ] || log_action_begin_msg "Initializing random number generator"
-	# Load and then save $POOLSIZE bytes,
-	# which is the size of the entropy pool
-	if [ -f "$SAVEDFILE" ]
-	then
-		# Handle locally increased pool size
-		set -- $(LC_ALL=C ls -l "$SAVEDFILE")
-		SAVEDSIZE="$5"
-		if [ "$SAVEDSIZE" -gt "$POOLSIZE" ]
-		then
-			[ -w /proc/sys/kernel/random/poolsize ] && echo $POOLSIZE > /proc/sys/kernel/random/poolsize
-			POOLSIZE=$SAVEDSIZE
-		fi
-		cat "$SAVEDFILE" >/dev/urandom
-	fi
-	rm -f $SAVEDFILE
-	# Hm, why is the saved pool re-created at boot? [pere 2009-09-03]
+	# Seed the RNG with date and time.
+	# This is helpful in the less-than-ideal case where $SAVEDFILE
+	# is read-only.
+	# The value of this is greatly reduced if $SAVEDFILE is missing,
+	# or its contents are shared machine-to-machine or known to
+	# attackers (since they might well know at what time this
+	# machine booted up).
+	(
+	  date +%s.%N
+
+	  # Load and then save $POOLBYTES bytes,
+	  # which is the size of the entropy pool
+	  if [ -f "$SAVEDFILE" ]
+	  then
+		  cat "$SAVEDFILE"
+	  fi
+	# Redirect output of subshell (not individual commands)
+	# to cope with a misfeature in the FreeBSD (not Linux)
+	# /dev/random, where every superuser write/close causes
+	# an explicit reseed of the yarrow.
+	) >/dev/urandom
+
+	# Write a new seed into $SAVEDFILE because re-using a seed
+	# compromises security.  Each time we re-seed, we want the
+	# seed to be as different as possible.
+	# Write it now, in case the machine crashes without doing
+	# an orderly shutdown.
+	# The write will fail if $SAVEDFILE is read-only, but it
+	# doesn't hurt to try.
 	umask 077
-	dd if=/dev/urandom of=$SAVEDFILE bs=$POOLSIZE count=1 >/dev/null 2>&1
+	dd if=/dev/urandom of=$SAVEDFILE bs=$POOLBYTES count=1 >/dev/null 2>&1
 	ES=$?
 	umask 022
 	[ "$VERBOSE" = no ] || log_action_end_msg $ES
 	;;
   stop)
 	# Carry a random seed from shut-down to start-up;
+	# Write it on shutdown, in case the one written at startup
+	# has been lost, snooped, or otherwise compromised.
 	# see documentation in linux/drivers/char/random.c
 	[ "$VERBOSE" = no ] || log_action_begin_msg "Saving random seed"
 	umask 077
-	dd if=/dev/urandom of=$SAVEDFILE bs=$POOLSIZE count=1 >/dev/null 2>&1
+	dd if=/dev/urandom of=$SAVEDFILE bs=$POOLBYTES count=1 >/dev/null 2>&1
 	ES=$?
 	[ "$VERBOSE" = no ] || log_action_end_msg $ES
 	;;
diff --git a/etc/init.d/x11-common b/etc/init.d/x11-common
--- a/etc/init.d/x11-common
+++ b/etc/init.d/x11-common
@@ -2,17 +2,17 @@
 # /etc/init.d/x11-common: set up the X server and ICE socket directories
 ### BEGIN INIT INFO
 # Provides:          x11-common
-# Required-Start:    $local_fs
-# Required-Stop:     $local_fs
+# Required-Start:    $remote_fs
+# Required-Stop:     $remote_fs
 # Default-Start:     S
 # Default-Stop:
 ### END INIT INFO
 
 set -e
 
-PATH=/bin:/sbin
-SOCKET_DIR=/tmp/.X11-unix
-ICE_DIR=/tmp/.ICE-unix
+PATH=/usr/bin:/usr/sbin:/bin:/sbin
+SOCKET_DIR=.X11-unix
+ICE_DIR=.ICE-unix
 
 . /lib/lsb/init-functions
 if [ -f /etc/default/rcS ]; then
@@ -26,36 +26,60 @@ do_restorecon () {
   fi
 }
 
-set_up_socket_dir () {
-  if [ "$VERBOSE" != no ]; then
-    log_begin_msg "Setting up X server socket directory $SOCKET_DIR..."
-  fi
-  if [ -e $SOCKET_DIR ] && [ ! -d $SOCKET_DIR ]; then
-    mv $SOCKET_DIR $SOCKET_DIR.$$
-  fi
-  mkdir -p $SOCKET_DIR
-  chown root:root $SOCKET_DIR
-  chmod 1777 $SOCKET_DIR
-  do_restorecon $SOCKET_DIR
-  [ "$VERBOSE" != no ] && log_end_msg 0 || return 0
-}
+# create a directory in /tmp.
+# assumes /tmp has a sticky bit set (or is only writeable by root)
+set_up_dir () {
+  DIR="/tmp/$1"
 
-set_up_ice_dir () {
   if [ "$VERBOSE" != no ]; then
-    log_begin_msg "Setting up ICE socket directory $ICE_DIR..."
+    log_progress_msg "$DIR"
   fi
-  if [ -e $ICE_DIR ] && [ ! -d $ICE_DIR ]; then
-    mv $ICE_DIR $ICE_DIR.$$
+  # if $DIR exists and isn't a directory, move it aside
+  if [ -e $DIR ] && ! [ -d $DIR ] || [ -h $DIR ]; then
+    mv "$DIR" "$(mktemp -d $DIR.XXXXXX)"
   fi
-  mkdir -p $ICE_DIR
-  chown root:root $ICE_DIR
-  chmod 1777 $ICE_DIR
-  do_restorecon $ICE_DIR
-  [ "$VERBOSE" != no ] && log_end_msg 0 || return 0
+
+  error=0
+  while :; do
+    if [ $error -ne 0 ] ; then
+      # an error means the file-system is readonly or an attacker
+      # is doing evil things, distinguish by creating a temporary file,
+      # but give up after a while.
+      if [ $error -gt 5 ]; then
+        log_failure_msg "failed to set up $DIR"
+        return 1
+      fi
+      fn="$(mktemp /tmp/testwriteable.XXXXXXXXXX)" || return 1
+      rm "$fn"
+    fi
+    mkdir -p -m 01777 "$DIR" || { rm "$DIR" || error=$((error + 1)) ; continue ; }
+    case "$(LC_ALL=C stat -c '%u %g %a %F' "$DIR")" in
+      "0 0 1777 directory")
+        # everything as it is supposed to be
+        break
+        ;;
+      "0 0 "*" directory")
+        # as it is owned by root, cannot be replaced with a symlink:
+        chmod 01777 "$DIR"
+        break
+        ;;
+      *" directory")
+        # if the chown succeeds, the next step can change it savely
+        chown -h root:root "$DIR" || error=$((error + 1))
+        continue
+        ;;
+      *)
+        log_failure_msg "failed to set up $DIR"
+        return 1
+        ;;
+    esac
+  done
+
+  return 0
 }
 
 do_status () {
-    if [ -d $ICE_DIR ] && [ -d $SOCKET_DIR ]; then
+    if [ -d "/tmp/$ICE_DIR" ] && [ -d "/tmp/$SOCKET_DIR" ]; then
       return 0
     else
       return 4
@@ -64,8 +88,14 @@ do_status () {
 
 case "$1" in
   start)
-    set_up_socket_dir
-    set_up_ice_dir
+    if [ "$VERBOSE" != no ]; then
+      log_begin_msg "Setting up X socket directories..."
+    fi
+    set_up_dir "$SOCKET_DIR"
+    set_up_dir "$ICE_DIR"
+    if [ "$VERBOSE" != no ]; then
+      log_end_msg 0
+    fi
   ;;
 
   restart|reload|force-reload)
diff --git a/lib/lsb/init-functions b/lib/lsb/init-functions
--- a/lib/lsb/init-functions
+++ b/lib/lsb/init-functions
@@ -27,21 +27,16 @@
 #OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE,
 #EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 
-# only show errors
-. /etc/webc/functions.sh
-. /etc/webc/webc.conf
-cmdline | grep -qs quiet && exec >/dev/null
-
 start_daemon () {
-    local force nice pidfile exec i args
-    force=0
+    local force nice pidfile exec args OPTIND
+    force=""
     nice=0
     pidfile=/dev/null
 
     OPTIND=1
     while getopts fn:p: opt ; do
         case "$opt" in
-            f)  force=1;;
+            f)  force="force";;
             n)  nice="$OPTARG";;
             p)  pidfile="$OPTARG";;
         esac
@@ -55,24 +50,28 @@ start_daemon () {
     exec="$1"; shift
 
     args="--start --nicelevel $nice --quiet --oknodo"
-    if [ $force = 1 ]; then
-        /sbin/start-stop-daemon $args --chdir "$PWD" --startas $exec --pidfile /dev/null -- "$@"
+    if [ "$force" ]; then
+        /sbin/start-stop-daemon $args \
+	    --chdir "$PWD" --startas $exec --pidfile /dev/null -- "$@"
     elif [ $pidfile ]; then
-        /sbin/start-stop-daemon $args --chdir "$PWD" --exec $exec --oknodo --pidfile "$pidfile" -- "$@"
+        /sbin/start-stop-daemon $args \
+	    --chdir "$PWD" --exec $exec --oknodo --pidfile "$pidfile" -- "$@"
     else
         /sbin/start-stop-daemon $args --chdir "$PWD" --exec $exec -- "$@"
     fi
 }
 
 pidofproc () {
-    local pidfile line i pids= status specified pid
+    local pidfile base status specified pid OPTIND
     pidfile=
     specified=
     
     OPTIND=1
     while getopts p: opt ; do
         case "$opt" in
-            p)  pidfile="$OPTARG"; specified=1;;
+            p)  pidfile="$OPTARG"
+                specified="specified"
+		;;
         esac
     done
     shift $(($OPTIND - 1))
@@ -82,37 +81,49 @@ pidofproc () {
         pidfile="/var/run/$base.pid"
     fi
 
-    if [ -n "${pidfile:-}" -a -r "$pidfile" ]; then
+    if [ -n "${pidfile:-}" ]; then
+     if [ -e "$pidfile" ]; then
+      if [ -r "$pidfile" ]; then
         read pid < "$pidfile"
         if [ -n "${pid:-}" ]; then
             if $(kill -0 "${pid:-}" 2> /dev/null); then
-                echo "$pid"
+                echo "$pid" || true
                 return 0
             elif ps "${pid:-}" >/dev/null 2>&1; then
-                echo "$pid"
+                echo "$pid" || true
                 return 0 # program is running, but not owned by this user
             else
                 return 1 # program is dead and /var/run pid file exists
             fi
         fi
+      else
+        return 4 # pid file not readable, hence status is unknown.
+      fi
+     else
+       # pid file doesn't exist, try to find the pid nevertheless
+       if [ -x /bin/pidof ] && [ ! "$specified" ]; then
+         status="0"
+         /bin/pidof -o %PPID -x $1 || status="$?"
+         if [ "$status" = 1 ]; then
+             return 3 # program is not running
+         fi
+         return 0
+       fi
+       return 3 # specified pid file doesn't exist, program probably stopped
+     fi
     fi
-    if [ -x /bin/pidof -a ! "$specified" ]; then
-        status="0"
-        /bin/pidof -o %PPID -x $1 || status="$?"
-        if [ "$status" = 1 ]; then
-            return 3 # program is not running
-        fi
-        return 0
+    if [ "$specified" ]; then
+        return 3 # almost certain it's not running
     fi
     return 4 # Unable to determine status
 }
 
 # start-stop-daemon uses the same algorithm as "pidofproc" above.
 killproc () {
-    local pidfile sig status base i name_param is_term_sig
+    local pidfile sig status base name_param is_term_sig OPTIND
     pidfile=
     name_param=
-    is_term_sig=no
+    is_term_sig=
 
     OPTIND=1
     while getopts p: opt ; do
@@ -131,27 +142,31 @@ killproc () {
 
     sig=$(echo ${2:-} | sed -e 's/^-\(.*\)/\1/')
     sig=$(echo $sig | sed -e 's/^SIG\(.*\)/\1/')
-    if [ -z "$sig" -o "$sig" = 15 -o "$sig" = TERM ]; then
-        is_term_sig=yes
+    if [ "$sig" = 15 ] || [ "$sig" = TERM ]; then
+        is_term_sig="terminate_signal"
     fi
     status=0
-    if [ ! "$is_term_sig" = yes ]; then
+    if [ ! "$is_term_sig" ]; then
         if [ -n "$sig" ]; then
-            /sbin/start-stop-daemon --stop --signal "$sig" --quiet $name_param || status="$?"
+            /sbin/start-stop-daemon --stop --signal "$sig" \
+		--quiet $name_param || status="$?"
         else
-            /sbin/start-stop-daemon --stop --quiet $name_param || status="$?"
+            /sbin/start-stop-daemon --stop \
+		--retry 5 \
+		--quiet $name_param || status="$?"
         fi
     else
-        /sbin/start-stop-daemon --stop --quiet --oknodo $name_param || status="$?"
+        /sbin/start-stop-daemon --stop --quiet \
+	    --oknodo $name_param || status="$?"
     fi
     if [ "$status" = 1 ]; then
-        if [ -n "$sig" ]; then
+        if [ -z "$sig" ]; then
             return 0
         fi
         return 3 # program is not running
     fi
 
-    if [ "$status" = 0 -a "$is_term_sig" = yes -a "$pidfile" ]; then
+    if [ "$status" = 0 ] && [ "$is_term_sig" ] && [ "$pidfile" ]; then
         pidofproc -p "$pidfile" "$1" >/dev/null || rm -f "$pidfile"
     fi
     return 0
@@ -159,7 +174,7 @@ killproc () {
 
 # Return LSB status
 status_of_proc () {
-    local pidfile daemon name status
+    local pidfile daemon name status OPTIND
 
     pidfile=
     OPTIND=1
@@ -193,7 +208,13 @@ status_of_proc () {
 log_use_fancy_output () {
     TPUT=/usr/bin/tput
     EXPR=/usr/bin/expr
-    if [ -t 1 ] && [ "x${TERM:-}" != "x" ] && [ "x${TERM:-}" != "xdumb" ] && [ -x $TPUT ] && [ -x $EXPR ] && $TPUT hpa 60 >/dev/null 2>&1 && $TPUT setaf 1 >/dev/null 2>&1; then
+    if  [ -t 1 ] &&
+	[ "x${TERM:-}" != "x" ] &&
+	[ "x${TERM:-}" != "xdumb" ] &&
+	[ -x $TPUT ] && [ -x $EXPR ] &&
+	$TPUT hpa 60 >/dev/null 2>&1 &&
+	$TPUT setaf 1 >/dev/null 2>&1
+    then
         [ -z $FANCYTTY ] && FANCYTTY=1 || true
     else
         FANCYTTY=0
@@ -238,12 +259,25 @@ get_lsb_header_val () {
         sed -n "/$LSB_S/,/$LSB_E/ s/# $2: \(.*\)/\1/p" $1
 }
 
+# If the currently running init daemon is upstart, return zero; if the
+# calling init script belongs to a package which also provides a native
+# upstart job, it should generally exit non-zero in this case.
+init_is_upstart()
+{
+   if [ -x /sbin/initctl ] && /sbin/initctl version 2>/dev/null | /bin/grep -q upstart; then
+       return 0
+   fi
+   return 1
+}
+
 # int log_begin_message (char *message)
 log_begin_msg () {
+    log_begin_msg_pre "$@"
     if [ -z "${1:-}" ]; then
         return 1
     fi
-    echo -n "$@"
+    /bin/echo -n "$@" || true
+    log_begin_msg_post "$@"
 }
 
 # Sample usage:
@@ -267,11 +301,11 @@ log_daemon_msg () {
     log_daemon_msg_pre "$@"
 
     if [ -z "${2:-}" ]; then
-        echo -n "$1:"
+        /bin/echo -n "$1:" || true
         return
     fi
     
-    echo -n "$1: $2"
+    /bin/echo -n "$1: $2" || true
     log_daemon_msg_post "$@"
 }
 
@@ -294,7 +328,7 @@ log_progress_msg () {
     if [ -z "${1:-}" ]; then
         return 1
     fi
-    echo -n " $@"
+    /bin/echo -n " $@" || true
 }
 
 
@@ -305,6 +339,7 @@ log_end_msg () {
         return 1
     fi
 
+    local retval
     retval=$1
 
     log_end_msg_pre "$@"
@@ -312,9 +347,9 @@ log_end_msg () {
     # Only do the fancy stuff if we have an appropriate terminal
     # and if /usr is already mounted
     if log_use_fancy_output; then
-        RED=`$TPUT setaf 1`
-        YELLOW=`$TPUT setaf 3`
-        NORMAL=`$TPUT op`
+        RED=$( $TPUT setaf 1)
+        YELLOW=$( $TPUT setaf 3)
+        NORMAL=$( $TPUT op)
     else
         RED=''
         YELLOW=''
@@ -322,29 +357,34 @@ log_end_msg () {
     fi
 
     if [ $1 -eq 0 ]; then
-        echo "."
+        echo "." || true
     elif [ $1 -eq 255 ]; then
-        /bin/echo -e " ${YELLOW}(warning).${NORMAL}"
+        /bin/echo -e " ${YELLOW}(warning).${NORMAL}" || true
     else
-        /bin/echo -e " ${RED}failed!${NORMAL}"
+        /bin/echo -e " ${RED}failed!${NORMAL}" || true
     fi
     log_end_msg_post "$@"
     return $retval
 }
 
 log_action_msg () {
-    echo "$@."
+    log_action_msg_pre "$@"
+    echo "$@." || true
+    log_action_msg_post "$@"
 }
 
 log_action_begin_msg () {
-    echo -n "$@..."
+    log_action_begin_msg_pre "$@"
+    /bin/echo -n "$@..." || true
+    log_action_begin_msg_post "$@"
 }
 
 log_action_cont_msg () {
-    echo -n "$@..."
+    /bin/echo -n "$@..." || true
 }
 
 log_action_end_msg () {
+    local end
     log_action_end_msg_pre "$@"
     if [ -z "${2:-}" ]; then
         end="."
@@ -353,26 +393,37 @@ log_action_end_msg () {
     fi
 
     if [ $1 -eq 0 ]; then
-        echo "done${end}"
+        echo "done${end}" || true
     else
         if log_use_fancy_output; then
-            RED=`$TPUT setaf 1`
-            NORMAL=`$TPUT op`
-            echo -e "${RED}failed${end}${NORMAL}"
+            RED=$( $TPUT setaf 1)
+            NORMAL=$( $TPUT op)
+            /bin/echo -e "${RED}failed${end}${NORMAL}" || true
         else
-            echo "failed${end}"
+            echo "failed${end}" || true
         fi
     fi
     log_action_end_msg_post "$@"
 }
 
-# Hooks for /etc/lsb-base-logging.sh
+# Pre&Post empty function declaration, to be overriden from /lib/lsb/init-functions.d/*
 log_daemon_msg_pre () { :; }
 log_daemon_msg_post () { :; }
+log_begin_msg_pre () { :; }
+log_begin_msg_post () { :; }
 log_end_msg_pre () { :; }
 log_end_msg_post () { :; }
+log_action_msg_pre () { :; }
+log_action_msg_post () { :; }
+log_action_begin_msg_pre () { :; }
+log_action_begin_msg_post () { :; }
 log_action_end_msg_pre () { :; }
 log_action_end_msg_post () { :; }
+
+# Include hooks from other packages in /lib/lsb/init-functions.d
+for hook in $(run-parts --lsbsysinit --list /lib/lsb/init-functions.d 2>/dev/null); do
+    [ -r $hook ] && . $hook || true
+done
 
 FANCYTTY=
 [ -e /etc/lsb-base-logging.sh ] && . /etc/lsb-base-logging.sh || true
diff --git a/usr/share/initramfs-tools/hooks/keymap b/usr/share/initramfs-tools/hooks/keymap
--- a/usr/share/initramfs-tools/hooks/keymap
+++ b/usr/share/initramfs-tools/hooks/keymap
@@ -21,19 +21,23 @@ if [ "$KEYMAP" != "y" ] && [ "$KEYMAP" != "Y" ]; then
 fi
 
 # Step 1 - Basic tools
-if [ ! -x /bin/loadkeys ] ||
-! ( [ -r /etc/console/boottime.kmap.gz ] \
-	|| [ -r /etc/console-setup/cached.kmap.gz ] ); then
+if [ ! -x /bin/loadkeys ]; then
+	echo "loadkeys is missing. Please install the 'kbd' package."
+	exit 0
+fi
+
+if [ ! -x /bin/setupcon ]; then
+	echo "setupcon is missing. Please install the 'console-setup' package."
 	exit 0
 fi
 
 . /usr/share/initramfs-tools/hook-functions
 copy_exec /bin/loadkeys /bin
 
-if [ -e /etc/console-setup/cached.kmap.gz ]; then
-	cp /etc/console-setup/cached.kmap.gz ${DESTDIR}/etc/boottime.kmap.gz
-else
-	cp /etc/console/boottime.kmap.gz ${DESTDIR}/etc/
+if ! setupcon --save-keyboard ${DESTDIR}/etc/boottime.kmap.gz ; then
+	echo "Warning: error while trying to store keymap file - ignoring request to install /etc/boottime.kmap.gz"
+	rm -f ${DESTDIR}/etc/boottime.kmap.gz
+	exit 0
 fi
 
 # Step 2 - Check for UTF8 console
diff --git a/var/lib/dpkg/info/firmware-b43-installer.postinst b/var/lib/dpkg/info/firmware-b43-installer.postinst
--- a/var/lib/dpkg/info/firmware-b43-installer.postinst
+++ b/var/lib/dpkg/info/firmware-b43-installer.postinst
@@ -4,49 +4,131 @@ set -e
 
 tmp=`mktemp -q -d`
 
+latest_firmware ()
+{
+cd $tmp
+export FIRMWARE_INSTALL_DIR="/lib/firmware"
+
+# use apt proxy
+APT_PROXIES=$(apt-config shell \
+http_proxy Acquire::http::Proxy \
+https_proxy Acquire::https::Proxy \
+ftp_proxy Acquire::ftp::Proxy \
+)
+
+if [ -n "$APT_PROXIES" ]; then
+        eval export $APT_PROXIES
+fi
+
+wget --timeout=60 http://www.lwfinger.com/b43-firmware/broadcom-wl-5.100.138.tar.bz2
+if [ $? -ne 0 ]; then
+	echo "Some problem occurred during the firmware download. Please check your internet connection." 
+	exit 0
+    else
+	if [ -d /lib/firmware/b43 ]; then
+	   echo "Deleting old extracted firmware..."
+	   rm -rf /lib/firmware/b43
+	fi
+	if [ ! -d /lib/firmware/b43 ]; then
+	   echo "Creating new firmware directory..."
+      		mkdir -p /lib/firmware/b43
+        fi
+fi
+tar xvjf broadcom-wl-5.100.138.tar.bz2
+cd broadcom-wl-5.100.138/linux
+b43-fwcutter -w "$FIRMWARE_INSTALL_DIR" wl_apsta.o
+rm -rf $tmp
+}
+
+# check environment
+if [ "$(stat -c %d/%i /)" != "$(stat -Lc %d/%i /proc/1/root 2>/dev/null)" ];
+ then
+    echo "A chroot environment has been detected."
+    echo "Remember this firmware needs kernel >= 2.6.25."
+    latest_firmware
+    exit 0
+ else 
+    echo "No chroot environment found. Starting normal installation"
+fi
+     
+     
+
+
 # check kernel version
 if dpkg --compare-versions 2.6.25 gt `uname -r | cut -d- -f1`; then
 	echo "Kernel too old. This firmware needs >= 2.6.25!."
 	echo "Aborting!"
-	exit 1
+	exit 0
 fi
 
+
+# Fix for BCM4306/3 [14e4:4320] (rev 03)
+chip=`lspci -n | grep -o "14e4:4320 (rev 03)"` || true
+if [ "$chip" ] ; then
+   echo "Your card is BCM4306/3 [14e4:4320] (rev 03), firwmare 5.100.138 will be used"
+   latest_firmware
+   exit 0
+fi 
+
+# Fix for BCM4306/3 [14e4:4324] (rev 03)
+chip=`lspci -n | grep -o "14e4:4324 (rev 03)"` || true
+if [ "$chip" ] ; then
+   echo "Your card is BCM4306/3 [14e4:4324] (rev 03), firwmare 5.100.138 will be used"
+   latest_firmware
+   exit 0
+fi
+   
 # check chip
-pci=`lspci -n | grep -o "14e4:[1234567890]\+"` || true
+pci=`lspci -n | grep -o "14e4:[1234567890abcdef]\+"` || true
+
 if [ -n "$pci" ]; then
-	if [ "`echo $pci | cut -d: -f2`" = "4301" ] && \
-           [ "`echo $pci | cut -d: -f2`" = "4306" ]; then
-		echo "Not supported card here (PCI id $pci)!"
-		echo "Use b43legacy firmware."
-		echo "Aborting."
-		exit 1
-	elif [ "`echo $pci | cut -d: -f2`" = "4315" ]; then
-		echo "Not supported low-power chip with PCI id $pci!"
-		echo "Aborting."
-		exit 1
-	elif [ "`echo $pci | cut -d: -f2`" = "4321" ] && \
-             [ "`echo $pci | cut -d: -f2`" = "4324" ] && \
-             [ "`echo $pci | cut -d: -f2`" = "4325" ] && \
-             [ "`echo $pci | cut -d: -f2`" = "4328" ] && \
-             [ "`echo $pci | cut -d: -f2`" = "4329" ] && \
-             [ "`echo $pci | cut -d: -f2`" = "43b5" ]; then
-		echo "Not supported chip: PCI id $pci!"
-		echo "Aborting!"
-		exit 1
-	fi
+	for device in $pci; do
+		device_id=`echo $device | cut -d: -f2`
+		case $device_id in
+		4301 | 4306 | 4320 |4324 | 4325)
+			legacy=1
+		;;
+		4315)
+			lpphy=1
+		;;
+		4328 | 4329 | 4307 | 4311 | 4312 | 4318 | 4319 | 432b | 4315 | 4321 | 4353 | 4357 | 5354)
+			latest=1
+                ;;	
+		4322 | 4331 | 4727)
+			unsupported="$unsupported $device_id"
+		;;
+		0576 | 4313 | 432a | 432c | 432d | 4358 | 4359 | 435a | a99d)
+                        nottested=1
+                ;;
+		*)
+		;;
+		esac
+	done
 fi
 
-cd $tmp
-export FIRMWARE_INSTALL_DIR="/lib/firmware"
-
-if [ ! -d "$FIRMWARE_INSTALL_DIR" ]; then
-	mkdir -p $FIRMWARE_INSTALL_DIR
+if [ "$legacy" ]; then
+	echo "An unsupported BCM4301, BCM4306 or BCM4306/2 device was found."
+	echo "Use b43legacy firmware (firmware-b43legacy-installer package) instead."
+	echo "Aborting."
+	exit 0
+elif [ "$lpphy" ]; then
+	echo "An unsupported BCM4312 Low-Power (LP-PHY) device was found."
+	echo "Use b43 LP-PHY firmware (firmware-b43-lpphy-installer package) instead."
+	echo "Aborting."
+	exit 0
+elif [ "$unsupported" ]; then
+	echo -n "Unsupported device(s) found: PCI id "
+	for device_id in $unsupported; do echo -n "14e4:$device_id "; done
+	echo
+	echo "Aborting."
+	exit 0
+elif [ "$nottested" ]; then
+        echo "This card is actually not tested. Please install the driver manually."
+        exit 0
+elif [ "$latest" ]; then
+        echo "This card work with newer 5.100.138 firmware. Trying to install it."
+        latest_firmware
+        exit 0
 fi
-
-wget http://mirror2.openwrt.org/sources/broadcom-wl-4.150.10.5.tar.bz2
-tar xjf broadcom-wl-4.150.10.5.tar.bz2
-cd broadcom-wl-4.150.10.5/driver
-b43-fwcutter -w "$FIRMWARE_INSTALL_DIR" wl_apsta_mimo.o
-
 
 
