Big Buster upgrade

diff --git a/sbin/blkdeactivate b/sbin/blkdeactivate
--- a/sbin/blkdeactivate
+++ b/sbin/blkdeactivate
@@ -1,6 +1,6 @@
 #!/bin/bash
 #
-# Copyright (C) 2012-2015 Red Hat, Inc. All rights reserved.
+# Copyright (C) 2012-2017 Red Hat, Inc. All rights reserved.
 #
 # This file is part of LVM2.
 #
@@ -31,17 +31,19 @@ shopt -s dotglob nullglob
 
 TOOL=blkdeactivate
 
-DEV_DIR='/dev'
-SYS_BLK_DIR='/sys/block'
+DEV_DIR="/dev"
+SYS_BLK_DIR="/sys/block"
 
-MOUNTPOINT="/bin/mountpoint"
-UMOUNT="/bin/umount"
-DMSETUP="/sbin/dmsetup"
-LVM="/sbin/lvm"
 MDADM="/sbin/mdadm"
+MOUNTPOINT="/bin/mountpoint"
 MPATHD="/sbin/multipathd"
+UMOUNT="/bin/umount"
 
-if $UMOUNT --help | grep -- "--all-targets" >$DEV_DIR/null; then
+sbindir="/sbin"
+DMSETUP="$sbindir/dmsetup"
+LVM="$sbindir/lvm"
+
+if "$UMOUNT" --help | grep -- "--all-targets" >"$DEV_DIR/null"; then
 	UMOUNT_OPTS="--all-targets "
 else
 	UMOUNT_OPTS=""
@@ -71,6 +73,9 @@ LVM_DO_WHOLE_VG=0
 # Do not retry LV deactivation by default.
 LVM_CONFIG="activation{retry_deactivation=0}"
 
+# Do not wait for MD RAID device resync, recovery or reshape.
+MDRAID_DO_WAIT=0
+
 # Do not disable queueing if set on multipath devices.
 MPATHD_DO_DISABLEQUEUEING=0
 
@@ -94,7 +99,7 @@ declare -A SKIP_VG_LIST=()
 # listed here will be added to SKIP_DEVICE_LIST (and SKIP_VG_LIST) automatically.
 # (list is an associative array!)
 #
-declare -A SKIP_UMOUNT_LIST=(["/"]=1 ["/boot"]=1 \
+declare -A SKIP_UMOUNT_LIST=(["/"]=1 \
                              ["/lib"]=1 ["/lib64"]=1 \
                              ["/bin"]=1 ["/sbin"]=1 \
                              ["/var"]=1 ["/var/log"]=1 \
@@ -113,13 +118,14 @@ usage() {
 	echo "      If devices are specified, deactivate only supplied devices and their holders."
 	echo
 	echo "  Options:"
-	echo "    -e | --errors                    Show errors reported from tools"
-	echo "    -h | --help                      Show this help message"
-	echo "    -d | --dmoption    DM_OPTIONS    Comma separated DM specific options"
-	echo "    -l | --lvmoption   LVM_OPTIONS   Comma separated LVM specific options"
-	echo "    -m | --mpathoption MPATH_OPTIONS Comma separated DM-multipath specific options"
-	echo "    -u | --umount                    Unmount the device if mounted"
-	echo "    -v | --verbose                   Verbose mode (also implies -e)"
+	echo "    -e | --errors                       Show errors reported from tools"
+	echo "    -h | --help                         Show this help message"
+	echo "    -d | --dmoptions     DM_OPTIONS     Comma separated DM specific options"
+	echo "    -l | --lvmoptions    LVM_OPTIONS    Comma separated LVM specific options"
+	echo "    -m | --mpathoptions  MPATH_OPTIONS  Comma separated DM-multipath specific options"
+	echo "    -r | --mdraidoptions MDRAID_OPTIONS Comma separated MD RAID specific options"
+	echo "    -u | --umount                       Unmount the device if mounted"
+	echo "    -v | --verbose                      Verbose mode (also implies -e)"
 	echo
 	echo "  Device specific options:"
 	echo "    DM_OPTIONS:"
@@ -128,6 +134,8 @@ usage() {
 	echo "    LVM_OPTIONS:"
 	echo "      retry           retry removal several times in case of failure"
 	echo "      wholevg         deactivate the whole VG when processing an LV"
+	echo "    MDRAID_OPTIONS:"
+	echo "      wait            wait for resync, recovery or reshape to complete first"
 	echo "    MPATH_OPTIONS:"
 	echo "      disablequeueing disable queueing on all DM-multipath devices first"
 
@@ -147,7 +155,7 @@ add_vg_to_skip_list() {
 is_top_level_device() {
 	# top level devices do not have any holders, that is
 	# the SYS_BLK_DIR/<device_name>/holders dir is empty
-	files="`echo $SYS_BLK_DIR/$kname/holders/*`"
+	files=$(echo "$SYS_BLK_DIR/$kname/holders/"*)
 	test -z "$files"
 }
 
@@ -156,9 +164,9 @@ device_umount_one() {
 
 	if test -z "${SKIP_UMOUNT_LIST["$mnt"]}" -a "$DO_UMOUNT" -eq "1"; then
 		echo -n "  [UMOUNT]: unmounting $name ($kname) mounted on $mnt... "
-		if eval $UMOUNT $UMOUNT_OPTS "$(printf "%s" "$mnt")" $OUT $ERR; then
+		if eval "$UMOUNT" $UMOUNT_OPTS "$(printf "%s" "$mnt")" "$OUT" "$ERR"; then
 			echo "done"
-		elif $MOUNTPOINT -q "$mnt"; then
+		elif "$MOUNTPOINT" -q "$mnt"; then
 			echo "skipping"
 			add_device_to_skip_list
 		else
@@ -171,7 +179,8 @@ device_umount_one() {
 }
 
 device_umount() {
-	test "$devtype" != "lvm" && test "${kname:0:3}" != "dm-" && return 0
+	test "$devtype" != "lvm" && test "${kname:0:3}" != "dm-" \
+          && test "${kname:0:2}" != "md" && return 0
 
 	# FINDMNT is defined only if umount --all-targets is not available.
 	# In that case, read the list of multiple mount points of one device
@@ -181,7 +190,7 @@ device_umount() {
 	else
 		while $FINDMNT_READ; do
 			device_umount_one || return 1
-		done <<< "`$FINDMNT $DEV_DIR/$kname`"
+		done <<< "$($FINDMNT "$DEV_DIR/$kname")"
 	fi
 
 }
@@ -193,25 +202,26 @@ deactivate_holders () {
 	# First line on the lsblk output is the device itself - skip it for
 	# the deactivate call as this device is already being deactivated.
 	while $LSBLK_READ; do
-		test -e $SYS_BLK_DIR/$kname || continue
+		test -e "$SYS_BLK_DIR/$kname" || continue
 		# check if the device not on the skip list already
-		test -z ${SKIP_DEVICE_LIST["$kname"]} || return 1
+		test -z "${SKIP_DEVICE_LIST["$kname"]}" || return 1
 
 		# try to deactivate the holder
-		test $skip -eq 1 && skip=0 && continue
+		test "$skip" -eq 1 && skip=0 && continue
 		deactivate || return 1
-	done <<< "`$LSBLK $1`"
+	done <<< "$($LSBLK "$1")"
 }
 
 deactivate_dm () {
-	local name=$(printf "%s" "$name")
-	test -b "$DEV_DIR/mapper/$name" || return 0
-	test -z ${SKIP_DEVICE_LIST["$kname"]} || return 1
+	local xname
+	xname=$(printf "%s" "$name")
+	test -b "$DEV_DIR/mapper/$xname" || return 0
+	test -z "${SKIP_DEVICE_LIST["$kname"]}" || return 1
 
-	deactivate_holders "$DEV_DIR/mapper/$name" || return 1
+	deactivate_holders "$DEV_DIR/mapper/$xname" || return 1
 
-	echo -n "  [DM]: deactivating $devtype device $name ($kname)... "
-	if eval $DMSETUP $DMSETUP_OPTS remove "$name" $OUT $ERR; then
+	echo -n "  [DM]: deactivating $devtype device $xname ($kname)... "
+	if eval "$DMSETUP" $DMSETUP_OPTS remove "$xname" "$OUT" "$ERR"; then
 		echo "done"
 	else
 		echo "skipping"
@@ -220,15 +230,15 @@ deactivate_dm () {
 }
 
 deactivate_lvm () {
-	local DM_VG_NAME; local DM_LV_NAME; local DM_LV_LAYER
+	local DM_VG_NAME; local DM_LV_NAME
 
-	eval $(eval $DMSETUP splitname --nameprefixes --noheadings --rows "$name" LVM $ERR)
+	eval "$(eval "$DMSETUP" splitname --nameprefixes --noheadings --rows "$name" LVM "$ERR")"
 	test -b "$DEV_DIR/$DM_VG_NAME/$DM_LV_NAME" || return 0
-	test -z ${SKIP_VG_LIST["$DM_VG_NAME"]} || return 1
+	test -z "${SKIP_VG_LIST["$DM_VG_NAME"]}" || return 1
 
-	if test $LVM_DO_WHOLE_VG -eq 0; then
+	if test "$LVM_DO_WHOLE_VG" -eq 0; then
 		# Skip LVM device deactivation if LVM tools missing.
-		test $LVM_AVAILABLE -eq 0 && {
+		test "$LVM_AVAILABLE" -eq 0 && {
 			add_device_to_skip_list
 			return 1
 		}
@@ -239,7 +249,7 @@ deactivate_lvm () {
 		}
 
 		echo -n "  [LVM]: deactivating Logical Volume $DM_VG_NAME/$DM_LV_NAME... "
-		if eval $LVM lvchange $LVM_OPTS --config \'log{prefix=\"\"} $LVM_CONFIG\' -aln $DM_VG_NAME/$DM_LV_NAME $OUT $ERR; then
+		if eval "$LVM" lvchange $LVM_OPTS --config \'log\{prefix=\"\"\} $LVM_CONFIG\' -aln "$DM_VG_NAME/$DM_LV_NAME" "$OUT" "$ERR"; then
 			echo "done"
 		else
 			echo "skipping"
@@ -248,12 +258,12 @@ deactivate_lvm () {
 
 	else
 		# Skip LVM VG deactivation if LVM tools missing.
-		test $LVM_AVAILABLE -eq 0 && {
+		test "$LVM_AVAILABLE" -eq 0 && {
 			add_vg_to_skip_list
 			return 1
 		}
 		# Deactivating the whole VG the LV is part of
-		lv_list=$(eval $LVM vgs --config "$LVM_CONFIG" --noheadings --rows -o lv_name $DM_VG_NAME $ERR)
+		lv_list=$(eval "$LVM" vgs --config "$LVM_CONFIG" --noheadings --rows -o lv_name "$DM_VG_NAME" "$ERR")
 		for lv in $lv_list; do
 			test -b "$DEV_DIR/$DM_VG_NAME/$lv" || continue
 			deactivate_holders "$DEV_DIR/$DM_VG_NAME/$lv" || {
@@ -263,7 +273,7 @@ deactivate_lvm () {
 		done
 
 		echo -n "  [LVM]: deactivating Volume Group $DM_VG_NAME... "
-		if eval $LVM vgchange $LVM_OPTS --config \'log{prefix=\"    \"} $LVM_CONFIG\' -aln $DM_VG_NAME $OUT $ERR; then
+		if eval "$LVM" vgchange $LVM_OPTS --config \'log\{prefix=\"    \"\} $LVM_CONFIG\' -aln "$DM_VG_NAME" "$OUT" "$ERR"; then
 			echo "done"
 		else
 			echo "skipping"
@@ -273,20 +283,35 @@ deactivate_lvm () {
 }
 
 deactivate_md () {
-	local name=$(printf "%s" "$name")
-	test -b "$DEV_DIR/$name" || return 0
-	test -z ${SKIP_DEVICE_LIST["$kname"]} || return 1
+	local xname
+	xname=$(printf "%s" "$name")
+	local sync_action
+	test -b "$DEV_DIR/$xname" || return 0
+	test -z "${SKIP_DEVICE_LIST["$kname"]}" || return 1
 
 	# Skip MD device deactivation if MD tools missing.
-	test $MDADM_AVAILABLE -eq 0 && {
+	test "$MDADM_AVAILABLE" -eq 0 && {
 		add_device_to_skip_list
 		return 1
 	}
 
-	deactivate_holders "$DEV_DIR/$name" || return 1
+	deactivate_holders "$DEV_DIR/$xname" || return 1
 
 	echo -n "  [MD]: deactivating $devtype device $kname... "
-	if eval $MDADM $MDADM_OPTS -S "$name" $OUT $ERR; then
+
+	test "$MDRAID_DO_WAIT" -eq 1 && {
+		sync_action=$(cat "$SYS_BLK_DIR/$kname/md/sync_action")
+		test "$sync_action" != "idle" && {
+			echo -n "$sync_action action in progress... "
+			if eval "$MDADM" $MDADM_OPTS -W "$DEV_DIR/$kname" "$OUT" "$ERR"; then
+				echo -n "complete... "
+			else
+				test $? -ne 1 && echo -n "failed to wait for $sync_action action... "
+			fi
+		}
+	}
+
+	if eval "$MDADM" $MDADM_OPTS -S "$xname" "$OUT" "$ERR"; then
 		echo "done"
 	else
 		echo "skipping"
@@ -323,9 +348,9 @@ deactivate_all() {
 
 	echo "Deactivating block devices:"
 
-	test $MPATHD_RUNNING -eq 1 && {
+	test "$MPATHD_RUNNING" -eq 1 && {
 		echo -n "  [DM]: disabling queueing on all multipath devices... "
-		eval $MPATHD $MPATHD_OPTS disablequeueing maps $ERR | grep '^ok$' >$DEV_DIR/null && echo "done" || echo "failed"
+		eval "$MPATHD" $MPATHD_OPTS disablequeueing maps "$ERR" | grep '^ok$' >"$DEV_DIR/null" && echo "done" || echo "failed"
 	}
 
 	if test $# -eq 0; then
@@ -336,7 +361,7 @@ deactivate_all() {
 		# Unmount all relevant mountpoints first
 		while $LSBLK_READ; do
 			device_umount
-		done <<< "`$LSBLK | $SORT_MNT`"
+		done <<< "$($LSBLK | $SORT_MNT)"
 
 		# Do deactivate
 		while $LSBLK_READ; do
@@ -346,20 +371,24 @@ deactivate_all() {
 			# if deactivation of any device fails, skip processing
 			# any subsequent devices within its subtree as the
 			# top-level device could not be deactivated anyway
-			test $skip -eq 1 && {
+			test "$skip" -eq 1 && {
 				# reset 'skip' on top level device
-				is_top_level_device && skip=0 || continue
+				if is_top_level_device ; then
+					skip=0
+				else
+					continue
+				fi
 			}
 
 			# check if the device is not on the skip list already
-			test -z ${SKIP_DEVICE_LIST["$kname"]} || continue
+			test -z "${SKIP_DEVICE_LIST["$kname"]}" || continue
 
 			# try to deactivate top-level device, set 'skip=1'
 			# if it fails to do so - this will cause all the
 			# device's subtree to be skipped when processing
 			# devices further in this loop
 			deactivate || skip=1
-		done <<< "`$LSBLK -s`"
+		done <<< "$($LSBLK -s)"
 	else
 		##################################
 		# Process only specified devices #
@@ -369,15 +398,15 @@ deactivate_all() {
 			# Unmount all relevant mountpoints first
 			while $LSBLK_READ; do
 				device_umount
-			done <<< "`$LSBLK $1 | $SORT_MNT`"
+			done <<< "$($LSBLK "$1" | $SORT_MNT)"
 
 			# Do deactivate
 			# Single dm device tree deactivation.
 			if test -b "$1"; then
-				$LSBLK_READ <<< "`$LSBLK --nodeps $1`"
+				$LSBLK_READ <<< "$($LSBLK --nodeps "$1")"
 
 				# check if the device is not on the skip list already
-				test -z ${SKIP_DEVICE_LIST["$kname"]} || {
+				test -z "${SKIP_DEVICE_LIST["$kname"]}" || {
 					shift
 					continue
 				}
@@ -422,6 +451,20 @@ get_lvmopts() {
 	IFS=$ORIG_IFS
 }
 
+get_mdraidopts() {
+	ORIG_IFS=$IFS; IFS=','
+
+	for opt in $1; do
+		case "$opt" in
+			"") ;;
+			"wait") MDRAID_DO_WAIT=1 ;;
+			*) echo "$opt: unknown MD RAID option"
+		esac
+	done
+
+	IFS=$ORIG_IFS
+}
+
 get_mpathopts() {
 	ORIG_IFS=$IFS; IFS=','
 
@@ -454,7 +497,7 @@ set_env() {
 		OUT="1>$DEV_DIR/null"
 	fi
 
-	if test -f $LVM; then
+	if test -f "$LVM"; then
 		LVM_AVAILABLE=1
 	else
 		LVM_AVAILABLE=0
@@ -467,9 +510,9 @@ set_env() {
 	fi
 
 	MPATHD_RUNNING=0
-	test $MPATHD_DO_DISABLEQUEUEING -eq 1 && {
-		if test -f $MPATHD; then
-			if eval $MPATHD show daemon $ERR | grep "running" >$DEV_DIR/null; then
+	test "$MPATHD_DO_DISABLEQUEUEING" -eq 1 && {
+		if test -f "$MPATHD"; then
+			if eval "$MPATHD" show daemon "$ERR" | grep "running" >"$DEV_DIR/null"; then
 				MPATHD_RUNNING=1
 			fi
 		fi
@@ -481,9 +524,10 @@ while test $# -ne 0; do
 		"") ;;
 		"-e"|"--errors") ERRORS=1 ;;
 		"-h"|"--help") usage ;;
-		"-d"|"--dmoption ") get_dmopts "$2" ; shift ;;
-		"-l"|"--lvmoption ") get_lvmopts "$2" ; shift ;;
-		"-m"|"--mpathoption ") get_mpathopts "$2" ; shift ;;
+		"-d"|"--dmoptions") get_dmopts "$2" ; shift ;;
+		"-l"|"--lvmoptions") get_lvmopts "$2" ; shift ;;
+		"-m"|"--mpathoptions") get_mpathopts "$2" ; shift ;;
+		"-r"|"--mdraidoptions") get_mdraidopts "$2"; shift ;;
 		"-u"|"--umount") DO_UMOUNT=1 ;;
 		"-v"|"--verbose") VERBOSE=1 ; ERRORS=1 ;;
 		"-vv") VERBOSE=1 ; ERRORS=1 ; set -x ;;
diff --git a/usr/bin/apt-key b/usr/bin/apt-key
--- a/usr/bin/apt-key
+++ b/usr/bin/apt-key
@@ -15,6 +15,74 @@ eval "$(apt-config shell ARCHIVE_KEYRING_URI APT::Key::ArchiveKeyringURI)"
 
 aptkey_echo() { echo "$@"; }
 
+find_gpgv_status_fd() {
+   while [ -n "$1" ]; do
+	if [ "$1" = '--status-fd' ]; then
+		shift
+		echo "$1"
+		break
+	fi
+	shift
+   done
+}
+GPGSTATUSFD="$(find_gpgv_status_fd "$@")"
+
+apt_warn() {
+    if [ -z "$GPGHOMEDIR" ]; then
+	echo >&2 'W:' "$@"
+    else
+	echo 'W:' "$@" > "${GPGHOMEDIR}/aptwarnings.log"
+    fi
+    if [ -n "$GPGSTATUSFD" ]; then
+	echo >&${GPGSTATUSFD} '[APTKEY:] WARNING' "$@"
+    fi
+}
+apt_error() {
+    if [ -z "$GPGHOMEDIR" ]; then
+	echo >&2 'E:' "$@"
+    else
+	echo 'E:' "$@" > "${GPGHOMEDIR}/aptwarnings.log"
+    fi
+    if [ -n "$GPGSTATUSFD" ]; then
+	echo >&${GPGSTATUSFD} '[APTKEY:] ERROR' "$@"
+    fi
+}
+
+cleanup_gpg_home() {
+    if [ -z "$GPGHOMEDIR" ]; then return; fi
+    if [ -s "$GPGHOMEDIR/aptwarnings.log" ]; then
+	cat >&2 "$GPGHOMEDIR/aptwarnings.log"
+    fi
+    if command_available 'gpgconf'; then
+	GNUPGHOME="${GPGHOMEDIR}" gpgconf --kill all >/dev/null 2>&1 || true
+    fi
+    rm -rf "$GPGHOMEDIR"
+}
+
+# gpg needs (in different versions more or less) files to function correctly,
+# so we give it its own homedir and generate some valid content for it later on
+create_gpg_home() {
+    # for cases in which we want to cache a homedir due to expensive setup
+    if [ -n "$GPGHOMEDIR" ]; then
+	return
+    fi
+    if [ -n "$TMPDIR" ]; then
+	# tmpdir is a directory and current user has rwx access to it
+	# same tests as in apt-pkg/contrib/fileutl.cc GetTempDir()
+	if [ ! -d "$TMPDIR" ] || [ ! -r "$TMPDIR" ] || [ ! -w "$TMPDIR" ] || [ ! -x "$TMPDIR" ]; then
+	    unset TMPDIR
+	fi
+    fi
+    GPGHOMEDIR="$(mktemp --directory --tmpdir 'apt-key-gpghome.XXXXXXXXXX')"
+    CURRENTTRAP="${CURRENTTRAP} cleanup_gpg_home;"
+    trap "${CURRENTTRAP}" 0 HUP INT QUIT ILL ABRT FPE SEGV PIPE TERM
+    if [ -z "$GPGHOMEDIR" ]; then
+	apt_error "Could not create temporary gpg home directory in $TMPDIR (wrong permissions?)"
+	exit 28
+    fi
+    chmod 700 "$GPGHOMEDIR"
+}
+
 requires_root() {
 	if [ "$(id -u)" -ne 0 ]; then
 		apt_error "This command can only be used by root."
@@ -131,7 +199,7 @@ net_update() {
 	exit 1
     fi
     # in theory we would need to depend on wget for this, but this feature
-    # isn't useable in debian anyway as we have no keyring uri nor a master key
+    # isn't usable in debian anyway as we have no keyring uri nor a master key
     if ! command_available 'wget'; then
 	apt_error 'wget is required for a network-based update, but it is not installed'
 	exit 1
@@ -249,15 +317,43 @@ accessible_file_exists() {
    return 1
 }
 
+is_supported_keyring() {
+    # empty files are always supported
+    if ! test -s "$1"; then
+	return 0
+    fi
+    local FILEEXT="${1##*.}"
+    if [ "$FILEEXT" = 'gpg' ]; then
+	# 0x98, 0x99 and 0xC6 via octal as hex isn't supported by dashs printf
+	if printf '\231' | cmp --silent --bytes=1 - "$1"; then
+	    true
+	elif printf '\230' | cmp --silent --bytes=1 - "$1"; then
+	    true
+	elif printf '\306' | cmp --silent --bytes=1 - "$1"; then
+	    true
+	else
+	    apt_warn "The key(s) in the keyring $1 are ignored as the file has an unsupported filetype."
+	    return 1
+	fi
+    elif [ "$FILEEXT" = 'asc' ]; then
+	true #dearmor_filename will deal with them
+    else
+	# most callers ignore unsupported extensions silently
+	apt_warn "The key(s) in the keyring $1 are ignored as the file has an unsupported filename extension."
+	return 1
+    fi
+    return 0
+}
+
 foreach_keyring_do() {
    local ACTION="$1"
    shift
    # if a --keyring was given, just work on this one
    if [ -n "$FORCED_KEYRING" ]; then
-	$ACTION "$TRUSTEDFILE" "$@"
+	$ACTION "$FORCED_KEYRING" "$@"
    else
 	# otherwise all known keyrings are up for inspection
-	if accessible_file_exists "$TRUSTEDFILE"; then
+	if accessible_file_exists "$TRUSTEDFILE" && is_supported_keyring "$TRUSTEDFILE"; then
 	    $ACTION "$TRUSTEDFILE" "$@"
 	fi
 	local TRUSTEDPARTS="/etc/apt/trusted.gpg.d"
@@ -266,7 +362,7 @@ foreach_keyring_do() {
 	    TRUSTEDPARTS="$(readlink -f "$TRUSTEDPARTS")"
 	    local TRUSTEDPARTSLIST="$(cd /; find "$TRUSTEDPARTS" -mindepth 1 -maxdepth 1 \( -name '*.gpg' -o -name '*.asc' \))"
 	    for trusted in $(echo "$TRUSTEDPARTSLIST" | sort); do
-		if accessible_file_exists "$trusted"; then
+		if accessible_file_exists "$trusted" && is_supported_keyring "$trusted"; then
 		    $ACTION "$trusted" "$@"
 		fi
 	    done
@@ -497,11 +593,26 @@ while [ -n "$1" ]; do
    case "$1" in
       --keyring)
 	 shift
-	 TRUSTEDFILE="$1"
-	 FORCED_KEYRING="$1"
+	 if [ -z "$FORCED_KEYRING" -o "$FORCED_KEYRING" = '/dev/null' ]; then
+	     TRUSTEDFILE="$1"
+	     FORCED_KEYRING="$1"
+	 elif [ "$TRUSTEDFILE" = "$FORCED_KEYRING" ]; then
+	     create_gpg_home
+	     FORCED_KEYRING="${GPGHOMEDIR}/mergedkeyrings.gpg"
+	     echo -n '' > "$FORCED_KEYRING"
+	     chmod 0644 -- "$FORCED_KEYRING"
+	     catfile "$TRUSTEDFILE" "$FORCED_KEYRING"
+	     catfile "$1" "$FORCED_KEYRING"
+	 else
+	     catfile "$1" "$FORCED_KEYRING"
+	 fi
 	 ;;
       --keyid)
 	 shift
+	 if [ -n "$FORCED_KEYID" ]; then
+	     apt_error 'Specifying --keyid multiple times is not supported'
+	     exit 1
+	 fi
 	 FORCED_KEYID="$1"
 	 ;;
       --secret-keyring)
@@ -553,74 +664,6 @@ if [ -z "$command" ]; then
     exit 1
 fi
 shift
-
-find_gpgv_status_fd() {
-   while [ -n "$1" ]; do
-	if [ "$1" = '--status-fd' ]; then
-		shift
-		echo "$1"
-		break
-	fi
-	shift
-   done
-}
-GPGSTATUSFD="$(find_gpgv_status_fd "$@")"
-
-apt_warn() {
-    if [ -z "$GPGHOMEDIR" ]; then
-	echo >&2 'W:' "$@"
-    else
-	echo 'W:' "$@" > "${GPGHOMEDIR}/aptwarnings.log"
-    fi
-    if [ -n "$GPGSTATUSFD" ]; then
-	echo >&${GPGSTATUSFD} '[APTKEY:] WARNING' "$@"
-    fi
-}
-apt_error() {
-    if [ -z "$GPGHOMEDIR" ]; then
-	echo >&2 'E:' "$@"
-    else
-	echo 'E:' "$@" > "${GPGHOMEDIR}/aptwarnings.log"
-    fi
-    if [ -n "$GPGSTATUSFD" ]; then
-	echo >&${GPGSTATUSFD} '[APTKEY:] ERROR' "$@"
-    fi
-}
-
-cleanup_gpg_home() {
-    if [ -z "$GPGHOMEDIR" ]; then return; fi
-    if [ -s "$GPGHOMEDIR/aptwarnings.log" ]; then
-	cat >&2 "$GPGHOMEDIR/aptwarnings.log"
-    fi
-    if command_available 'gpgconf'; then
-	GNUPGHOME="${GPGHOMEDIR}" gpgconf --kill gpg-agent >/dev/null 2>&1 || true
-    fi
-    rm -rf "$GPGHOMEDIR"
-}
-
-# gpg needs (in different versions more or less) files to function correctly,
-# so we give it its own homedir and generate some valid content for it later on
-create_gpg_home() {
-    # for cases in which we want to cache a homedir due to expensive setup
-    if [ -n "$GPGHOMEDIR" ]; then
-	return
-    fi
-    if [ -n "$TMPDIR" ]; then
-	# tmpdir is a directory and current user has rwx access to it
-	# same tests as in apt-pkg/contrib/fileutl.cc GetTempDir()
-	if [ ! -d "$TMPDIR" ] || [ ! -r "$TMPDIR" ] || [ ! -w "$TMPDIR" ] || [ ! -x "$TMPDIR" ]; then
-	    unset TMPDIR
-	fi
-    fi
-    GPGHOMEDIR="$(mktemp --directory --tmpdir 'apt-key-gpghome.XXXXXXXXXX')"
-    CURRENTTRAP="${CURRENTTRAP} cleanup_gpg_home;"
-    trap "${CURRENTTRAP}" 0 HUP INT QUIT ILL ABRT FPE SEGV PIPE TERM
-    if [ -z "$GPGHOMEDIR" ]; then
-	apt_error "Could not create temporary gpg home directory in $TMPDIR (wrong permissions?)"
-	exit 28
-    fi
-    chmod 700 "$GPGHOMEDIR"
-}
 
 prepare_gpg_home() {
     # crude detection if we are called from a maintainerscript where the
diff --git a/usr/bin/dpkg-maintscript-helper b/usr/bin/dpkg-maintscript-helper
--- a/usr/bin/dpkg-maintscript-helper
+++ b/usr/bin/dpkg-maintscript-helper
@@ -46,6 +46,8 @@ rm_conffile() {
 	[ -n "$1" ] || error "maintainer script parameters are missing"
 	[ -n "$DPKG_MAINTSCRIPT_NAME" ] || \
 		error "environment variable DPKG_MAINTSCRIPT_NAME is required"
+	[ -n "$DPKG_MAINTSCRIPT_PACKAGE" ] || \
+		error "environment variable DPKG_MAINTSCRIPT_PACKAGE is required"
 	[ "${CONFFILE}" != "${CONFFILE#/}" ] || \
 		error "conffile '$CONFFILE' is not an absolute path"
 	validate_optional_version "$LASTVERSION"
@@ -94,7 +96,7 @@ prepare_rm_conffile() {
 	local md5sum old_md5sum
 	md5sum="$(md5sum "$CONFFILE" | sed -e 's/ .*//')"
 	old_md5sum="$(dpkg-query -W -f='${Conffiles}' "$PACKAGE" | \
-		sed -n -e "\'^ $CONFFILE ' { s/ obsolete$//; s/.* //; p }")"
+		sed -n -e "\\'^ $CONFFILE ' { s/ obsolete$//; s/.* //; p }")"
 	if [ "$md5sum" != "$old_md5sum" ]; then
 		mv -f "$CONFFILE" "$CONFFILE.dpkg-backup"
 	else
@@ -156,6 +158,8 @@ mv_conffile() {
 	[ -n "$1" ] || error "maintainer script parameters are missing"
 	[ -n "$DPKG_MAINTSCRIPT_NAME" ] || \
 		error "environment variable DPKG_MAINTSCRIPT_NAME is required"
+	[ -n "$DPKG_MAINTSCRIPT_PACKAGE" ] || \
+		error "environment variable DPKG_MAINTSCRIPT_PACKAGE is required"
 	[ "${OLDCONFFILE}" != "${OLDCONFFILE#/}" ] || \
 		error "old-conffile '$OLDCONFFILE' is not an absolute path"
 	[ "${NEWCONFFILE}" != "${NEWCONFFILE#/}" ] || \
@@ -203,7 +207,7 @@ prepare_mv_conffile() {
 	local md5sum old_md5sum
 	md5sum="$(md5sum "$CONFFILE" | sed -e 's/ .*//')"
 	old_md5sum="$(dpkg-query -W -f='${Conffiles}' "$PACKAGE" | \
-		sed -n -e "\'^ $CONFFILE ' { s/ obsolete$//; s/.* //; p }")"
+		sed -n -e "\\'^ $CONFFILE ' { s/ obsolete$//; s/.* //; p }")"
 	if [ "$md5sum" = "$old_md5sum" ]; then
 		mv -f "$CONFFILE" "$CONFFILE.dpkg-remove"
 	fi
@@ -262,6 +266,8 @@ symlink_to_dir() {
 
 	[ -n "$DPKG_MAINTSCRIPT_NAME" ] || \
 		error "environment variable DPKG_MAINTSCRIPT_NAME is required"
+	[ -n "$DPKG_MAINTSCRIPT_PACKAGE" ] || \
+		error "environment variable DPKG_MAINTSCRIPT_PACKAGE is required"
 	[ -n "$PACKAGE" ] || error "cannot identify the package"
 	[ -n "$SYMLINK" ] || error "symlink parameter is missing"
 	[ "${SYMLINK#/}" = "$SYMLINK" ] && \
@@ -340,6 +346,8 @@ dir_to_symlink() {
 
 	[ -n "$DPKG_MAINTSCRIPT_NAME" ] || \
 		error "environment variable DPKG_MAINTSCRIPT_NAME is required"
+	[ -n "$DPKG_MAINTSCRIPT_PACKAGE" ] || \
+		error "environment variable DPKG_MAINTSCRIPT_PACKAGE is required"
 	[ -n "$PACKAGE" ] || error "cannot identify the package"
 	[ -n "$PATHNAME" ] || error "directory parameter is missing"
 	[ "${PATHNAME#/}" = "$PATHNAME" ] && \
@@ -416,7 +424,7 @@ prepare_dir_to_symlink()
 	# we should not perform the switch.
 	export DPKG_MAINTSCRIPT_HELPER_INTERNAL_API="$version"
 	find "$PATHNAME" -print0 | \
-		xargs -0 -n1 $0 _internal_pkg_must_own_file "$PACKAGE" || \
+		xargs -0 -n1 "$0" _internal_pkg_must_own_file "$PACKAGE" || \
 		error "directory '$PATHNAME' contains files not owned by" \
 		      "package $PACKAGE, cannot switch to symlink"
 	unset DPKG_MAINTSCRIPT_HELPER_INTERNAL_API
@@ -457,7 +465,7 @@ finish_dir_to_symlink()
 		ABS_SYMLINK_TARGET="$SYMLINK_TARGET"
 	fi
 	rm "$PATHNAME/.dpkg-staging-dir"
-	find "$PATHNAME" -mindepth 1 -print0 | \
+	find "$PATHNAME" -mindepth 1 -maxdepth 1 -print0 | \
 		xargs -0 -i% mv -f "%" "$ABS_SYMLINK_TARGET/"
 
 	# Remove the staging directory.
@@ -537,19 +545,72 @@ symlink_match()
 	[ "$(readlink -f "$SYMLINK")" = "$SYMLINK_TARGET" ]
 }
 
+# Standard ANSI colors and attributes.
+COLOR_NORMAL=''
+COLOR_RESET='[0m'
+COLOR_BOLD='[1m'
+COLOR_BLACK='[30m'
+COLOR_RED='[31m'
+COLOR_GREEN='[32m'
+COLOR_YELLOW='[33m'
+COLOR_BLUE='[34m'
+COLOR_MAGENTA='[35m'
+COLOR_CYAN='[36m'
+COLOR_WHITE='[37m'
+COLOR_BOLD_BLACK='[1;30m'
+COLOR_BOLD_RED='[1;31m'
+COLOR_BOLD_GREEN='[1;32m'
+COLOR_BOLD_YELLOW='[1;33m'
+COLOR_BOLD_BLUE='[1;34m'
+COLOR_BOLD_MAGENTA='[1;35m'
+COLOR_BOLD_CYAN='[1;36m'
+COLOR_BOLD_WHITE='[1;37m'
+
+setup_colors()
+{
+	: "${DPKG_COLORS=auto}"
+
+	case "$DPKG_COLORS" in
+	auto)
+		if [ -t 1 ]; then
+			USE_COLORS=yes
+		else
+			USE_COLORS=no
+		fi
+		;;
+	always)
+		USE_COLORS=yes
+		;;
+	*)
+		USE_COLORS=no
+		;;
+	esac
+
+	if [ $USE_COLORS = yes ]; then
+		COLOR_PROG="$COLOR_BOLD"
+		COLOR_INFO="$COLOR_GREEN"
+		COLOR_NOTICE="$COLOR_YELLOW"
+		COLOR_WARN="$COLOR_BOLD_YELLOW"
+		COLOR_ERROR="$COLOR_BOLD_RED"
+	else
+		COLOR_RESET=""
+	fi
+	FMT_PROG="$COLOR_PROG$PROGNAME$COLOR_RESET"
+}
+
 debug() {
 	if [ -n "$DPKG_DEBUG" ]; then
-		echo "DEBUG: $PROGNAME: $*" >&2
+		echo "DEBUG: $FMT_PROG: $*" >&2
 	fi
 }
 
 error() {
-	echo "$PROGNAME: error: $*" >&2
+	echo "$FMT_PROG: ${COLOR_ERROR}error${COLOR_RESET}: $*" >&2
 	exit 1
 }
 
 warning() {
-	echo "$PROGNAME: warning: $*" >&2
+	echo "$FMT_PROG: ${COLOR_WARN}warning${COLOR_RESET}: $*" >&2
 }
 
 usage() {
@@ -576,7 +637,7 @@ END
 }
 
 badusage() {
-	echo "$PROGNAME: error: $1" >&2
+	echo "$FMT_PROG: ${COLOR_ERROR}error${COLOR_RESET}: $1" >&2
 	echo >&2
 	echo "Use '$PROGNAME help' for program usage information." >&2
 	exit 1
@@ -586,7 +647,10 @@ badusage() {
 set -e
 
 PROGNAME=$(basename "$0")
-version="1.18.25"
+version="1.19.7"
+
+setup_colors
+
 command="$1"
 [ $# -gt 0 ] || badusage "missing command"
 shift
diff --git a/usr/lib/cups/filter/imagetobrf b/usr/lib/cups/filter/imagetobrf
--- a/usr/lib/cups/filter/imagetobrf
+++ b/usr/lib/cups/filter/imagetobrf
@@ -1,7 +1,7 @@
 #!/bin/bash
 
 #
-# Copyright (c) 2015-2016 Samuel Thibault <samuel.thibault@ens-lyon.org>
+# Copyright (c) 2015-2018 Samuel Thibault <samuel.thibault@ens-lyon.org>
 # 
 # Permission is hereby granted, free of charge, to any person obtaining a copy
 # of this software and associated documentation files (the "Software"), to deal
@@ -46,8 +46,8 @@ checkTool convert imagemagick "embossing images"
 
 NEGATE=$(getOption Negate)
 case "$NEGATE" in
-  True)  NEGATE=-negate ;;
-  False) NEGATE= ;;
+  True|true)  NEGATE=-negate ;;
+  False|false) NEGATE= ;;
   *)
     printf "ERROR: Option Negate must either True or False, got '%s'\n" "$NEGATE" >&2
     exit 1
@@ -56,9 +56,38 @@ esac
 
 ROTATE=$(getOption Rotate)
 case "$ROTATE" in
-  0|90|90\>|90\<|270|270\>|270\<|180) ;;
+  90\>|270\>)
+    if [ "$GRAPHICWIDTH" -gt "$GRAPHICHEIGHT" ]
+    then
+      # Landscape paper, rotate to landscape instead of to portrait
+      ROTATE=${ROTATE/\>/\<}
+    fi
+    ;;
+  0|90|270|180) ;;
   *)
     printf "ERROR: Option Rotate must be a valid rotation value, got '%s'\n" "$ROTATE" >&2
+    exit 1
+    ;;
+esac
+
+MIRROR=$(getOption mirror)
+case "$MIRROR" in
+  True|true)   MIRROR="-flop" ;;
+  False|false) MIRROR="" ;;
+  *)
+    printf "ERROR: Option mirror must either True or False, got '%s'\n" "$MIRROR" >&2
+    exit 1
+    ;;
+esac
+
+PAGE="-page ${TOTALGRAPHICWIDTH}x${TOTALGRAPHICHEIGHT}+${GRAPHICHOFFSET}+${GRAPHICVOFFSET}"
+
+RESIZE=$(getOption fitplot)
+case "$RESIZE" in
+  True|true) RESIZE="-size ${GRAPHICWIDTH}x${GRAPHICHEIGHT} -resize ${GRAPHICWIDTH}x${GRAPHICHEIGHT}" ;;
+  False|false) RESIZE="-crop ${GRAPHICWIDTH}x${GRAPHICHEIGHT}+${GRAPHICHOFFSET}+${GRAPHICVOFFSET}" ;;
+  *)
+    printf "ERROR: Option fitplot must either True or False, got '%s'\n" "$RESIZE" >&2
     exit 1
     ;;
 esac
@@ -81,16 +110,16 @@ case $EDGE in
     ;;
 esac
 
-RENDER_CALL="convert $WORK -rotate $ROTATE -size ${GRAPHICWIDTH}x${GRAPHICHEIGHT} -resize ${GRAPHICWIDTH}x${GRAPHICHEIGHT} - $OUTPUT_FORMAT:-"
+RENDER_CALL="convert $WORK -rotate $ROTATE $PAGE $RESIZE $MIRROR -flatten - $OUTPUT_FORMAT:-"
 
 # Now proceeed
 echo "INFO: Converting image" 1>&2
 if [ -z "$FILE" ]
 then
-  printf "DEBUG: Calling $RENDER_CALL from stdin\n" 1>&2
-  $RENDER_CALL | sed -e '/^Width: [0-9]*$/,/^$/d' 
+  printf "DEBUG: Calling %s from stdin\n" "$RENDER_CALL" 1>&2
+  $RENDER_CALL | sed -e '/^\(Width\|X\|Y\): [0-9]*$/,/^$/d' | addmargins
 else
-  printf "DEBUG: Calling $RENDER_CALL on '%s'\n" "$FILE" 1>&2
-  $RENDER_CALL < "$FILE" | sed -e '/^Width: [0-9]*$/,/^$/d' 
+  printf "DEBUG: Calling %s on '%s'\n" "$RENDER_CALL" "$FILE" 1>&2
+  $RENDER_CALL < "$FILE" | sed -e '/^\(Width\|X\|Y\): [0-9]*$/,/^$/d' | addmargins
 fi
 echo "INFO: Ready" >&2
diff --git a/usr/lib/cups/filter/textbrftoindexv3 b/usr/lib/cups/filter/textbrftoindexv3
--- a/usr/lib/cups/filter/textbrftoindexv3
+++ b/usr/lib/cups/filter/textbrftoindexv3
@@ -1,7 +1,7 @@
 #!/bin/bash
 
 #
-# Copyright (c) 2015-2016 Samuel Thibault <samuel.thibault@ens-lyon.org>
+# Copyright (c) 2015-2018 Samuel Thibault <samuel.thibault@ens-lyon.org>
 # 
 # Permission is hereby granted, free of charge, to any person obtaining a copy
 # of this software and associated documentation files (the "Software"), to deal
@@ -57,10 +57,38 @@ then
   else
     cat "$FILE"
   fi | (
-    while read LINE
+    IFS=$'\n' read -r LINE
+    EOF=$?
+    while [ "$EOF" = 0 -o -n "$LINE" ]
     do
       # Strip CRs
       LINE=${LINE//$'\015'}
+      # Ignore SUBs
+      LINE=${LINE//$'\032'}
+      # Turn non-breakable spaces into spaces
+      LINE=${LINE//$'\302'$'\240'/ }
+      LINE=${LINE//$'\240'/ }
+
+      # Interpret FFs
+      while [ -n "$LINE" -a -z "${LINE/#$'\014'*}" ]
+      do
+        printf "\\f"
+	LINE=${LINE#$'\014'}
+      done
+
+      # Make sure there is nothing else we don't process
+      if [ -n "$LINE" ]
+      then
+	if [ -z "${LINE/*[$'\000'-$'\037'$'\177']*}" ]
+	then
+	  echo "ERROR: unsupported control character in BRF file" >&2
+	fi
+	if [ -z "${LINE/*[$'\200'-$'\377']*}" ]
+	then
+	  echo "ERROR: unsupported non-ASCII character in BRF file" >&2
+	fi
+      fi
+
       CHARS=$(printf %s "$LINE" | wc -c)
       if [ "$CHARS" -gt 127 ]
       then
@@ -74,12 +102,32 @@ then
       then
 	# Enter transparent mode for $CHARS characters
 	printf "\\033\\\\\\x$(printf %02x $CHARS)\\x00"
-	# Echo those $CHARS characters
-	printf %s "$LINE" | tr " !\"#$%&'()*+,-./0123456789:;<=>?@ABCDEFGHIJKLMNOPQRSTUVWXYZ[\\\\]^_{}|~\`abcdefghijklmnopqrstuvwxyz" "\\0V tSQW"$'\004'"gvAT@DP"$'\024'"d"$'\002\006'"\"bB&fF\$a\`Cw4q"$'\020\001\003\021'"1!"$'\023'"3#"$'\022'"2"$'\005\007\025'"5%"$'\027'"7'"$'\026'"6EGrUueRcs0pRsc0"$'\020\001\003\021'"1!"$'\023'"3#"$'\022'"2"$'\005\007\025'"5%"$'\027'"7'"$'\026'"6EGrUue"
+	# Echo those $CHARS characters.
+	# First normalize BRF characters (`a-z{|}~ are non-standard).
+	# Drop unicode patterns with dots 7 or 8 in case the liblouis table happened to erroneously emit one
+	# Drop remaining erroneous multibyte characters
+	# Drop remaining erroneous 1-byte characters
+	# Then turn it into Index 6dots sequences.
+	printf %s "$LINE" | \
+	  tr "\`a-z{|}~" "@A-Z\\[\\\\]_" | \
+	  sed -e 's/[⡀⡁⡂⡃⡄⡅⡆⡇⡈⡉⡊⡋⡌⡍⡎⡏⡐⡑⡒⡓⡔⡕⡖⡗⡘⡙⡚⡛⡜⡝⡞⡟⡠⡡⡢⡣⡤⡥⡦⡧⡨⡩⡪⡫⡬⡭⡮⡯⡰⡱⡲⡳⡴⡵⡶⡷⡸⡹⡺⡻⡼⡽⡾⡿⢀⢁⢂⢃⢄⢅⢆⢇⢈⢉⢊⢋⢌⢍⢎⢏⢐⢑⢒⢓⢔⢕⢖⢗⢘⢙⢚⢛⢜⢝⢞⢟⢠⢡⢢⢣⢤⢥⢦⢧⢨⢩⢪⢫⢬⢭⢮⢯⢰⢱⢲⢳⢴⢵⢶⢷⢸⢹⢺⢻⢼⢽⢾⢿⣀⣁⣂⣃⣄⣅⣆⣇⣈⣉⣊⣋⣌⣍⣎⣏⣐⣑⣒⣓⣔⣕⣖⣗⣘⣙⣚⣛⣜⣝⣞⣟⣠⣡⣢⣣⣤⣥⣦⣧⣨⣩⣪⣫⣬⣭⣮⣯⣰⣱⣲⣳⣴⣵⣶⣷⣸⣹⣺⣻⣼⣽⣾⣿]/ /g' | \
+	  sed -e "s/[^] \!\"#$%&'()*+,.\\/0123456789:;<=>?@ABCDEFGHIJKLMNOPQRSTUVWXYZ\\\\^_[-]/ /g" | \
+	  tr "\000-\037\177\200-\377" " " | \
+	  tr " \!\"#$%&'()*+,-./0123456789:;<=>?@ABCDEFGHIJKLMNOPQRSTUVWXYZ\\[\\\\\\]^_" "\\0V tSQW"$'\004'"gvAT@DP"$'\024'"d"$'\002\006'"\"bB&fF\$a\`Cw4q"$'\020\001\003\021'"1!"$'\023'"3#"$'\022'"2"$'\005\007\025'"5%"$'\027'"7'"$'\026'"6EGrUueRcs0p"
       fi
-      printf "\\r\\n"
+      if [ "$EOF" = 0 ]
+      then
+	printf "\\r\\n"
+      fi
+      IFS=$'\n' read -r LINE
+      EOF=$?
     done
   )
+  if [ $? != 0 ]
+  then
+    printf '\032'
+    exit 1
+  fi
 else
   # not software-translated, send to printer as such
   echo "INFO: Writing text to Index embosser" >&2
diff --git a/usr/lib/cups/filter/texttobrf b/usr/lib/cups/filter/texttobrf
--- a/usr/lib/cups/filter/texttobrf
+++ b/usr/lib/cups/filter/texttobrf
@@ -1,7 +1,7 @@
 #!/bin/bash
 
 #
-# Copyright (c) 2015-2016 Samuel Thibault <samuel.thibault@ens-lyon.org>
+# Copyright (c) 2015-2018 Samuel Thibault <samuel.thibault@ens-lyon.org>
 # 
 # Permission is hereby granted, free of charge, to any person obtaining a copy
 # of this software and associated documentation files (the "Software"), to deal
@@ -40,17 +40,6 @@ FILE=$6
 # Liblouis options #
 ####################
 LIBLOUIS_CONFIG=""
-
-#  number of cells per line
-LIBLOUIS_CONFIG+=" -CcellsPerLine=$TEXTWIDTH -ClinesPerPage=$TEXTHEIGHT -CbraillePages=yes"
-
-#  input encoding
-if [ "$CHARSET" = utf-8 ]
-then
-  LIBLOUIS_CONFIG+=" -CinputTextEncoding=UTF8"
-else
-  LIBLOUIS_CONFIG+=" -CinputTextEncoding=ascii8"
-fi
 
 echo "DEBUG: Input content type: $CONTENT_TYPE" >&2
 
@@ -93,6 +82,22 @@ setupTextRendering() {
   esac
 }
 
+# sometimes we can't filter directly from stdin or the original file because the
+# tools need to seek within the file (e.g. unzip), or spaces in the path pose
+# problem. This can be called in such case to dump the original content to a
+# fresh file
+dumptofile() {
+  ORIGFILE="$FILE"
+  FILE=$(mktemp "${TMPDIR:-/tmp}/texttobrf.tmp.XXXXXX")
+  trap -- 'rm -f "$FILE"' EXIT
+  if [ -n "$ORIGFILE" ]
+  then
+    cat "$ORIGFILE" > "$FILE"
+  else
+    cat > "$FILE"
+  fi
+}
+
 #  Selected braille table
 if [ -n "$LIBLOUIS_TABLES" ]
 then
@@ -108,7 +113,7 @@ then
 	LIBLOUIS_TOOL="file2brl -t"
 	CONVERT=""
 	;;
-      text/xml|application/xml|application/xhtml+xml)
+      text/xml|application/xml|application/xhtml+xml|application/sgml)
 	LIBLOUIS_TOOL="file2brl"
 	CONVERT=""
 	;;
@@ -117,10 +122,19 @@ then
 	CONVERT="antiword -x db -"
 	checkTool antiword antiword "translating MS-Word doc files"
 	;;
-      application/vnd.openxmlformats-officedocument.wordprocessingml.document)
+      application/vnd.oasis.opendocument*)
 	LIBLOUIS_TOOL="file2brl"
-	CONVERT="docx2txt"
-	checkTool docx2txt docx2txt "translating MS-Word docx files"
+	dumptofile
+	CONVERT="unzip -p $FILE content.xml"
+	CHARSET=utf-8
+	checkTool unzip unzip "translating LibreOffice/OpenOffice OpenDocument files"
+	;;
+      application/vnd.openxmlformats-officedocument*)
+	LIBLOUIS_TOOL="file2brl"
+	dumptofile
+	CONVERT="unzip -p $FILE word/document.xml"
+	CHARSET=utf-8
+	checkTool unzip unzip "translating MS-Word docx files"
 	;;
       text/rtf|application/rtf)
 	LIBLOUIS_TOOL="file2brl"
@@ -130,6 +144,7 @@ then
       application/pdf|application/vnd.cups-pdf-banner)
 	LIBLOUIS_TOOL="file2brl -p"
 	CONVERT="pdftotext -raw - -"
+	CHARSET=utf-8
 	checkTool pdftotext poppler "translating PDF files"
 	;;
       *)
@@ -137,19 +152,104 @@ then
 	exit 1
 	;;
     esac
-    RENDER_CALL="$LIBLOUIS_TOOL -CliteraryTextTable=$LIBLOUIS_TABLES,braille-patterns.cti $LIBLOUIS_CONFIG"
+
+    #
+    # text encoding
+    #
+    if [ "$CHARSET" = utf-8 ]
+    then
+      LIBLOUIS_CONFIG+=" -CinputTextEncoding=UTF8"
+    else
+      LIBLOUIS_CONFIG+=" -CinputTextEncoding=ascii8"
+    fi
+
+    #
+    # Page numbers options
+    #
+    BRAILLEPAGENUMBER=$(getOption BraillePageNumber)
+    case "$BRAILLEPAGENUMBER" in
+      None) LIBLOUIS_CONFIG+=" -CbraillePages=no";;
+      TopMargin) LIBLOUIS_CONFIG+=" -CbraillePages=yes -CbraillePageNumberAt=top -CpageNumberTopSeparateLine=yes";;
+      BottomMargin) LIBLOUIS_CONFIG+=" -CbraillePages=yes -CbraillePageNumberAt=bottom -CpageNumberBottomSeparateLine=yes";;
+      TopInline) LIBLOUIS_CONFIG+=" -CbraillePages=yes -CbraillePageNumberAt=top -CpageNumberTopSeparateLine=no";;
+      BottomInline) LIBLOUIS_CONFIG+=" -CbraillePages=yes -CbraillePageNumberAt=bottom -CpageNumberBottomSeparateLine=no";;
+      *)
+	printf "ERROR: Unknown braille page number option '%s'\n" "$BRAILLEPAGENUMBER" >&2
+	exit 1
+	;;
+    esac
+
+    PRINTPAGENUMBER=$(getOption PrintPageNumber)
+    case "$PRINTPAGENUMBER" in
+      None) LIBLOUIS_CONFIG+=" -CprintPages=no";;
+      TopMargin) LIBLOUIS_CONFIG+=" -CprintPages=yes -CprintPageNumberAt=top -CpageNumberTopSeparateLine=yes";;
+      BottomMargin) LIBLOUIS_CONFIG+=" -CprintPages=yes -CprintPageNumberAt=bottom -CpageNumberBottomSeparateLine=yes";;
+      TopInline) LIBLOUIS_CONFIG+=" -CprintPages=yes -CprintPageNumberAt=top -CpageNumberTopSeparateLine=no";;
+      BottomInline) LIBLOUIS_CONFIG+=" -CprintPages=yes -CprintPageNumberAt=bottom -CpageNumberBottomSeparateLine=no";;
+      *)
+	printf "ERROR: Unknown print page number option '%s'\n" "$PRINTPAGENUMBER" >&2
+	exit 1
+	;;
+    esac
+
+    # Page numbering in top or bottom margin actually reduce the given margin
+    if [ "$BRAILLEPAGENUMBER" = TopMargin -o "$PRINTPAGENUMBER" = TopMargin ]
+    then
+      TOPMARGIN=$((TOPMARGIN - 1))
+      TEXTHEIGHT=$((TEXTHEIGHT + 1))
+    fi
+    if [ "$BRAILLEPAGENUMBER" = BottomMargin -o "$PRINTPAGENUMBER" = BottomMargin ]
+    then
+      BOTTOMMARGIN=$((BOTTOMMARGIN - 1))
+      TEXTHEIGHT=$((TEXTHEIGHT + 1))
+    fi
+
+    PAGESEPARATOR=$(getOption PageSeparator)
+    case "$PAGESEPARATOR" in
+      True|true) LIBLOUIS_CONFIG+=" -CpageSeparator=yes";;
+      False|false) LIBLOUIS_CONFIG+=" -CpageSeparator=no";;
+      *)
+	printf "ERROR: Unknown page separator option '%s'\n" "$PAGESEPARATOR" >&2
+	exit 1
+	;;
+    esac
+
+    PAGESEPARATORNUMBER=$(getOption PageSeparatorNumber)
+    case "$PAGESEPARATORNUMBER" in
+      True|true) LIBLOUIS_CONFIG+=" -CpageSeparatorNumber=yes";;
+      False|false) LIBLOUIS_CONFIG+=" -CpageSeparatorNumber=no";;
+      *)
+	printf "ERROR: Unknown page separator number option '%s'\n" "$PAGESEPARATORNUMBER" >&2
+	exit 1
+	;;
+    esac
+
+    CONTINUEPAGES=$(getOption ContinuePages)
+    case "$CONTINUEPAGES" in
+      True|true) LIBLOUIS_CONFIG+=" -CcontinuePages=yes";;
+      False|false) LIBLOUIS_CONFIG+=" -CcontinuePages=no";;
+      *)
+	printf "ERROR: Unknown page separator number option '%s'\n" "$CONTINUEPAGES" >&2
+	exit 1
+	;;
+    esac
+
+    LIBLOUIS_CONFIG+=" -CcellsPerLine=$TEXTWIDTH -ClinesPerPage=$TEXTHEIGHT "
+
+    RENDER_CALL="$LIBLOUIS_TOOL -Chyphenate=yes -CliteraryTextTable=en-us-brf.dis,$LIBLOUIS_TABLES,braille-patterns.cti $LIBLOUIS_CONFIG"
   elif type lou_translate > /dev/null
   then
     # Only liblouis, but better than nothing
     setupTextRendering
     printf "WARN: The liblouisutdml package is required for translating braille better\n" >&2
-    TRANSLATE="lou_translate $LIBLOUIS_TABLES,braille-patterns.cti"
+    TRANSLATE="lou_translate en-us-brf.dis,$LIBLOUIS_TABLES,braille-patterns.cti"
   else
     printf "ERROR: The liblouisutdml package is required for translating braille\n" >&2
     exit 1
   fi
 else
   # No translation, only text rendering
+  printf "WARN: No braille table translation was selected\n" >&2
   setupTextRendering
 fi
 
@@ -157,32 +257,39 @@ fi
 cd $TMPDIR
 echo "INFO: Reformating text" >&2
 
+(
+set -o pipefail
+set -e
 if [ -z "$CONVERT" ]
 then
   printf "DEBUG: Calling $RENDER_CALL on '%s'\n" "$FILE" >&2
   if [ -z "$FILE" ]
   then
-    $RENDER_CALL
+    $RENDER_CALL 2> /dev/null | addmargins
   else
-   < "$FILE" $RENDER_CALL
+   < "$FILE" $RENDER_CALL 2> /dev/null | addmargins
   fi
 elif [ -z "$TRANSLATE" ]
 then
   printf "DEBUG: Calling $CONVERT | $RENDER_CALL on '%s'\n" "$FILE" >&2
   if [ -z "$FILE" ]
   then
-    $CONVERT | $RENDER_CALL
+    $CONVERT | $RENDER_CALL 2> /dev/null | addmargins
   else
-  < "$FILE" $CONVERT | $RENDER_CALL
+  < "$FILE" $CONVERT | $RENDER_CALL 2> /dev/null | addmargins
   fi
 else
   printf "DEBUG: Calling $CONVERT | $RENDER_CALL | $TRANSLATE on '%s'\n" "$FILE" >&2
   if [ -z "$FILE" ]
   then
-    $CONVERT | $RENDER_CALL | $TRANSLATE
+    $CONVERT | $RENDER_CALL 2> /dev/null | $TRANSLATE | addmargins
   else
-  < "$FILE" $CONVERT | $RENDER_CALL | $TRANSLATE
+  < "$FILE" $CONVERT | $RENDER_CALL 2> /dev/null | $TRANSLATE | addmargins
   fi
 fi
+) || {
+  printf "ERROR: text conversion pipeline $CONVERT | $RENDER_CALL | $TRANSLATE | addmargins failed\n" >&2
+  exit 1
+}
 
 echo "INFO: Ready" >&2
diff --git a/usr/lib/git-core/git-mergetool--lib b/usr/lib/git-core/git-mergetool--lib
--- a/usr/lib/git-core/git-mergetool--lib
+++ b/usr/lib/git-core/git-mergetool--lib
@@ -125,16 +125,7 @@ setup_user_tool () {
 	}
 
 	merge_cmd () {
-		trust_exit_code=$(git config --bool \
-			"mergetool.$1.trustExitCode" || echo false)
-		if test "$trust_exit_code" = "false"
-		then
-			touch "$BACKUP"
-			( eval $merge_tool_cmd )
-			check_unchanged
-		else
-			( eval $merge_tool_cmd )
-		fi
+		( eval $merge_tool_cmd )
 	}
 }
 
@@ -161,6 +152,28 @@ setup_tool () {
 	translate_merge_tool_path () {
 		echo "$1"
 	}
+
+	# Most tools' exit codes cannot be trusted, so By default we ignore
+	# their exit code and check the merged file's modification time in
+	# check_unchanged() to determine whether or not the merge was
+	# successful.  The return value from run_merge_cmd, by default, is
+	# determined by check_unchanged().
+	#
+	# When a tool's exit code can be trusted then the return value from
+	# run_merge_cmd is simply the tool's exit code, and check_unchanged()
+	# is not called.
+	#
+	# The return value of exit_code_trustable() tells us whether or not we
+	# can trust the tool's exit code.
+	#
+	# User-defined and built-in tools default to false.
+	# Built-in tools advertise that their exit code is trustable by
+	# redefining exit_code_trustable() to true.
+
+	exit_code_trustable () {
+		false
+	}
+
 
 	if ! test -f "$MERGE_TOOLS_DIR/$tool"
 	then
@@ -197,6 +210,19 @@ get_merge_tool_cmd () {
 	fi
 }
 
+trust_exit_code () {
+	if git config --bool "mergetool.$1.trustExitCode"
+	then
+		:; # OK
+	elif exit_code_trustable
+	then
+		echo true
+	else
+		echo false
+	fi
+}
+
+
 # Entry point for running tools
 run_merge_tool () {
 	# If GIT_PREFIX is empty then we cannot use it in tools
@@ -225,7 +251,15 @@ run_diff_cmd () {
 
 # Run a either a configured or built-in merge tool
 run_merge_cmd () {
-	merge_cmd "$1"
+	mergetool_trust_exit_code=$(trust_exit_code "$1")
+	if test "$mergetool_trust_exit_code" = "true"
+	then
+		merge_cmd "$1"
+	else
+		touch "$BACKUP"
+		merge_cmd "$1"
+		check_unchanged
+	fi
 }
 
 list_merge_tool_candidates () {
@@ -316,17 +350,23 @@ guess_merge_tool () {
 }
 
 get_configured_merge_tool () {
-	# Diff mode first tries diff.tool and falls back to merge.tool.
-	# Merge mode only checks merge.tool
+	# If first argument is true, find the guitool instead
+	if test "$1" = true
+	then
+		gui_prefix=gui
+	fi
+
+	# Diff mode first tries diff.(gui)tool and falls back to merge.(gui)tool.
+	# Merge mode only checks merge.(gui)tool
 	if diff_mode
 	then
-		merge_tool=$(git config diff.tool || git config merge.tool)
+		merge_tool=$(git config diff.${gui_prefix}tool || git config merge.${gui_prefix}tool)
 	else
-		merge_tool=$(git config merge.tool)
+		merge_tool=$(git config merge.${gui_prefix}tool)
 	fi
 	if test -n "$merge_tool" && ! valid_tool "$merge_tool"
 	then
-		echo >&2 "git config option $TOOL_MODE.tool set to unknown tool: $merge_tool"
+		echo >&2 "git config option $TOOL_MODE.${gui_prefix}tool set to unknown tool: $merge_tool"
 		echo >&2 "Resetting to default..."
 		return 1
 	fi
diff --git a/usr/lib/git-core/git-stash b/usr/lib/git-core/git-stash
--- a/usr/lib/git-core/git-stash
+++ b/usr/lib/git-core/git-stash
@@ -7,8 +7,11 @@ USAGE="list [<options>]
    or: $dashless drop [-q|--quiet] [<stash>]
    or: $dashless ( pop | apply ) [--index] [-q|--quiet] [<stash>]
    or: $dashless branch <branchname> [<stash>]
-   or: $dashless [save [--patch] [-k|--[no-]keep-index] [-q|--quiet]
-		       [-u|--include-untracked] [-a|--all] [<message>]]
+   or: $dashless save [--patch] [-k|--[no-]keep-index] [-q|--quiet]
+		      [-u|--include-untracked] [-a|--all] [<message>]
+   or: $dashless [push [--patch] [-k|--[no-]keep-index] [-q|--quiet]
+		       [-u|--include-untracked] [-a|--all] [-m <message>]
+		       [-- <pathspec>...]]
    or: $dashless clear"
 
 SUBDIRECTORY_OK=Yes
@@ -16,6 +19,7 @@ OPTIONS_SPEC=
 START_DIR=$(pwd)
 . git-sh-setup
 require_work_tree
+prefix=$(git rev-parse --show-prefix) || exit 1
 cd_to_toplevel
 
 TMP="$GIT_DIR/.git-stash.$$"
@@ -33,15 +37,22 @@ else
 fi
 
 no_changes () {
-	git diff-index --quiet --cached HEAD --ignore-submodules -- &&
-	git diff-files --quiet --ignore-submodules &&
-	(test -z "$untracked" || test -z "$(untracked_files)")
+	git diff-index --quiet --cached HEAD --ignore-submodules -- "$@" &&
+	git diff-files --quiet --ignore-submodules -- "$@" &&
+	(test -z "$untracked" || test -z "$(untracked_files "$@")")
 }
 
 untracked_files () {
+	if test "$1" = "-z"
+	then
+		shift
+		z=-z
+	else
+		z=
+	fi
 	excl_opt=--exclude-standard
 	test "$untracked" = "all" && excl_opt=
-	git ls-files -o -z $excl_opt
+	git ls-files -o $z $excl_opt -- "$@"
 }
 
 clear_stash () {
@@ -56,11 +67,35 @@ clear_stash () {
 }
 
 create_stash () {
-	stash_msg="$1"
-	untracked="$2"
+	stash_msg=
+	untracked=
+	while test $# != 0
+	do
+		case "$1" in
+		-m|--message)
+			shift
+			stash_msg=${1?"BUG: create_stash () -m requires an argument"}
+			;;
+		-m*)
+			stash_msg=${1#-m}
+			;;
+		--message=*)
+			stash_msg=${1#--message=}
+			;;
+		-u|--include-untracked)
+			shift
+			untracked=${1?"BUG: create_stash () -u requires an argument"}
+			;;
+		--)
+			shift
+			break
+			;;
+		esac
+		shift
+	done
 
 	git update-index -q --refresh
-	if no_changes
+	if no_changes "$@"
 	then
 		exit 0
 	fi
@@ -92,7 +127,7 @@ create_stash () {
 		# Untracked files are stored by themselves in a parentless commit, for
 		# ease of unpacking later.
 		u_commit=$(
-			untracked_files | (
+			untracked_files -z "$@" | (
 				GIT_INDEX_FILE="$TMPindex" &&
 				export GIT_INDEX_FILE &&
 				rm -f "$TMPindex" &&
@@ -115,7 +150,7 @@ create_stash () {
 			git read-tree --index-output="$TMPindex" -m $i_tree &&
 			GIT_INDEX_FILE="$TMPindex" &&
 			export GIT_INDEX_FILE &&
-			git diff --name-only -z HEAD -- >"$TMP-stagenames" &&
+			git diff-index --name-only -z HEAD -- "$@" >"$TMP-stagenames" &&
 			git update-index -z --add --remove --stdin <"$TMP-stagenames" &&
 			git write-tree &&
 			rm -f "$TMPindex"
@@ -129,7 +164,7 @@ create_stash () {
 
 		# find out what the user wants
 		GIT_INDEX_FILE="$TMP-index" \
-			git add--interactive --patch=stash -- &&
+			git add--interactive --patch=stash -- "$@" &&
 
 		# state of the working tree
 		w_tree=$(GIT_INDEX_FILE="$TMP-index" git write-tree) ||
@@ -164,6 +199,12 @@ store_stash () {
 			shift
 			stash_msg="$1"
 			;;
+		-m*)
+			stash_msg=${1#-m}
+			;;
+		--message=*)
+			stash_msg=${1#--message=}
+			;;
 		-q|--quiet)
 			quiet=t
 			;;
@@ -189,10 +230,11 @@ store_stash () {
 	return $ret
 }
 
-save_stash () {
+push_stash () {
 	keep_index=
 	patch_mode=
 	untracked=
+	stash_msg=
 	while test $# != 0
 	do
 		case "$1" in
@@ -216,6 +258,17 @@ save_stash () {
 		-a|--all)
 			untracked=all
 			;;
+		-m|--message)
+			shift
+			test -z ${1+x} && usage
+			stash_msg=$1
+			;;
+		-m*)
+			stash_msg=${1#-m}
+			;;
+		--message=*)
+			stash_msg=${1#--message=}
+			;;
 		--help)
 			show_help
 			;;
@@ -225,18 +278,7 @@ save_stash () {
 			;;
 		-*)
 			option="$1"
-			# TRANSLATORS: $option is an invalid option, like
-			# `--blah-blah'. The 7 spaces at the beginning of the
-			# second line correspond to "error: ". So you should line
-			# up the second line with however many characters the
-			# translation of "error: " takes in your language. E.g. in
-			# English this is:
-			#
-			#    $ git stash save --blah-blah 2>&1 | head -n 2
-			#    error: unknown option for 'stash save': --blah-blah
-			#           To provide a message, use git stash save -- '--blah-blah'
-			eval_gettextln "error: unknown option for 'stash save': \$option
-       To provide a message, use git stash save -- '\$option'"
+			eval_gettextln "error: unknown option for 'stash push': \$option"
 			usage
 			;;
 		*)
@@ -246,39 +288,54 @@ save_stash () {
 		shift
 	done
 
+	eval "set $(git rev-parse --sq --prefix "$prefix" -- "$@")"
+
 	if test -n "$patch_mode" && test -n "$untracked"
 	then
 		die "$(gettext "Can't use --patch and --include-untracked or --all at the same time")"
 	fi
 
-	stash_msg="$*"
+	test -n "$untracked" || git ls-files --error-unmatch -- "$@" >/dev/null || exit 1
 
 	git update-index -q --refresh
-	if no_changes
+	if no_changes "$@"
 	then
 		say "$(gettext "No local changes to save")"
 		exit 0
 	fi
+
 	git reflog exists $ref_stash ||
 		clear_stash || die "$(gettext "Cannot initialize stash")"
 
-	create_stash "$stash_msg" $untracked
+	create_stash -m "$stash_msg" -u "$untracked" -- "$@"
 	store_stash -m "$stash_msg" -q $w_commit ||
 	die "$(gettext "Cannot save the current status")"
 	say "$(eval_gettext "Saved working directory and index state \$stash_msg")"
 
 	if test -z "$patch_mode"
 	then
-		git reset --hard ${GIT_QUIET:+-q}
 		test "$untracked" = "all" && CLEAN_X_OPTION=-x || CLEAN_X_OPTION=
-		if test -n "$untracked"
+		if test -n "$untracked" && test $# = 0
 		then
 			git clean --force --quiet -d $CLEAN_X_OPTION
 		fi
 
+		if test $# != 0
+		then
+			test -z "$untracked" && UPDATE_OPTION="-u" || UPDATE_OPTION=
+			test "$untracked" = "all" && FORCE_OPTION="--force" || FORCE_OPTION=
+			git add $UPDATE_OPTION $FORCE_OPTION -- "$@"
+			git diff-index -p --cached --binary HEAD -- "$@" |
+			git apply --index -R
+		else
+			git reset --hard -q
+		fi
+
 		if test "$keep_index" = "t" && test -n "$i_tree"
 		then
-			git read-tree --reset -u $i_tree
+			git read-tree --reset $i_tree
+			git ls-files -z --modified -- "$@" |
+			git checkout-index -z --force --stdin
 		fi
 	else
 		git apply -R < "$TMP-patch" ||
@@ -286,8 +343,38 @@ save_stash () {
 
 		if test "$keep_index" != "t"
 		then
-			git reset
+			git reset -q -- "$@"
 		fi
+	fi
+}
+
+save_stash () {
+	push_options=
+	while test $# != 0
+	do
+		case "$1" in
+		--)
+			shift
+			break
+			;;
+		-*)
+			# pass all options through to push_stash
+			push_options="$push_options $1"
+			;;
+		*)
+			break
+			;;
+		esac
+		shift
+	done
+
+	stash_msg="$*"
+
+	if test -z "$stash_msg"
+	then
+		push_stash $push_options
+	else
+		push_stash $push_options -m "$stash_msg"
 	fi
 }
 
@@ -413,7 +500,7 @@ parse_flags_and_rev()
 
 	case $# in
 		0)
-			have_stash || die "$(gettext "No stash found.")"
+			have_stash || die "$(gettext "No stash entries found.")"
 			set -- ${ref_stash}@{0}
 		;;
 		1)
@@ -502,10 +589,10 @@ apply_stash () {
 
 	if test -n "$u_tree"
 	then
-		GIT_INDEX_FILE="$TMPindex" git-read-tree "$u_tree" &&
+		GIT_INDEX_FILE="$TMPindex" git read-tree "$u_tree" &&
 		GIT_INDEX_FILE="$TMPindex" git checkout-index --all &&
 		rm -f "$TMPindex" ||
-		die "$(gettext "Could not restore untracked files from stash")"
+		die "$(gettext "Could not restore untracked files from stash entry")"
 	fi
 
 	eval "
@@ -559,7 +646,7 @@ pop_stash() {
 		drop_stash "$@"
 	else
 		status=$?
-		say "$(gettext "The stash is kept in case you need it again.")"
+		say "$(gettext "The stash entry is kept in case you need it again.")"
 		exit $status
 	fi
 }
@@ -590,18 +677,21 @@ apply_to_branch () {
 	}
 }
 
+test "$1" = "-p" && set "push" "$@"
+
 PARSE_CACHE='--not-parsed'
-# The default command is "save" if nothing but options are given
+# The default command is "push" if nothing but options are given
 seen_non_option=
 for opt
 do
 	case "$opt" in
+	--) break ;;
 	-*) ;;
 	*) seen_non_option=t; break ;;
 	esac
 done
 
-test -n "$seen_non_option" || set "save" "$@"
+test -n "$seen_non_option" || set "push" "$@"
 
 # Main command set
 case "$1" in
@@ -617,6 +707,10 @@ save)
 	shift
 	save_stash "$@"
 	;;
+push)
+	shift
+	push_stash "$@"
+	;;
 apply)
 	shift
 	apply_stash "$@"
@@ -627,7 +721,7 @@ clear)
 	;;
 create)
 	shift
-	create_stash "$*" && echo "$w_commit"
+	create_stash -m "$*" && echo "$w_commit"
 	;;
 store)
 	shift
@@ -648,7 +742,7 @@ branch)
 *)
 	case $# in
 	0)
-		save_stash &&
+		push_stash &&
 		say "$(gettext "(To restore them type \"git stash apply\")")"
 		;;
 	*)
diff --git a/usr/lib/git-core/git-submodule b/usr/lib/git-core/git-submodule
--- a/usr/lib/git-core/git-submodule
+++ b/usr/lib/git-core/git-submodule
@@ -12,7 +12,8 @@ USAGE="[--quiet] add [-b <branch>] [-f|--force] [--name <name>] [--reference <re
    or: $dashless [--quiet] update [--init] [--remote] [-N|--no-fetch] [-f|--force] [--checkout|--merge|--rebase] [--[no-]recommend-shallow] [--reference <repository>] [--recursive] [--] [<path>...]
    or: $dashless [--quiet] summary [--cached|--files] [--summary-limit <n>] [commit] [--] [<path>...]
    or: $dashless [--quiet] foreach [--recursive] <command>
-   or: $dashless [--quiet] sync [--recursive] [--] [<path>...]"
+   or: $dashless [--quiet] sync [--recursive] [--] [<path>...]
+   or: $dashless [--quiet] absorbgitdirs [--] [<path>...]"
 OPTIONS_SPEC=
 SUBDIRECTORY_OK=Yes
 . git-sh-setup
@@ -21,14 +22,10 @@ require_work_tree
 wt_prefix=$(git rev-parse --show-prefix)
 cd_to_toplevel
 
-# Restrict ourselves to a vanilla subset of protocols; the URLs
-# we get are under control of a remote repository, and we do not
-# want them kicking off arbitrary git-remote-* programs.
-#
-# If the user has already specified a set of allowed protocols,
-# we assume they know what they're doing and use that instead.
-: ${GIT_ALLOW_PROTOCOL=file:git:http:https:ssh}
-export GIT_ALLOW_PROTOCOL
+# Tell the rest of git that any URLs we get don't come
+# directly from the user, so it can apply policy as appropriate.
+GIT_PROTOCOL_FROM_USER=0
+export GIT_PROTOCOL_FROM_USER
 
 command=
 branch=
@@ -46,6 +43,7 @@ prefix=
 custom_name=
 depth=
 progress=
+dissociate=
 
 die_if_unmatched ()
 {
@@ -75,7 +73,7 @@ get_submodule_config () {
 	value=$(git config submodule."$name"."$option")
 	if test -z "$value"
 	then
-		value=$(git config -f .gitmodules submodule."$name"."$option")
+		value=$(git submodule--helper config submodule."$name"."$option")
 	fi
 	printf '%s' "${value:-$default}"
 }
@@ -83,6 +81,11 @@ get_submodule_config () {
 isnumber()
 {
 	n=$(($1 + 0)) 2>/dev/null && test "$n" = "$1"
+}
+
+# Given a full hex object ID, is this the zero OID?
+is_zero_oid () {
+	echo "$1" | sane_egrep '^0+$' >/dev/null 2>&1
 }
 
 # Sanitize the local git environment for use within a submodule. We
@@ -121,6 +124,9 @@ cmd_add()
 		-q|--quiet)
 			GIT_QUIET=1
 			;;
+		--progress)
+			progress=1
+			;;
 		--reference)
 			case "$2" in '') usage ;; esac
 			reference_path=$2
@@ -128,6 +134,9 @@ cmd_add()
 			;;
 		--reference=*)
 			reference_path="${1#--reference=}"
+			;;
+		--dissociate)
+			dissociate=1
 			;;
 		--name)
 			case "$2" in '') usage ;; esac
@@ -155,6 +164,11 @@ cmd_add()
 		esac
 		shift
 	done
+
+	if ! git submodule--helper config --check-writeable >/dev/null 2>&1
+	then
+		 die "$(eval_gettext "please make sure that the .gitmodules file is in the working tree")"
+	fi
 
 	if test -n "$reference_path"
 	then
@@ -208,10 +222,17 @@ cmd_add()
 			tstart
 			s|/*$||
 		')
-	git ls-files --error-unmatch "$sm_path" > /dev/null 2>&1 &&
-	die "$(eval_gettext "'\$sm_path' already exists in the index")"
+	if test -z "$force"
+	then
+		git ls-files --error-unmatch "$sm_path" > /dev/null 2>&1 &&
+		die "$(eval_gettext "'\$sm_path' already exists in the index")"
+	else
+		git ls-files -s "$sm_path" | sane_grep -v "^160000" > /dev/null 2>&1 &&
+		die "$(eval_gettext "'\$sm_path' already exists in the index and is not a submodule")"
+	fi
 
-	if test -z "$force" && ! git add --dry-run --ignore-missing "$sm_path" > /dev/null 2>&1
+	if test -z "$force" &&
+		! git add --dry-run --ignore-missing --no-warn-embedded-repo "$sm_path" > /dev/null 2>&1
 	then
 		eval_gettextln "The following path is ignored by one of your .gitignore files:
 \$sm_path
@@ -242,11 +263,6 @@ Use -f if you really want to add it." >&2
 		fi
 
 	else
-		sm_gitdir=".git/modules/$sm_name"
-		if ! git submodule--helper validate-git-dir "$sm_gitdir" "$sm_name"
-		then
-			die "$(eval_gettextln "refusing to create/use '\$sm_gitdir' in another submodule's git dir")"
-		fi
 		if test -d ".git/modules/$sm_name"
 		then
 			if test -z "$force"
@@ -262,7 +278,7 @@ or you are unsure what this means choose another name with the '--name' option."
 				eval_gettextln "Reactivating local git directory for submodule '\$sm_name'."
 			fi
 		fi
-		git submodule--helper clone ${GIT_QUIET:+--quiet} --prefix "$wt_prefix" --path "$sm_path" --name "$sm_name" --url "$realrepo" ${reference:+"$reference"} ${depth:+"$depth"} || exit
+		git submodule--helper clone ${GIT_QUIET:+--quiet} ${progress:+"--progress"} --prefix "$wt_prefix" --path "$sm_path" --name "$sm_name" --url "$realrepo" ${reference:+"$reference"} ${dissociate:+"--dissociate"} ${depth:+"$depth"} || exit
 		(
 			sanitize_submodule_env
 			cd "$sm_path" &&
@@ -275,17 +291,31 @@ or you are unsure what this means choose another name with the '--name' option."
 	fi
 	git config submodule."$sm_name".url "$realrepo"
 
-	git add $force "$sm_path" ||
+	git add --no-warn-embedded-repo $force "$sm_path" ||
 	die "$(eval_gettext "Failed to add submodule '\$sm_path'")"
 
-	git config -f .gitmodules submodule."$sm_name".path "$sm_path" &&
-	git config -f .gitmodules submodule."$sm_name".url "$repo" &&
+	git submodule--helper config submodule."$sm_name".path "$sm_path" &&
+	git submodule--helper config submodule."$sm_name".url "$repo" &&
 	if test -n "$branch"
 	then
-		git config -f .gitmodules submodule."$sm_name".branch "$branch"
+		git submodule--helper config submodule."$sm_name".branch "$branch"
 	fi &&
 	git add --force .gitmodules ||
 	die "$(eval_gettext "Failed to register submodule '\$sm_path'")"
+
+	# NEEDSWORK: In a multi-working-tree world, this needs to be
+	# set in the per-worktree config.
+	if git config --get submodule.active >/dev/null
+	then
+		# If the submodule being adding isn't already covered by the
+		# current configured pathspec, set the submodule's active flag
+		if ! git submodule--helper is-active "$sm_path"
+		then
+			git config submodule."$sm_name".active "true"
+		fi
+	else
+		git config submodule."$sm_name".active "true"
+	fi
 }
 
 #
@@ -316,45 +346,7 @@ cmd_foreach()
 		shift
 	done
 
-	toplevel=$(pwd)
-
-	# dup stdin so that it can be restored when running the external
-	# command in the subshell (and a recursive call to this function)
-	exec 3<&0
-
-	{
-		git submodule--helper list --prefix "$wt_prefix" ||
-		echo "#unmatched" $?
-	} |
-	while read mode sha1 stage sm_path
-	do
-		die_if_unmatched "$mode" "$sha1"
-		if test -e "$sm_path"/.git
-		then
-			displaypath=$(git submodule--helper relative-path "$prefix$sm_path" "$wt_prefix")
-			say "$(eval_gettext "Entering '\$displaypath'")"
-			name=$(git submodule--helper name "$sm_path")
-			(
-				prefix="$prefix$sm_path/"
-				sanitize_submodule_env
-				cd "$sm_path" &&
-				sm_path=$(git submodule--helper relative-path "$sm_path" "$wt_prefix") &&
-				# we make $path available to scripts ...
-				path=$sm_path &&
-				if test $# -eq 1
-				then
-					eval "$1"
-				else
-					"$@"
-				fi &&
-				if test -n "$recursive"
-				then
-					cmd_foreach "--recursive" "$@"
-				fi
-			) <&3 3<&- ||
-			die "$(eval_gettext "Stopping at '\$displaypath'; script returned non-zero status.")"
-		fi
-	done
+	git ${wt_prefix:+-C "$wt_prefix"} ${prefix:+--super-prefix "$prefix"} submodule--helper foreach ${GIT_QUIET:+--quiet} ${recursive:+--recursive} "$@"
 }
 
 #
@@ -385,7 +377,7 @@ cmd_init()
 		shift
 	done
 
-	git ${wt_prefix:+-C "$wt_prefix"} submodule--helper init ${GIT_QUIET:+--quiet} ${prefix:+--prefix "$prefix"} "$@"
+	git ${wt_prefix:+-C "$wt_prefix"} ${prefix:+--super-prefix "$prefix"} submodule--helper init ${GIT_QUIET:+--quiet}  "$@"
 }
 
 #
@@ -421,60 +413,7 @@ cmd_deinit()
 		shift
 	done
 
-	if test -n "$deinit_all" && test "$#" -ne 0
-	then
-		echo >&2 "$(eval_gettext "pathspec and --all are incompatible")"
-		usage
-	fi
-	if test $# = 0 && test -z "$deinit_all"
-	then
-		die "$(eval_gettext "Use '--all' if you really want to deinitialize all submodules")"
-	fi
-
-	{
-		git submodule--helper list --prefix "$wt_prefix" "$@" ||
-		echo "#unmatched" $?
-	} |
-	while read mode sha1 stage sm_path
-	do
-		die_if_unmatched "$mode" "$sha1"
-		name=$(git submodule--helper name "$sm_path") || exit
-
-		displaypath=$(git submodule--helper relative-path "$sm_path" "$wt_prefix")
-
-		# Remove the submodule work tree (unless the user already did it)
-		if test -d "$sm_path"
-		then
-			# Protect submodules containing a .git directory
-			if test -d "$sm_path/.git"
-			then
-				die "$(eval_gettext "\
-Submodule work tree '\$displaypath' contains a .git directory
-(use 'rm -rf' if you really want to remove it including all of its history)")"
-			fi
-
-			if test -z "$force"
-			then
-				git rm -qn "$sm_path" ||
-				die "$(eval_gettext "Submodule work tree '\$displaypath' contains local modifications; use '-f' to discard them")"
-			fi
-			rm -rf "$sm_path" &&
-			say "$(eval_gettext "Cleared directory '\$displaypath'")" ||
-			say "$(eval_gettext "Could not remove submodule work tree '\$displaypath'")"
-		fi
-
-		mkdir "$sm_path" || say "$(eval_gettext "Could not create empty submodule directory '\$displaypath'")"
-
-		# Remove the .git/config entries (unless the user already did it)
-		if test -n "$(git config --get-regexp submodule."$name\.")"
-		then
-			# Remove the whole section so we have a clean state when
-			# the user later decides to init this submodule again
-			url=$(git config submodule."$name".url)
-			git config --remove-section submodule."$name" 2>/dev/null &&
-			say "$(eval_gettext "Submodule '\$name' (\$url) unregistered for path '\$displaypath'")"
-		fi
-	done
+	git ${wt_prefix:+-C "$wt_prefix"} submodule--helper deinit ${GIT_QUIET:+--quiet} ${prefix:+--prefix "$prefix"} ${force:+--force} ${deinit_all:+--all} "$@"
 }
 
 is_tip_reachable () (
@@ -510,8 +449,11 @@ cmd_update()
 		-q|--quiet)
 			GIT_QUIET=1
 			;;
+		-v)
+			GIT_QUIET=0
+			;;
 		--progress)
-			progress="--progress"
+			progress=1
 			;;
 		-i|--init)
 			init=1
@@ -539,6 +481,9 @@ cmd_update()
 			;;
 		--reference=*)
 			reference="$1"
+			;;
+		--dissociate)
+			dissociate=1
 			;;
 		-m|--merge)
 			update="merge"
@@ -592,41 +537,32 @@ cmd_update()
 
 	{
 	git submodule--helper update-clone ${GIT_QUIET:+--quiet} \
-		${progress:+"$progress"} \
+		${progress:+"--progress"} \
 		${wt_prefix:+--prefix "$wt_prefix"} \
 		${prefix:+--recursive-prefix "$prefix"} \
 		${update:+--update "$update"} \
 		${reference:+"$reference"} \
+		${dissociate:+"--dissociate"} \
 		${depth:+--depth "$depth"} \
 		${require_init:+--require-init} \
-		${recommend_shallow:+"$recommend_shallow"} \
-		${jobs:+$jobs} \
+		$recommend_shallow \
+		$jobs \
 		"$@" || echo "#unmatched" $?
 	} | {
 	err=
-	while read mode sha1 stage just_cloned sm_path
+	while read -r quickabort sha1 just_cloned sm_path
 	do
-		die_if_unmatched "$mode" "$sha1"
+		die_if_unmatched "$quickabort" "$sha1"
 
-		name=$(git submodule--helper name "$sm_path") || exit
-		url=$(git config submodule."$name".url)
-		if ! test -z "$update"
-		then
-			update_module=$update
-		else
-			update_module=$(git config submodule."$name".update)
-			if test -z "$update_module"
-			then
-				update_module="checkout"
-			fi
-		fi
+		git submodule--helper ensure-core-worktree "$sm_path"
+
+		update_module=$(git submodule--helper update-module-mode $just_cloned "$sm_path" $update)
 
 		displaypath=$(git submodule--helper relative-path "$prefix$sm_path" "$wt_prefix")
 
 		if test $just_cloned -eq 1
 		then
 			subsha1=
-			update_module=checkout
 		else
 			subsha1=$(sanitize_submodule_env; cd "$sm_path" &&
 				git rev-parse --verify HEAD) ||
@@ -663,7 +599,7 @@ cmd_update()
 				# is not reachable from a ref.
 				is_tip_reachable "$sm_path" "$sha1" ||
 				fetch_in_submodule "$sm_path" $depth ||
-				die "$(eval_gettext "Unable to fetch in submodule path '\$displaypath'")"
+				say "$(eval_gettext "Unable to fetch in submodule path '\$displaypath'")"
 
 				# Now we tried the usual fetch, but $sha1 may
 				# not be reachable from any of the refs
@@ -698,7 +634,7 @@ cmd_update()
 				must_die_on_failure=yes
 				;;
 			*)
-				die "$(eval_gettext "Invalid update mode '$update_module' for submodule '$name'")"
+				die "$(eval_gettext "Invalid update mode '$update_module' for submodule path '$path'")"
 			esac
 
 			if (sanitize_submodule_env; cd "$sm_path" && $command "$sha1")
@@ -754,18 +690,6 @@ cmd_update()
 	}
 }
 
-set_name_rev () {
-	revname=$( (
-		sanitize_submodule_env
-		cd "$1" && {
-			git describe "$2" 2>/dev/null ||
-			git describe --tags "$2" 2>/dev/null ||
-			git describe --contains "$2" 2>/dev/null ||
-			git describe --all --always "$2"
-		}
-	) )
-	test -z "$revname" || revname=" ($revname)"
-}
 #
 # Show commit summary for submodules in index or working tree
 #
@@ -843,7 +767,7 @@ cmd_summary() {
 	# Get modified modules cared by user
 	modules=$(git $diff_cmd $cached --ignore-submodules=dirty --raw $head -- "$@" |
 		sane_egrep '^:([0-7]* )?160000' |
-		while read mod_src mod_dst sha1_src sha1_dst status sm_path
+		while read -r mod_src mod_dst sha1_src sha1_dst status sm_path
 		do
 			# Always show modules deleted or type-changed (blob<->module)
 			if test "$status" = D || test "$status" = T
@@ -859,7 +783,7 @@ cmd_summary() {
 				test $status != A && test $ignore_config = all && continue
 			fi
 			# Also show added or modified modules which are checked out
-			GIT_DIR="$sm_path/.git" git-rev-parse --git-dir >/dev/null 2>&1 &&
+			GIT_DIR="$sm_path/.git" git rev-parse --git-dir >/dev/null 2>&1 &&
 			printf '%s\n' "$sm_path"
 		done
 	)
@@ -869,10 +793,10 @@ cmd_summary() {
 	git $diff_cmd $cached --ignore-submodules=dirty --raw $head -- $modules |
 	sane_egrep '^:([0-7]* )?160000' |
 	cut -c2- |
-	while read mod_src mod_dst sha1_src sha1_dst status name
+	while read -r mod_src mod_dst sha1_src sha1_dst status name
 	do
 		if test -z "$cached" &&
-			test $sha1_dst = 0000000000000000000000000000000000000000
+			is_zero_oid $sha1_dst
 		then
 			case "$mod_dst" in
 			160000)
@@ -893,11 +817,11 @@ cmd_summary() {
 		missing_dst=
 
 		test $mod_src = 160000 &&
-		! GIT_DIR="$name/.git" git-rev-parse -q --verify $sha1_src^0 >/dev/null &&
+		! GIT_DIR="$name/.git" git rev-parse -q --verify $sha1_src^0 >/dev/null &&
 		missing_src=t
 
 		test $mod_dst = 160000 &&
-		! GIT_DIR="$name/.git" git-rev-parse -q --verify $sha1_dst^0 >/dev/null &&
+		! GIT_DIR="$name/.git" git rev-parse -q --verify $sha1_dst^0 >/dev/null &&
 		missing_dst=t
 
 		display_name=$(git submodule--helper relative-path "$name" "$wt_prefix")
@@ -1012,55 +936,7 @@ cmd_status()
 		shift
 	done
 
-	{
-		git submodule--helper list --prefix "$wt_prefix" "$@" ||
-		echo "#unmatched" $?
-	} |
-	while read mode sha1 stage sm_path
-	do
-		die_if_unmatched "$mode" "$sha1"
-		name=$(git submodule--helper name "$sm_path") || exit
-		url=$(git config submodule."$name".url)
-		displaypath=$(git submodule--helper relative-path "$prefix$sm_path" "$wt_prefix")
-		if test "$stage" = U
-		then
-			say "U$sha1 $displaypath"
-			continue
-		fi
-		if test -z "$url" ||
-		{
-			! test -d "$sm_path"/.git &&
-			! test -f "$sm_path"/.git
-		}
-		then
-			say "-$sha1 $displaypath"
-			continue;
-		fi
-		if git diff-files --ignore-submodules=dirty --quiet -- "$sm_path"
-		then
-			set_name_rev "$sm_path" "$sha1"
-			say " $sha1 $displaypath$revname"
-		else
-			if test -z "$cached"
-			then
-				sha1=$(sanitize_submodule_env; cd "$sm_path" && git rev-parse --verify HEAD)
-			fi
-			set_name_rev "$sm_path" "$sha1"
-			say "+$sha1 $displaypath$revname"
-		fi
-
-		if test -n "$recursive"
-		then
-			(
-				prefix="$displaypath/"
-				sanitize_submodule_env
-				wt_prefix=
-				cd "$sm_path" &&
-				eval cmd_status
-			) ||
-			die "$(eval_gettext "Failed to recurse into submodule path '\$sm_path'")"
-		fi
-	done
+	git ${wt_prefix:+-C "$wt_prefix"} ${prefix:+--super-prefix "$prefix"} submodule--helper status ${GIT_QUIET:+--quiet} ${cached:+--cached} ${recursive:+--recursive} "$@"
 }
 #
 # Sync remote urls for submodules
@@ -1092,59 +968,13 @@ cmd_sync()
 			;;
 		esac
 	done
-	cd_to_toplevel
-	{
-		git submodule--helper list --prefix "$wt_prefix" "$@" ||
-		echo "#unmatched" $?
-	} |
-	while read mode sha1 stage sm_path
-	do
-		die_if_unmatched "$mode" "$sha1"
-		name=$(git submodule--helper name "$sm_path")
-		url=$(git config -f .gitmodules --get submodule."$name".url)
 
-		# Possibly a url relative to parent
-		case "$url" in
-		./*|../*)
-			# rewrite foo/bar as ../.. to find path from
-			# submodule work tree to superproject work tree
-			up_path="$(printf '%s\n' "$sm_path" | sed "s/[^/][^/]*/../g")" &&
-			# guarantee a trailing /
-			up_path=${up_path%/}/ &&
-			# path from submodule work tree to submodule origin repo
-			sub_origin_url=$(git submodule--helper resolve-relative-url "$url" "$up_path") &&
-			# path from superproject work tree to submodule origin repo
-			super_config_url=$(git submodule--helper resolve-relative-url "$url") || exit
-			;;
-		*)
-			sub_origin_url="$url"
-			super_config_url="$url"
-			;;
-		esac
+	git ${wt_prefix:+-C "$wt_prefix"} ${prefix:+--super-prefix "$prefix"} submodule--helper sync ${GIT_QUIET:+--quiet} ${recursive:+--recursive} "$@"
+}
 
-		if git config "submodule.$name.url" >/dev/null 2>/dev/null
-		then
-			displaypath=$(git submodule--helper relative-path "$prefix$sm_path" "$wt_prefix")
-			say "$(eval_gettext "Synchronizing submodule url for '\$displaypath'")"
-			git config submodule."$name".url "$super_config_url"
-
-			if test -e "$sm_path"/.git
-			then
-			(
-				sanitize_submodule_env
-				cd "$sm_path"
-				remote=$(get_default_remote)
-				git config remote."$remote".url "$sub_origin_url"
-
-				if test -n "$recursive"
-				then
-					prefix="$prefix$sm_path/"
-					eval cmd_sync
-				fi
-			)
-			fi
-		fi
-	done
+cmd_absorbgitdirs()
+{
+	git submodule--helper absorb-git-dirs --prefix "$wt_prefix" "$@"
 }
 
 # This loop parses the command line arguments to find the
@@ -1156,7 +986,7 @@ cmd_sync()
 while test $# != 0 && test -z "$command"
 do
 	case "$1" in
-	add | foreach | init | deinit | update | status | summary | sync)
+	add | foreach | init | deinit | update | status | summary | sync | absorbgitdirs)
 		command=$1
 		;;
 	-q|--quiet)
diff --git a/usr/lib/kernel/install.d/90-loaderentry.install b/usr/lib/kernel/install.d/90-loaderentry.install
--- a/usr/lib/kernel/install.d/90-loaderentry.install
+++ b/usr/lib/kernel/install.d/90-loaderentry.install
@@ -6,21 +6,25 @@ COMMAND="$1"
 KERNEL_VERSION="$2"
 BOOT_DIR_ABS="$3"
 KERNEL_IMAGE="$4"
+INITRD_OPTIONS_START="5"
 
-if [[ -f /etc/machine-id ]]; then
-    read MACHINE_ID < /etc/machine-id
+if ! [[ $KERNEL_INSTALL_MACHINE_ID ]]; then
+    exit 0
 fi
 
-if ! [[ $MACHINE_ID ]]; then
-    exit 1
+if ! [[ -d "$BOOT_DIR_ABS" ]]; then
+    exit 0
 fi
+
+MACHINE_ID=$KERNEL_INSTALL_MACHINE_ID
 
 BOOT_DIR="/$MACHINE_ID/$KERNEL_VERSION"
 BOOT_ROOT=${BOOT_DIR_ABS%$BOOT_DIR}
-LOADER_ENTRY="$BOOT_ROOT/loader/entries/$MACHINE_ID-$KERNEL_VERSION.conf"
 
 if [[ $COMMAND == remove ]]; then
-    exec rm -f "$LOADER_ENTRY"
+    rm -f "$BOOT_ROOT/loader/entries/$MACHINE_ID-$KERNEL_VERSION.conf"
+    rm -f "$BOOT_ROOT/loader/entries/$MACHINE_ID-$KERNEL_VERSION+"*".conf"
+    exit 0
 fi
 
 if ! [[ $COMMAND == add ]]; then
@@ -61,12 +65,41 @@ if ! [[ ${BOOT_OPTIONS[*]} ]]; then
     exit 1
 fi
 
+if [[ -f /etc/kernel/tries ]]; then
+    read -r TRIES </etc/kernel/tries
+    if ! [[ "$TRIES" =~ ^[0-9]+$ ]] ; then
+        echo "/etc/kernel/tries does not contain an integer." >&2
+        exit 1
+    fi
+    LOADER_ENTRY="$BOOT_ROOT/loader/entries/$MACHINE_ID-$KERNEL_VERSION+$TRIES.conf"
+else
+    LOADER_ENTRY="$BOOT_ROOT/loader/entries/$MACHINE_ID-$KERNEL_VERSION.conf"
+fi
+
 cp "$KERNEL_IMAGE" "$BOOT_DIR_ABS/linux" &&
    chown root:root "$BOOT_DIR_ABS/linux" &&
    chmod 0644 "$BOOT_DIR_ABS/linux" || {
     echo "Could not copy '$KERNEL_IMAGE to '$BOOT_DIR_ABS/linux'." >&2
     exit 1
 }
+
+INITRD_OPTIONS=( "${@:${INITRD_OPTIONS_START}}" )
+
+for initrd in "${INITRD_OPTIONS[@]}"; do
+    if [[ -f "${initrd}" ]]; then
+        initrd_basename="$(basename ${initrd})"
+        cp "${initrd}" "$BOOT_DIR_ABS/${initrd_basename}" &&
+            chown root:root "$BOOT_DIR_ABS/${initrd_basename}" &&
+            chmod 0644 "$BOOT_DIR_ABS/${initrd_basename}" || {
+             echo "Could not copy '${initrd}' to '$BOOT_DIR_ABS/${initrd_basename}'." >&2
+             exit 1
+        }
+    fi
+done
+
+# If no initrd option is supplied, fallback to "initrd" which is
+# the name used by dracut when generating it in its kernel-install hook
+[[ ${#INITRD_OPTIONS[@]} == 0 ]] && INITRD_OPTIONS=( initrd )
 
 mkdir -p "${LOADER_ENTRY%/*}" || {
     echo "Could not create loader entry directory '${LOADER_ENTRY%/*}'." >&2
@@ -79,8 +112,10 @@ mkdir -p "${LOADER_ENTRY%/*}" || {
     echo "machine-id $MACHINE_ID"
     echo "options    ${BOOT_OPTIONS[*]}"
     echo "linux      $BOOT_DIR/linux"
-    [[ -f $BOOT_DIR_ABS/initrd ]] && \
-        echo "initrd     $BOOT_DIR/initrd"
+    for initrd in "${INITRD_OPTIONS[@]}"; do
+        [[ -f $BOOT_DIR_ABS/$(basename ${initrd}) ]] && \
+            echo "initrd     $BOOT_DIR/$(basename ${initrd})"
+    done
     :
 } > "$LOADER_ENTRY" || {
     echo "Could not create loader entry '$LOADER_ENTRY'." >&2
diff --git a/usr/share/initramfs-tools/hook-functions b/usr/share/initramfs-tools/hook-functions
--- a/usr/share/initramfs-tools/hook-functions
+++ b/usr/share/initramfs-tools/hook-functions
@@ -44,7 +44,7 @@ add_modules_from_file()
 		return
 	fi
 
-	grep '^[^#]' ${1} | while read module args; do
+	grep '^[^#]' "${1}" | while read -r module args; do
 		[ -n "$module" ] || continue
 		force_load "${module}" "${args}"
 	done
@@ -64,9 +64,10 @@ manual_add_modules()
 	# module.ko' as we want.  However it also means that 'softdep'
 	# configuration lines and embedded softdep information is not
 	# processed.  So we run twice, with and without this option.
-	{ modprobe --all --set-version="${version}" --ignore-install --quiet --show-depends "$@";
+	# shellcheck disable=SC2034
+	{ modprobe --all --set-version="${version?}" --ignore-install --quiet --show-depends "$@";
 	  modprobe --all --set-version="${version}" --quiet --show-depends "$@"; } |
-	while read prefix kmod options ; do
+	while read -r prefix kmod options ; do
 		if [ "${prefix}" != "insmod" ]; then
 			continue
 		fi
@@ -91,9 +92,9 @@ manual_add_modules()
 				fi
 
 				kmod_modname="${kmod##*/}"
-				kmod_modname="${kmod_modname%.ko}"
+				kmod_modname="${kmod_modname%%.*}"
 				if grep -q "^$kmod_modname\\>" /proc/modules "${CONFDIR}/modules"; then
-					echo "W: Possible missing firmware /lib/firmware/${firmware} for module $(basename ${kmod} .ko)" >&2
+					echo "W: Possible missing firmware /lib/firmware/${firmware} for module ${kmod_modname}" >&2
 				fi
 				continue
 			fi
@@ -109,8 +110,8 @@ manual_add_modules()
 }
 
 # $1 = file type (for logging)
-# $2 = file to copy to ramdisk
-# $3 (optional) Name for the file on the ramdisk
+# $2 = file to copy to initramfs
+# $3 (optional) Name for the file on the initramfs
 # Location of the image dir is assumed to be $DESTDIR
 # If the target exists, we leave it and return 1.
 # On any other error, we return >1.
@@ -127,10 +128,14 @@ copy_file() {
 		target="${target}/${src##*/}"
 	fi
 
+	# Canonicalise usr-merged target directories
+	case "${target}" in
+	/bin/* | /lib* | /sbin/*) target="/usr${target}" ;;
+	esac
+
 	# check if already copied
 	[ -e "${DESTDIR}/${target}" ] && return 1
 
-	#FIXME: inst_dir
 	mkdir -p "${DESTDIR}/${target%/*}"
 
 	if [ -h "${src}" ]; then
@@ -138,8 +143,16 @@ copy_file() {
 		# just link directly to the ultimate target
 		link_target="$(readlink -f "${src}")" || return $(($? + 1))
 
+		# Update source for the copy
+		src="${link_target}"
+
+		# Canonicalise usr-merged target directories
+		case "${link_target}" in
+		/bin/* | /lib* | /sbin/*) link_target="/usr${link_target}" ;;
+		esac
+
 		if [ "${link_target}" != "${target}" ]; then
-			[ "${verbose}" = "y" ] && echo "Adding ${type}-link ${src}"
+			[ "${verbose?}" = "y" ] && echo "Adding ${type}-link ${src}"
 
 			# Create a relative link so it always points
 			# to the right place
@@ -147,7 +160,6 @@ copy_file() {
 		fi
 
 		# Copy the link target if it doesn't already exist
-		src="${link_target}"
 		target="${link_target}"
 		[ -e "${DESTDIR}/${target}" ] && return 0
 		mkdir -p "${DESTDIR}/${target%/*}"
@@ -158,8 +170,8 @@ copy_file() {
 	cp -pP "${src}" "${DESTDIR}/${target}" || return $(($? + 1))
 }
 
-# $1 = executable to copy to ramdisk, with library dependencies
-# $2 (optional) Name for the file on the ramdisk
+# $1 = executable to copy to initramfs, with library dependencies
+# $2 (optional) Name for the file on the initramfs
 # Location of the image dir is assumed to be $DESTDIR
 # We never overwrite the target if it exists.
 copy_exec() {
@@ -197,7 +209,7 @@ copy_exec() {
 # Copy entire subtrees to the initramfs
 copy_modules_dir()
 {
-	local kmod exclude
+	local kmod first exclude
 	local modules=
 	local dir="$1"
 	shift
@@ -211,13 +223,24 @@ copy_modules_dir()
 			echo "(excluding $*)"
 		fi
 	fi
-	while [ $# -ge 1 ]; do
-		exclude="${exclude:-} -name $1 -prune -o "
-		shift
+
+	# Build up an expression for find
+	first=true
+	for exclude in "$@"; do
+		# Change .ko suffix in exclusion to .ko*
+		if [ "${exclude%.ko}" != "${exclude}" ]; then
+			exclude="${exclude}*"
+		fi
+		$first && set --
+		set -- "$@" -name "${exclude}" -prune -o
+		first=false
 	done
-	for kmod in $(find "${MODULESDIR}/${dir}" ${exclude:-} -name '*.ko' -printf '%f\n'); do
-		modules="$modules ${kmod%.ko}"
+
+	# shellcheck disable=SC2044
+	for kmod in $(find "${MODULESDIR}/${dir}" "$@" -name '*.ko*' -printf '%f\n'); do
+		modules="$modules ${kmod%%.*}"
 	done
+	# shellcheck disable=SC2086
 	manual_add_modules $modules
 }
 
@@ -237,15 +260,15 @@ sys_walk_mod_add()
 		fi
 
 		# current driver module
-		driver_path="$(readlink -f ${device_path}/driver/module)"
+		driver_path="$(readlink -f "${device_path}/driver/module")"
 		if [ -e "$driver_path" ]; then
-			module="$(basename $(readlink -f $driver_path))"
+			module="$(basename "$(readlink -f "$driver_path")")"
 			if [ -n "${module}" ]; then
 				manual_add_modules "${module}"
 			fi
 		fi
 
-		device_path="$(dirname ${device_path})"
+		device_path="$(dirname "${device_path}")"
 	done
 }
 
@@ -264,11 +287,11 @@ block_dev_sys_walk_mod_add()
 	fi
 
 	# Iterate over component of a layered device
-	ls -1 "$disk_sys_path/slaves" | while read component; do
-		block_dev_sys_walk_mod_add "$disk_sys_path/slaves/$component"
+	find "$disk_sys_path/slaves" -mindepth 1 -maxdepth 1 | while read -r component; do
+		block_dev_sys_walk_mod_add "$component"
 	done
 
-	sys_walk_mod_add ${dev_sys_path}
+	sys_walk_mod_add "${dev_sys_path}"
 }
 
 block_dev_mod_add()
@@ -299,22 +322,22 @@ block_dev_mod_add()
 add_loaded_modules()
 {
 	local pattern="$1"
-	local module
-	local builtin=/lib/modules/$(uname -r)/modules.builtin
+	local module builtin
+	builtin="/lib/modules/$(uname -r)/modules.builtin"
 
 	for module in /sys/module/$pattern; do
 		if [ -d "$module" ]; then
-			manual_add_modules $(basename $module)
+			manual_add_modules "$(basename "$module")"
 		fi
 	done
-	if [ -f $builtin ]; then
-		while read module; do
+	if [ -f "$builtin" ]; then
+		while read -r module; do
 			case "$module" in
 			*/$pattern.ko)
-				manual_add_modules $(basename $module .ko)
+				manual_add_modules "$(basename "$module" .ko)"
 				;;
 			esac
-		done < $builtin
+		done < "$builtin"
 	fi
 }
 
@@ -332,9 +355,10 @@ dep_add_modules_mount()
 	fi
 
 	# find out block device + fstype
-	eval "$(while read dev mp fs opts rest ; do \
+	# shellcheck disable=SC2034
+	eval "$(while read -r dev mp fs opts rest ; do \
 		[ "$mp" = "$dir" ] && [ "$fs" != "rootfs" ] \
-		&& printf "dev_node=$dev\nFSTYPE=$fs"\
+		&& printf "dev_node=%s\\nFSTYPE=%s" "$dev" "$fs"\
 		&& break; done < /proc/mounts)"
 
 	# Only the root mountpoint has to exist; do nothing if any other
@@ -353,11 +377,12 @@ dep_add_modules_mount()
 	if [ "$dir" = / ] && [ "${dev_node}" = "/dev/root" ] ; then
 		if [ -b "${dev_node}" ]; then
 			# Match it to the canonical device name by UUID
-			dev_node="/dev/disk/by-uuid/"$(blkid -o value -s UUID ${dev_node}) 2>/dev/null
+			dev_node="/dev/disk/by-uuid/"$(blkid -o value -s UUID "${dev_node}") 2>/dev/null
 		else
 			# Does not exist in our namespace, so look at the
 			# kernel command line
 			dev_node=
+			# shellcheck disable=SC2013
 			for arg in $(cat /proc/cmdline); do
 				case "$arg" in
 				root=*)
@@ -377,11 +402,11 @@ dep_add_modules_mount()
 	fi
 
 	# recheck device
-	if [ -z "$dev_node" ] || ! dev_node="$(readlink -f ${dev_node})" \
+	if [ -z "$dev_node" ] || ! dev_node="$(readlink -f "${dev_node}")" \
 		|| ! [ -b "$dev_node" ]; then
 		echo "mkinitramfs: failed to determine device for $dir" >&2
 		echo "mkinitramfs: workaround is MODULES=most, check:" >&2
-		echo "grep -r MODULES /etc/initramfs-tools/" >&2
+		echo "grep -r MODULES ${CONFDIR}" >&2
 		echo "" >&2
 		echo "Error please report bug on initramfs-tools" >&2
 		echo "Include the output of 'mount' and 'cat /proc/mounts'" >&2
@@ -389,7 +414,7 @@ dep_add_modules_mount()
 	fi
 
 	# do not trust mount, check superblock
-	eval "$(/usr/lib/klibc/bin/fstype ${dev_node})"
+	eval "$(/usr/lib/klibc/bin/fstype "${dev_node}")"
 
 	# check that fstype fs recognition
 	if [ "${FSTYPE}" = "unknown" ]; then
@@ -403,7 +428,7 @@ dep_add_modules_mount()
 	fi
 
 	# Add filesystem
-	manual_add_modules ${FSTYPE}
+	manual_add_modules "${FSTYPE}"
 
 	block_dev_mod_add "$dev_node"
 }
@@ -424,8 +449,8 @@ dep_add_modules()
 	fi
 
 	# sys walk some important device classes
-	for class in gpio phy regulator rtc; do
-		for device in /sys/class/$class/*; do
+	for class in extcon gpio phy regulator rtc; do
+		for device in "/sys/class/$class"/*; do
 			device="$(readlink -f "$device")" \
 				&& sys_walk_mod_add "$device"
 		done
@@ -478,6 +503,7 @@ dep_add_modules()
 		modules="$modules sunvnet sunvdc"
 	fi
 
+	# shellcheck disable=SC2086
 	manual_add_modules $modules
 }
 
@@ -512,11 +538,17 @@ auto_add_modules()
 			copy_modules_dir kernel/drivers/usb/musb
 			copy_modules_dir kernel/drivers/usb/renesas_usbhs
 			# and any extcon drivers for USB
-			modules="$modules extcon-usb-gpio"
+			modules="$modules extcon-usb-gpio extcon-usbc-cros-ec"
+			# Add the axp20x_usb_power power supply driver,
+			# required to initialize the USB host controllers
+			# on a number of armhf systems
+			modules="$modules axp20x_usb_power"
 
-			# Include all HID drivers unless we're sure they
-			# don't support keyboards.  hid-*ff covers various
-			# game controllers with force feedback.
+			# Include all keyboard drivers and all HID drivers
+			# unless we're sure they don't support keyboards.
+			# hid-*ff covers various game controllers with
+			# force feedback.
+			copy_modules_dir kernel/drivers/input/keyboard
 			copy_modules_dir kernel/drivers/hid \
 				'hid-*ff.ko' hid-a4tech.ko hid-cypress.ko \
 				hid-dr.ko hid-elecom.ko hid-gyration.ko \
@@ -530,6 +562,8 @@ auto_add_modules()
 				hid-speedlink.ko hid-tivo.ko hid-twinhan.ko \
 				hid-uclogic.ko hid-wacom.ko hid-waltop.ko \
 				hid-wiimote.ko hid-zydacron.ko
+			# needed to access keyboard on some ChromeOS devices
+			modules="$modules cros_ec_spi"
 
 			# Any of these might be needed by other drivers
 			copy_modules_dir kernel/drivers/bus
@@ -537,9 +571,11 @@ auto_add_modules()
 			copy_modules_dir kernel/drivers/gpio
 			copy_modules_dir kernel/drivers/i2c/busses
 			copy_modules_dir kernel/drivers/i2c/muxes
+			copy_modules_dir kernel/drivers/mfd
 			copy_modules_dir kernel/drivers/phy
 			copy_modules_dir kernel/drivers/pinctrl
 			copy_modules_dir kernel/drivers/regulator
+			copy_modules_dir kernel/drivers/spi
 			copy_modules_dir kernel/drivers/usb/phy
 
 			# Needed for periodic fsck
@@ -569,6 +605,7 @@ auto_add_modules()
 		block)
 			copy_modules_dir kernel/drivers/block
 			copy_modules_dir kernel/drivers/nvme
+			modules="$modules vmd"
 		;;
 		ubi)
 			modules="$modules deflate zlib lzo ubi ubifs"
@@ -591,46 +628,51 @@ auto_add_modules()
 		esac
 	done
 
+	# shellcheck disable=SC2086
 	manual_add_modules $modules
 }
 
-# 'depmod' only looks at symbol dependencies; there is no way for
-# modules to declare explicit dependencies through module information,
-# so dependencies on e.g. crypto providers are hidden.  Until this is
-# fixed, we need to handle those hidden dependencies.
+# 'depmod' only looks at symbol dependencies and the 'softdep' module
+# information field; there is no way for modules to declare weaker
+# dependencies (modules that *might* be needed at run-time) through
+# module information, Until this is fixed, we need to handle those
+# hidden dependencies.
 hidden_dep_add_modules()
 {
-	local modules=
-	for dep in "lib/libcrc32c crc32c" \
-			"fs/ubifs/ubifs deflate zlib lzo" \
-			"fs/btrfs/btrfs crc32c"; do
-		set -- $dep
-		if [ -f "${DESTDIR}/lib/modules/${version}/kernel/$1.ko" ]; then
-			shift
-			modules="$modules $@"
-		fi
-	done
-	manual_add_modules $modules
-}
-
-# mkinitramfs help message
-usage()
-{
-	cat >&2 << EOF
-
-Usage: ${0} [OPTION]... -o outfile [version]
-
-Options:
-  -c compress	Override COMPRESS setting in initramfs.conf.
-  -d confdir	Specify an alternative configuration directory.
-  -k		Keep temporary directory used to make the image.
-  -o outfile	Write to outfile.
-  -r root	Override ROOT setting in initramfs.conf.
-
-See mkinitramfs(8) for further details.
-EOF
-	exit 1
-
+	# shellcheck disable=SC2046
+	manual_add_modules $(
+		{
+			cat "${DESTDIR}/lib/modules/${version}/modules.builtin"
+			find "${DESTDIR}/lib/modules/${version}/kernel" -name '*.ko*'
+		} |
+		while read -r module; do
+			module="${module##*/}"
+			module="${module%%.*}"
+			case "$module" in
+			libcrc32c)
+				echo crc32c
+				;;
+			ubifs)
+				echo deflate zlib lzo
+				;;
+			btrfs)
+				echo crc32c
+				;;
+			mlx4_core)
+				echo mlx4_ib
+				;;
+			mlx5_core)
+				echo mlx5_ib
+				;;
+			i8042)
+				echo psmouse
+				;;
+			nvme)
+				echo vmd
+				;;
+			esac
+		done
+		)
 }
 
 # Find the source for a script file.  This is needed to work around
@@ -650,7 +692,7 @@ get_source()
 set_initlist()
 {
 	unset initlist
-	for si_x in ${initdir}/*; do
+	for si_x in "${initdir}"/*; do
 		# skip empty dirs without warning
 		[ "${si_x}" = "${initdir}/*" ] && return
 
@@ -664,7 +706,7 @@ set_initlist()
 		esac
 
 		# skip directories
-		if [ -d ${si_x} ]; then
+		if [ -d "${si_x}" ]; then
 			[ "${verbose}" = "y" ] \
 			&& echo "$si_x ignored: a directory" >&2
 			continue
@@ -673,14 +715,14 @@ set_initlist()
 		si_x="$(get_source "${si_x#${initdir}/}")"
 
 		# skip non executable scripts
-		if [ ! -x ${si_x} ]; then
+		if [ ! -x "${si_x}" ]; then
 			[ "${verbose}" = "y" ] \
 			&& echo "$si_x ignored: not executable" >&2
 			continue
 		fi
 
 		# skip bad syntax
-		if ! sh -n ${si_x} ; then
+		if ! sh -n "${si_x}" ; then
 			[ "${verbose}" = "y" ] \
 			&& echo "$si_x ignored: bad syntax" >&2
 			continue
@@ -694,11 +736,11 @@ get_prereq_pairs()
 {
 	set_initlist
 	for gp_x in ${initlist:-}; do
-		echo ${gp_x} ${gp_x}
-		gp_src="$(get_source $gp_x)"
+		echo "${gp_x} ${gp_x}"
+		gp_src="$(get_source "$gp_x")"
 		prereqs=$("${gp_src}" prereqs)
 		for prereq in ${prereqs}; do
-			echo ${prereq} ${gp_x}
+			echo "${prereq} ${gp_x}"
 		done
 	done
 }
@@ -709,14 +751,14 @@ cache_run_scripts()
 	DESTDIR=${1}
 	scriptdir=${2}
 	initdir=${DESTDIR}${scriptdir}
-	[ ! -d ${initdir} ] && return
+	[ ! -d "${initdir}" ] && return
 
-	> ${initdir}/ORDER
+	true > "${initdir}/ORDER"
 	runlist=$(get_prereq_pairs | tsort)
 	for crs_x in ${runlist}; do
-		[ -f ${initdir}/${crs_x} ] || continue
-		echo "${scriptdir}/${crs_x} \"\$@\"" >> ${initdir}/ORDER
-		echo "[ -e /conf/param.conf ] && . /conf/param.conf" >> ${initdir}/ORDER
+		[ -f "${initdir}/${crs_x}" ] || continue
+		echo "${scriptdir}/${crs_x} \"\$@\"" >> "${initdir}/ORDER"
+		echo "[ -e /conf/param.conf ] && . /conf/param.conf" >> "${initdir}/ORDER"
 	done
 }
 
@@ -724,15 +766,15 @@ call_scripts()
 {
 	set -e
 	for cs_x in ${runlist}; do
-		[ -f ${initdir}/${cs_x} ] || continue
+		[ -f "${initdir}/${cs_x}" ] || continue
 		# mkinitramfs verbose output
 		if [ "${verbose}" = "y" ]; then
 			echo "Calling hook ${cs_x}"
 		fi
-		${initdir}/${cs_x} && ec=$? || ec=$?
+		"${initdir}/${cs_x}" && ec=$? || ec=$?
 		# allow hooks to abort build:
 		if [ "$ec" -ne 0 ]; then
-			echo "E: ${initdir}/${cs_x} failed with return $ec."
+			echo "E: ${initdir}/${cs_x} failed with return $ec." >&2
 			# only errexit on mkinitramfs
 			[ -n "${version}" ] && exit $ec
 		fi
@@ -748,8 +790,8 @@ run_scripts()
 {
 	scriptdir=${2:-}
 	initdir=${1}
-	[ ! -d ${initdir} ] && return
+	[ ! -d "${initdir}" ] && return
 
 	runlist=$(get_prereq_pairs | tsort)
-	call_scripts $scriptdir
+	call_scripts "$scriptdir"
 }
diff --git a/usr/share/initramfs-tools/hooks/fsck b/usr/share/initramfs-tools/hooks/fsck
--- a/usr/share/initramfs-tools/hooks/fsck
+++ b/usr/share/initramfs-tools/hooks/fsck
@@ -7,14 +7,6 @@ prereqs()
 	echo "$PREREQ"
 }
 
-fstab_files()
-{
-	echo /etc/fstab
-	if [ -d /etc/fstab.d ]; then
-		ls -1 /etc/fstab.d | grep '\.fstab$' | sed -e 's;^;/etc/fstab.d/;'
-	fi
-}
-
 # Find a specific fstab entry
 # $1=mountpoint
 # $2=fstype (optional)
@@ -24,9 +16,10 @@ _read_fstab_entry () {
 	echo "MNT_DIR="
 	echo "MNT_TYPE="
 
-	fstab_files | while read file; do
+	for file in /etc/fstab /etc/fstab.d/*.fstab; do
 		if [ -f "$file" ]; then
-			while read MNT_FSNAME MNT_DIR MNT_TYPE MNT_OPTS MNT_FREQ MNT_PASS MNT_JUNK; do
+			# shellcheck disable=SC2034
+			while read -r MNT_FSNAME MNT_DIR MNT_TYPE MNT_OPTS MNT_FREQ MNT_PASS MNT_JUNK; do
 				case "$MNT_FSNAME" in
 				  ""|\#*)
 					continue;
@@ -59,9 +52,11 @@ get_fsck_type_fstab () {
 		# therefore never used at boot time
 		if [ "${MNT_DIR}" = "/" ] || [ "${MNT_TYPE}" = "auto" ]; then
 			MNT_FSNAME="$(resolve_device "${MNT_FSNAME}")"
-			alias fstype="/usr/lib/klibc/bin/fstype"
-			get_fstype "${MNT_FSNAME}"
-			unalias fstype
+			fstype() { "/usr/lib/klibc/bin/fstype" "$@"; }
+			if ! get_fstype "${MNT_FSNAME}"; then
+				echo "W: Couldn't identify type of $2 file system for fsck hook" >&2
+			fi
+			unset -f fstype
 		else
 			echo "${MNT_TYPE}"
 		fi
@@ -69,8 +64,8 @@ get_fsck_type_fstab () {
 }
 
 get_fsck_types() {
-	get_fsck_type_fstab /
-	get_fsck_type_fstab /usr
+	get_fsck_type_fstab /    root
+	get_fsck_type_fstab /usr /usr
 }
 
 case $1 in
@@ -97,14 +92,9 @@ copy_exec /sbin/fsck
 copy_exec /sbin/logsave
 
 for type in $fsck_types; do
-	if [ "$type" = "unknown" ] ; then
-		echo "Warning: couldn't identify filesystem type for fsck hook, ignoring."
-		continue
-	fi
-
-	if prog="$(command -v fsck.${type})"; then
+	if prog="$(command -v "fsck.${type}")"; then
 		copy_exec "$prog"
 	else
-		echo "Warning: /sbin/fsck.${type} doesn't exist, can't install to initramfs, ignoring."
+		echo "W: /sbin/fsck.${type} doesn't exist, can't install to initramfs" >&2
 	fi
 done
diff --git a/var/lib/dpkg/info/acpid.postinst b/var/lib/dpkg/info/acpid.postinst
--- a/var/lib/dpkg/info/acpid.postinst
+++ b/var/lib/dpkg/info/acpid.postinst
@@ -20,57 +20,68 @@ if dpkg --compare-versions "$2" lt-nl "1.0.10-5"; then
 	[ -f /var/log/acpid ] && chmod 640 /var/log/acpid*
 fi
 
-# Automatically added by dh_systemd_enable
-if deb-systemd-helper debian-installed acpid.service; then
-	# This will only remove masks created by d-s-h on package removal.
-	deb-systemd-helper unmask acpid.service >/dev/null || true
-
-	if deb-systemd-helper --quiet was-enabled acpid.service; then
-		# Create new symlinks, if any.
-		deb-systemd-helper enable acpid.service >/dev/null || true
-	fi
-fi
-
-# Update the statefile to add new symlinks (if any), which need to be cleaned
-# up on purge. Also remove old symlinks.
-deb-systemd-helper update-state acpid.service >/dev/null || true
-# End automatically added section
-# Automatically added by dh_systemd_enable
-# This will only remove masks created by d-s-h on package removal.
-deb-systemd-helper unmask acpid.socket >/dev/null || true
-
-# was-enabled defaults to true, so new installations run enable.
-if deb-systemd-helper --quiet was-enabled acpid.socket; then
-	# Enables the unit on first installation, creates new
-	# symlinks on upgrades if the unit file has changed.
-	deb-systemd-helper enable acpid.socket >/dev/null || true
-else
-	# Update the statefile to add new symlinks (if any), which need to be
-	# cleaned up on purge. Also remove old symlinks.
-	deb-systemd-helper update-state acpid.socket >/dev/null || true
-fi
-# End automatically added section
-# Automatically added by dh_systemd_enable
-# This will only remove masks created by d-s-h on package removal.
-deb-systemd-helper unmask acpid.path >/dev/null || true
-
-# was-enabled defaults to true, so new installations run enable.
-if deb-systemd-helper --quiet was-enabled acpid.path; then
-	# Enables the unit on first installation, creates new
-	# symlinks on upgrades if the unit file has changed.
-	deb-systemd-helper enable acpid.path >/dev/null || true
-else
-	# Update the statefile to add new symlinks (if any), which need to be
-	# cleaned up on purge. Also remove old symlinks.
-	deb-systemd-helper update-state acpid.path >/dev/null || true
-fi
-# End automatically added section
-# Automatically added by dh_installinit
-if [ "$1" = "configure" ] || [ "$1" = "abort-upgrade" ]; then
+# Automatically added by dh_installinit/11.5.3
+if [ "$1" = "configure" ] || [ "$1" = "abort-upgrade" ] || [ "$1" = "abort-deconfigure" ] || [ "$1" = "abort-remove" ] ; then
 	if [ -x "/etc/init.d/acpid" ]; then
 		update-rc.d acpid defaults >/dev/null
-		invoke-rc.d acpid start || exit $?
+		if [ -n "$2" ]; then
+			_dh_action=restart
+		else
+			_dh_action=start
+		fi
+		invoke-rc.d acpid $_dh_action || exit 1
 	fi
+fi
+# End automatically added section
+# Automatically added by dh_installsystemd/11.5.3
+if [ "$1" = "configure" ] || [ "$1" = "abort-upgrade" ] || [ "$1" = "abort-deconfigure" ] || [ "$1" = "abort-remove" ] ; then
+	if deb-systemd-helper debian-installed 'acpid.path'; then
+		# This will only remove masks created by d-s-h on package removal.
+		deb-systemd-helper unmask 'acpid.path' >/dev/null || true
+
+		if deb-systemd-helper --quiet was-enabled 'acpid.path'; then
+			# Create new symlinks, if any.
+			deb-systemd-helper enable 'acpid.path' >/dev/null || true
+		fi
+	fi
+
+	# Update the statefile to add new symlinks (if any), which need to be cleaned
+	# up on purge. Also remove old symlinks.
+	deb-systemd-helper update-state 'acpid.path' >/dev/null || true
+fi
+# End automatically added section
+# Automatically added by dh_installsystemd/11.5.3
+if [ "$1" = "configure" ] || [ "$1" = "abort-upgrade" ] || [ "$1" = "abort-deconfigure" ] || [ "$1" = "abort-remove" ] ; then
+	if deb-systemd-helper debian-installed 'acpid.service'; then
+		# This will only remove masks created by d-s-h on package removal.
+		deb-systemd-helper unmask 'acpid.service' >/dev/null || true
+
+		if deb-systemd-helper --quiet was-enabled 'acpid.service'; then
+			# Create new symlinks, if any.
+			deb-systemd-helper enable 'acpid.service' >/dev/null || true
+		fi
+	fi
+
+	# Update the statefile to add new symlinks (if any), which need to be cleaned
+	# up on purge. Also remove old symlinks.
+	deb-systemd-helper update-state 'acpid.service' >/dev/null || true
+fi
+# End automatically added section
+# Automatically added by dh_installsystemd/11.5.3
+if [ "$1" = "configure" ] || [ "$1" = "abort-upgrade" ] || [ "$1" = "abort-deconfigure" ] || [ "$1" = "abort-remove" ] ; then
+	if deb-systemd-helper debian-installed 'acpid.socket'; then
+		# This will only remove masks created by d-s-h on package removal.
+		deb-systemd-helper unmask 'acpid.socket' >/dev/null || true
+
+		if deb-systemd-helper --quiet was-enabled 'acpid.socket'; then
+			# Create new symlinks, if any.
+			deb-systemd-helper enable 'acpid.socket' >/dev/null || true
+		fi
+	fi
+
+	# Update the statefile to add new symlinks (if any), which need to be cleaned
+	# up on purge. Also remove old symlinks.
+	deb-systemd-helper update-state 'acpid.socket' >/dev/null || true
 fi
 # End automatically added section
 
diff --git a/var/lib/dpkg/info/alsa-utils.postinst b/var/lib/dpkg/info/alsa-utils.postinst
--- a/var/lib/dpkg/info/alsa-utils.postinst
+++ b/var/lib/dpkg/info/alsa-utils.postinst
@@ -1,20 +1,22 @@
 #!/bin/sh
 set -e
-# Automatically added by dh_installinit
-if [ "$1" = "configure" ] || [ "$1" = "abort-upgrade" ]; then
+# Automatically added by dh_installinit/12.1.1
+if [ "$1" = "configure" ] || [ "$1" = "abort-upgrade" ] || [ "$1" = "abort-deconfigure" ] || [ "$1" = "abort-remove" ] ; then
 	if [ -x "/etc/init.d/alsa-utils" ]; then
-		update-rc.d alsa-utils defaults >/dev/null || exit $?
+		update-rc.d alsa-utils defaults >/dev/null || exit 1
 	fi
 fi
 # End automatically added section
-# Automatically added by dh_systemd_start
-if [ -d /run/systemd/system ]; then
-	systemctl --system daemon-reload >/dev/null || true
-	if [ -n "$2" ]; then
-		_dh_action=try-restart
-	else
-		_dh_action=start
+# Automatically added by dh_installsystemd/12.1.1
+if [ "$1" = "configure" ] || [ "$1" = "abort-upgrade" ] || [ "$1" = "abort-deconfigure" ] || [ "$1" = "abort-remove" ] ; then
+	if [ -d /run/systemd/system ]; then
+		systemctl --system daemon-reload >/dev/null || true
+		if [ -n "$2" ]; then
+			_dh_action=restart
+		else
+			_dh_action=start
+		fi
+		deb-systemd-invoke $_dh_action 'alsa-restore.service' 'alsa-state.service' >/dev/null || true
 	fi
-	deb-systemd-invoke $_dh_action alsa-restore.service alsa-state.service >/dev/null || true
 fi
 # End automatically added section
diff --git a/var/lib/dpkg/info/apt.postinst b/var/lib/dpkg/info/apt.postinst
--- a/var/lib/dpkg/info/apt.postinst
+++ b/var/lib/dpkg/info/apt.postinst
@@ -79,48 +79,54 @@ esac
 # dh_installdeb will replace this with shell code automatically
 # generated by other debhelper scripts.
 
-# Automatically added by dh_systemd_enable
-# This will only remove masks created by d-s-h on package removal.
-deb-systemd-helper unmask apt-daily-upgrade.timer >/dev/null || true
+# Automatically added by dh_systemd_enable/12.1.1
+if [ "$1" = "configure" ] || [ "$1" = "abort-upgrade" ] || [ "$1" = "abort-deconfigure" ] || [ "$1" = "abort-remove" ] ; then
+	# This will only remove masks created by d-s-h on package removal.
+	deb-systemd-helper unmask 'apt-daily-upgrade.timer' >/dev/null || true
 
-# was-enabled defaults to true, so new installations run enable.
-if deb-systemd-helper --quiet was-enabled apt-daily-upgrade.timer; then
-	# Enables the unit on first installation, creates new
-	# symlinks on upgrades if the unit file has changed.
-	deb-systemd-helper enable apt-daily-upgrade.timer >/dev/null || true
-else
-	# Update the statefile to add new symlinks (if any), which need to be
-	# cleaned up on purge. Also remove old symlinks.
-	deb-systemd-helper update-state apt-daily-upgrade.timer >/dev/null || true
-fi
-# End automatically added section
-# Automatically added by dh_systemd_enable
-# This will only remove masks created by d-s-h on package removal.
-deb-systemd-helper unmask apt-daily.timer >/dev/null || true
-
-# was-enabled defaults to true, so new installations run enable.
-if deb-systemd-helper --quiet was-enabled apt-daily.timer; then
-	# Enables the unit on first installation, creates new
-	# symlinks on upgrades if the unit file has changed.
-	deb-systemd-helper enable apt-daily.timer >/dev/null || true
-else
-	# Update the statefile to add new symlinks (if any), which need to be
-	# cleaned up on purge. Also remove old symlinks.
-	deb-systemd-helper update-state apt-daily.timer >/dev/null || true
-fi
-# End automatically added section
-# Automatically added by dh_systemd_start
-if [ -d /run/systemd/system ]; then
-	systemctl --system daemon-reload >/dev/null || true
-	if [ -n "$2" ]; then
-		_dh_action=try-restart
+	# was-enabled defaults to true, so new installations run enable.
+	if deb-systemd-helper --quiet was-enabled 'apt-daily-upgrade.timer'; then
+		# Enables the unit on first installation, creates new
+		# symlinks on upgrades if the unit file has changed.
+		deb-systemd-helper enable 'apt-daily-upgrade.timer' >/dev/null || true
 	else
-		_dh_action=start
+		# Update the statefile to add new symlinks (if any), which need to be
+		# cleaned up on purge. Also remove old symlinks.
+		deb-systemd-helper update-state 'apt-daily-upgrade.timer' >/dev/null || true
 	fi
-	deb-systemd-invoke $_dh_action apt-daily-upgrade.timer apt-daily.timer >/dev/null || true
 fi
 # End automatically added section
-# Automatically added by dh_installdeb
+# Automatically added by dh_systemd_enable/12.1.1
+if [ "$1" = "configure" ] || [ "$1" = "abort-upgrade" ] || [ "$1" = "abort-deconfigure" ] || [ "$1" = "abort-remove" ] ; then
+	# This will only remove masks created by d-s-h on package removal.
+	deb-systemd-helper unmask 'apt-daily.timer' >/dev/null || true
+
+	# was-enabled defaults to true, so new installations run enable.
+	if deb-systemd-helper --quiet was-enabled 'apt-daily.timer'; then
+		# Enables the unit on first installation, creates new
+		# symlinks on upgrades if the unit file has changed.
+		deb-systemd-helper enable 'apt-daily.timer' >/dev/null || true
+	else
+		# Update the statefile to add new symlinks (if any), which need to be
+		# cleaned up on purge. Also remove old symlinks.
+		deb-systemd-helper update-state 'apt-daily.timer' >/dev/null || true
+	fi
+fi
+# End automatically added section
+# Automatically added by dh_systemd_start/12.1.1
+if [ "$1" = "configure" ] || [ "$1" = "abort-upgrade" ] || [ "$1" = "abort-deconfigure" ] || [ "$1" = "abort-remove" ] ; then
+	if [ -d /run/systemd/system ]; then
+		systemctl --system daemon-reload >/dev/null || true
+		if [ -n "$2" ]; then
+			_dh_action=restart
+		else
+			_dh_action=start
+		fi
+		deb-systemd-invoke $_dh_action 'apt-daily-upgrade.timer' 'apt-daily.timer' >/dev/null || true
+	fi
+fi
+# End automatically added section
+# Automatically added by dh_installdeb/12.1.1
 dpkg-maintscript-helper rm_conffile /etc/apt/apt.conf.d/20changelog 1.2.4\~ -- "$@"
 dpkg-maintscript-helper rm_conffile /etc/cron.daily/apt 1.2.10\~ -- "$@"
 # End automatically added section
diff --git a/var/lib/dpkg/info/console-setup-linux.postinst b/var/lib/dpkg/info/console-setup-linux.postinst
--- a/var/lib/dpkg/info/console-setup-linux.postinst
+++ b/var/lib/dpkg/info/console-setup-linux.postinst
@@ -1,61 +1,67 @@
 #!/bin/sh
 set -e
-# Automatically added by dh_systemd_enable
-# This will only remove masks created by d-s-h on package removal.
-deb-systemd-helper unmask keyboard-setup.service >/dev/null || true
+# Automatically added by dh_systemd_enable/12.1.1
+if [ "$1" = "configure" ] || [ "$1" = "abort-upgrade" ] || [ "$1" = "abort-deconfigure" ] || [ "$1" = "abort-remove" ] ; then
+	# This will only remove masks created by d-s-h on package removal.
+	deb-systemd-helper unmask 'keyboard-setup.service' >/dev/null || true
 
-# was-enabled defaults to true, so new installations run enable.
-if deb-systemd-helper --quiet was-enabled keyboard-setup.service; then
-	# Enables the unit on first installation, creates new
-	# symlinks on upgrades if the unit file has changed.
-	deb-systemd-helper enable keyboard-setup.service >/dev/null || true
-else
-	# Update the statefile to add new symlinks (if any), which need to be
-	# cleaned up on purge. Also remove old symlinks.
-	deb-systemd-helper update-state keyboard-setup.service >/dev/null || true
-fi
-# End automatically added section
-# Automatically added by dh_systemd_enable
-# This will only remove masks created by d-s-h on package removal.
-deb-systemd-helper unmask console-setup.service >/dev/null || true
-
-# was-enabled defaults to true, so new installations run enable.
-if deb-systemd-helper --quiet was-enabled console-setup.service; then
-	# Enables the unit on first installation, creates new
-	# symlinks on upgrades if the unit file has changed.
-	deb-systemd-helper enable console-setup.service >/dev/null || true
-else
-	# Update the statefile to add new symlinks (if any), which need to be
-	# cleaned up on purge. Also remove old symlinks.
-	deb-systemd-helper update-state console-setup.service >/dev/null || true
-fi
-# End automatically added section
-# Automatically added by dh_systemd_enable
-# This will only remove masks created by d-s-h on package removal.
-deb-systemd-helper unmask keyboard-setup.service >/dev/null || true
-
-# was-enabled defaults to true, so new installations run enable.
-if deb-systemd-helper --quiet was-enabled keyboard-setup.service; then
-	# Enables the unit on first installation, creates new
-	# symlinks on upgrades if the unit file has changed.
-	deb-systemd-helper enable keyboard-setup.service >/dev/null || true
-else
-	# Update the statefile to add new symlinks (if any), which need to be
-	# cleaned up on purge. Also remove old symlinks.
-	deb-systemd-helper update-state keyboard-setup.service >/dev/null || true
-fi
-# End automatically added section
-# Automatically added by dh_installinit
-if [ "$1" = "configure" ] || [ "$1" = "abort-upgrade" ]; then
-	if [ -x "/etc/init.d/keyboard-setup.sh" ]; then
-		update-rc.d keyboard-setup.sh defaults >/dev/null || exit $?
+	# was-enabled defaults to true, so new installations run enable.
+	if deb-systemd-helper --quiet was-enabled 'keyboard-setup.service'; then
+		# Enables the unit on first installation, creates new
+		# symlinks on upgrades if the unit file has changed.
+		deb-systemd-helper enable 'keyboard-setup.service' >/dev/null || true
+	else
+		# Update the statefile to add new symlinks (if any), which need to be
+		# cleaned up on purge. Also remove old symlinks.
+		deb-systemd-helper update-state 'keyboard-setup.service' >/dev/null || true
 	fi
 fi
 # End automatically added section
-# Automatically added by dh_installinit
-if [ "$1" = "configure" ] || [ "$1" = "abort-upgrade" ]; then
+# Automatically added by dh_systemd_enable/12.1.1
+if [ "$1" = "configure" ] || [ "$1" = "abort-upgrade" ] || [ "$1" = "abort-deconfigure" ] || [ "$1" = "abort-remove" ] ; then
+	# This will only remove masks created by d-s-h on package removal.
+	deb-systemd-helper unmask 'console-setup.service' >/dev/null || true
+
+	# was-enabled defaults to true, so new installations run enable.
+	if deb-systemd-helper --quiet was-enabled 'console-setup.service'; then
+		# Enables the unit on first installation, creates new
+		# symlinks on upgrades if the unit file has changed.
+		deb-systemd-helper enable 'console-setup.service' >/dev/null || true
+	else
+		# Update the statefile to add new symlinks (if any), which need to be
+		# cleaned up on purge. Also remove old symlinks.
+		deb-systemd-helper update-state 'console-setup.service' >/dev/null || true
+	fi
+fi
+# End automatically added section
+# Automatically added by dh_systemd_enable/12.1.1
+if [ "$1" = "configure" ] || [ "$1" = "abort-upgrade" ] || [ "$1" = "abort-deconfigure" ] || [ "$1" = "abort-remove" ] ; then
+	# This will only remove masks created by d-s-h on package removal.
+	deb-systemd-helper unmask 'keyboard-setup.service' >/dev/null || true
+
+	# was-enabled defaults to true, so new installations run enable.
+	if deb-systemd-helper --quiet was-enabled 'keyboard-setup.service'; then
+		# Enables the unit on first installation, creates new
+		# symlinks on upgrades if the unit file has changed.
+		deb-systemd-helper enable 'keyboard-setup.service' >/dev/null || true
+	else
+		# Update the statefile to add new symlinks (if any), which need to be
+		# cleaned up on purge. Also remove old symlinks.
+		deb-systemd-helper update-state 'keyboard-setup.service' >/dev/null || true
+	fi
+fi
+# End automatically added section
+# Automatically added by dh_installinit/12.1.1
+if [ "$1" = "configure" ] || [ "$1" = "abort-upgrade" ] || [ "$1" = "abort-deconfigure" ] || [ "$1" = "abort-remove" ] ; then
+	if [ -x "/etc/init.d/keyboard-setup.sh" ]; then
+		update-rc.d keyboard-setup.sh defaults >/dev/null || exit 1
+	fi
+fi
+# End automatically added section
+# Automatically added by dh_installinit/12.1.1
+if [ "$1" = "configure" ] || [ "$1" = "abort-upgrade" ] || [ "$1" = "abort-deconfigure" ] || [ "$1" = "abort-remove" ] ; then
 	if [ -x "/etc/init.d/console-setup.sh" ]; then
-		update-rc.d console-setup.sh defaults >/dev/null || exit $?
+		update-rc.d console-setup.sh defaults >/dev/null || exit 1
 	fi
 fi
 # End automatically added section
diff --git a/var/lib/dpkg/info/cron.postinst b/var/lib/dpkg/info/cron.postinst
--- a/var/lib/dpkg/info/cron.postinst
+++ b/var/lib/dpkg/info/cron.postinst
@@ -9,39 +9,6 @@ if [ "$action" != configure ]; then
 fi
 
 
-# LEGACY: This hasn't been relevant to Debian cron since the last Millenium,
-# but we keep it here to preserve the upgrade path... 
-# Copy existing allow/deny files
-pausemessage="F"
-for fname in allow deny ; do
-    if [ -f $crondir/$fname ] ; then
-	if [ ! -f $/etc/cron.$fname ] ; then
-	    mv $crondir/$fname /etc/cron.$fname
-	    echo " "
-	    echo "Moving $crondir/$fname to /etc/cron.$fname to comply with Debian policy"
-	    pausemessage="T"
-	else
-	    echo " "
-	    echo "Warning:"
-	    echo "Both $crondir/$fname and /etc/cron.$fname exist -- cron will"
-	    echo "use /etc/cron.$fname"
-	    pausemessage="T"
-	fi
-    fi
-done
-
-# Conffiles that are now obsolete
-dpkg-maintscript-helper rm_conffile /etc/cron.monthly/standard "3.0pl1-113" -- "$@"
-dpkg-maintscript-helper rm_conffile /etc/cron.daily/standard "3.0pl1-124" -- "$@"
-# If dpkg-maintscript-helper renames it instead of removing it because it has
-# local modifications, we must rename it back to a valid name, or crond
-# will not accept it. Thanks to Raphaël Hertzog for the tip.
-if [ -e /etc/cron.monthly/standard.dpkg-bak ]; then
-    mv /etc/cron.monthly/standard.dpkg-bak \
-        /etc/cron.monthly/standard-obsolete-please-verify-and-remove
-fi
-
-
 # Add group for crontabs
 getent group crontab > /dev/null 2>&1 || addgroup --system crontab
 
@@ -60,32 +27,76 @@ if [ -d $crondir/crontabs ] ; then
     # It has been disabled to suit cron alternative such as bcron. 
     cd $crondir/crontabs
     set +e
-    ls -1 | xargs -r -n 1 --replace=xxx  chown 'xxx:crontab' 'xxx'
-    ls -1 | xargs -r -n 1 chmod 600
+
+    # Iterate over each entry in the spool directory, perform some sanity
+    # checks (see CVE-2017-9525), and chown/chgroup the crontabs
+    for tab_name in *
+    do
+        [ "$tab_name" = "*" ] && continue
+        tab_links=`stat -c '%h' "$tab_name"`
+        tab_owner=`stat -c '%U' "$tab_name"`
+
+        if [ ! -f "$tab_name" ]
+        then
+            echo "Warning: $tab_name is not a regular file!"
+            continue
+        elif [ "$tab_links" -ne 1 ]
+        then
+            echo "Warning: $tab_name has more than one hard link!"
+            continue
+        elif [ "$tab_owner" != "$tab_name" ]
+        then
+            echo "Warning: $tab_name name differs from owner $tab_owner!"
+            continue
+        fi
+
+		chown "$tab_owner:crontab" "$tab_name"
+		chmod 600 "$tab_name"
+    done
     set -e
 fi
 
 
-# Automatically added by dh_systemd_enable
-# This will only remove masks created by d-s-h on package removal.
-deb-systemd-helper unmask cron.service >/dev/null || true
-
-# was-enabled defaults to true, so new installations run enable.
-if deb-systemd-helper --quiet was-enabled cron.service; then
-	# Enables the unit on first installation, creates new
-	# symlinks on upgrades if the unit file has changed.
-	deb-systemd-helper enable cron.service >/dev/null || true
-else
-	# Update the statefile to add new symlinks (if any), which need to be
-	# cleaned up on purge. Also remove old symlinks.
-	deb-systemd-helper update-state cron.service >/dev/null || true
+# Automatically added by dh_installinit/12.1.1
+if [ "$1" = "configure" ] || [ "$1" = "abort-upgrade" ] || [ "$1" = "abort-deconfigure" ] || [ "$1" = "abort-remove" ] ; then
+	if [ -x "/etc/init.d/cron" ]; then
+		update-rc.d cron defaults >/dev/null
+		if [ -n "$2" ]; then
+			_dh_action=restart
+		else
+			_dh_action=start
+		fi
+		invoke-rc.d --skip-systemd-native cron $_dh_action || exit 1
+	fi
 fi
 # End automatically added section
-# Automatically added by dh_installinit
-if [ "$1" = "configure" ] || [ "$1" = "abort-upgrade" ]; then
-	if [ -x "/etc/init.d/cron" ]; then
-		update-rc.d cron start 89 2 3 4 5 . >/dev/null
-		invoke-rc.d cron start || exit $?
+# Automatically added by dh_installsystemd/12.1.1
+if [ "$1" = "configure" ] || [ "$1" = "abort-upgrade" ] || [ "$1" = "abort-deconfigure" ] || [ "$1" = "abort-remove" ] ; then
+	# This will only remove masks created by d-s-h on package removal.
+	deb-systemd-helper unmask 'cron.service' >/dev/null || true
+
+	# was-enabled defaults to true, so new installations run enable.
+	if deb-systemd-helper --quiet was-enabled 'cron.service'; then
+		# Enables the unit on first installation, creates new
+		# symlinks on upgrades if the unit file has changed.
+		deb-systemd-helper enable 'cron.service' >/dev/null || true
+	else
+		# Update the statefile to add new symlinks (if any), which need to be
+		# cleaned up on purge. Also remove old symlinks.
+		deb-systemd-helper update-state 'cron.service' >/dev/null || true
+	fi
+fi
+# End automatically added section
+# Automatically added by dh_installsystemd/12.1.1
+if [ "$1" = "configure" ] || [ "$1" = "abort-upgrade" ] || [ "$1" = "abort-deconfigure" ] || [ "$1" = "abort-remove" ] ; then
+	if [ -d /run/systemd/system ]; then
+		systemctl --system daemon-reload >/dev/null || true
+		if [ -n "$2" ]; then
+			_dh_action=restart
+		else
+			_dh_action=start
+		fi
+		deb-systemd-invoke $_dh_action 'cron.service' >/dev/null || true
 	fi
 fi
 # End automatically added section
diff --git a/var/lib/dpkg/info/cups-daemon.postinst b/var/lib/dpkg/info/cups-daemon.postinst
--- a/var/lib/dpkg/info/cups-daemon.postinst
+++ b/var/lib/dpkg/info/cups-daemon.postinst
@@ -32,26 +32,6 @@ if [ "$1" = configure ]; then
 	fi
     fi
 
-    # symlink snakeoil SSL certificate if present
-    if [ -e /etc/ssl/certs/ssl-cert-snakeoil.pem -a \
-	  -e /etc/ssl/private/ssl-cert-snakeoil.key -a \
-	  -n "`getent group ssl-cert`" -a ! -e /etc/cups/ssl/server.crt \
-	  -a ! -e /etc/cups/ssl/server.key -a ! -h /etc/cups/ssl/server.crt \
-	  -a ! -h /etc/cups/ssl/server.key ]; then
-	 ln -s /etc/ssl/certs/ssl-cert-snakeoil.pem /etc/cups/ssl/server.crt
-	 ln -s /etc/ssl/private/ssl-cert-snakeoil.key /etc/cups/ssl/server.key
-    fi
-
-    # Clear cache if we upgrade to 1.4.x
-    if dpkg --compare-versions "$2" lt-nl "1.4.1-5"; then
-	rm /var/cache/cups/* 2> /dev/null || :
-    fi
-
-    # Clear PPD cache if we upgrade to 1.5.x
-    if dpkg --compare-versions "$2" lt-nl "1.5.0-3"; then
-	rm /var/cache/cups/ppds.dat 2> /dev/null || :
-    fi
-
     # Manage printcap file and associated symlinks
     if [ -e /etc/cups/cupsd.conf ]; then
 	if [ -e /etc/printcap.cups ]; then
@@ -63,7 +43,7 @@ if [ "$1" = configure ]; then
 
 	printcap_file=`egrep '^Printcap ' /etc/cups/cupsd.conf | awk '{print $2}' | tail -n 1`
 	if [ -z "$printcap_file" ]; then
-	    printcap_file=/var/run/cups/printcap
+	    printcap_file=/run/cups/printcap
 	fi
 	if [ ! -e /etc/printcap -a -e $printcap_file ]; then
 	    ln -s $printcap_file /etc/printcap
@@ -72,83 +52,11 @@ if [ "$1" = configure ]; then
 
     # Create default cupsd.conf if it doesn't exist
     if [ ! -r /etc/cups/cupsd.conf ]; then
-        if dpkg --compare-versions "$2" le "1.6.1" && [ -e /etc/cups/cupsd.conf.conffile-bak ]; then
-            # Move cupsd.conf back as it is now a non-conffile
-            mv /etc/cups/cupsd.conf.conffile-bak /etc/cups/cupsd.conf
-        else
-            cp /usr/share/cups/cupsd.conf.default /etc/cups/cupsd.conf
-        fi
-    fi
-
-    # Remove lines from cupsd.conf which got obsolete in CUPS 1.6.x and would
-    # prevent the CUPS daemon from starting due to being invalid now.
-    if dpkg --compare-versions "$2" le "1.6.4"; then
-        # Backup pre-1.6 cupsd.conf for cups-browsed upgrade path
-        cp /etc/cups/cupsd.conf /etc/cups/cupsd.conf.pre16-bak
-
-        cat /etc/cups/cupsd.conf | grep -Eiv '^\s*Browse(Order|Allow|Deny|Poll|RemoteProtocols)' > /etc/cups/cupsd.conf.new
-        if [ -r /etc/cups/cupsd.conf.new ]; then
-            if ! diff -q /etc/cups/cupsd.conf /etc/cups/cupsd.conf.new > /dev/null 2>&1; then
-                mv -f /etc/cups/cupsd.conf.new /etc/cups/cupsd.conf
-            else
-                rm /etc/cups/cupsd.conf.new
-            fi
-        fi
-        # Also the argument "cups" for BrowseLocalProtocols is obsolete. Remove the
-        # argument and put "dnssd" if there are no arguments left.
-        cat /etc/cups/cupsd.conf | perl -p -e 's/^(\s*BrowseLocalProtocols.*?)\s+cups/$1/i; s/^(\s*BrowseLocalProtocols)(\s*)$/$1 dnssd$2/i' > /etc/cups/cupsd.conf.new
-        if [ -r /etc/cups/cupsd.conf.new ]; then
-            if ! diff -q /etc/cups/cupsd.conf /etc/cups/cupsd.conf.new > /dev/null 2>&1; then
-                mv -f /etc/cups/cupsd.conf.new /etc/cups/cupsd.conf
-            else
-                rm /etc/cups/cupsd.conf.new
-            fi
-        fi
-    fi
-
-    if dpkg --compare-versions "$2" le "1.7.1-9~" && [ -x "`which logrotate 2>/dev/null`" ]; then
-        rotatemax=$(grep '^\s*rotate' /etc/logrotate.d/cups-daemon | sed -e 's/^\s*rotate\s*\(\d*\)/\1/g')
-        for logfiletype in access_log error_log cups-pdf_log error_log page_log; do
-            for biggest_non_gzipped in $(seq $rotatemax -1 1); do
-                if [ -f /var/log/cups/$logfiletype.$biggest_non_gzipped ]; then
-                    max=$((rotatemax-biggest_non_gzipped))
-                    for i in $(seq 1 $max); do
-                        new=$((i+biggest_non_gzipped))
-                        if [ -f /var/log/cups/$logfiletype.$i.gz ]; then
-                            mv /var/log/cups/$logfiletype.$i.gz /var/log/cups/$logfiletype.$new.gz
-                        fi
-                    done
-                    for i in $(seq 1 $biggest_non_gzipped); do
-                        if [ -f /var/log/cups/$logfiletype.$i ]; then
-                          gzip -f /var/log/cups/$logfiletype.$i
-                        fi
-                    done
-                    break;
-                fi
-            done
-        done
-    fi
-
-    # Remove cups.path leftover symlink
-    if dpkg --compare-versions "$2" lt "1.7.4-3~" ; then
-        rm -f /etc/systemd/system/multi-user.target.wants/cups.path
+        cp /usr/share/cups/cupsd.conf.default /etc/cups/cupsd.conf
     fi
 fi
 
-# Automatically added by dh_apparmor
-aa_is_enabled() {
-   if command aa-enabled >/dev/null 2>&1; then
-      # apparmor >= 2.10.95-2
-      aa-enabled --quiet 2>/dev/null
-   else
-      # apparmor << 2.10.95-2
-      # (This should be removed once Debian Stretch and Ubuntu 18.04 are out.)
-      rc=0
-      aa-status --enabled 2>/dev/null || rc=$?
-      [ "$rc" = 0 ] || [ "$rc" = 2 ]
-   fi
-}
-
+# Automatically added by dh_apparmor/2.13.2-10
 if [ "$1" = "configure" ]; then
     APP_PROFILE="/etc/apparmor.d/usr.sbin.cupsd"
     if [ -f "$APP_PROFILE" ]; then
@@ -156,84 +64,85 @@ if [ "$1" = "configure" ]; then
         LOCAL_APP_PROFILE="/etc/apparmor.d/local/usr.sbin.cupsd"
 
         test -e "$LOCAL_APP_PROFILE" || {
-            tmp=`mktemp`
-        cat <<EOM > "$tmp"
-# Site-specific additions and overrides for usr.sbin.cupsd.
-# For more details, please see /etc/apparmor.d/local/README.
-EOM
-            mkdir `dirname "$LOCAL_APP_PROFILE"` 2>/dev/null || true
-            mv -f "$tmp" "$LOCAL_APP_PROFILE"
-            chmod 644 "$LOCAL_APP_PROFILE"
+            mkdir -p `dirname "$LOCAL_APP_PROFILE"`
+            install --mode 644 /dev/null "$LOCAL_APP_PROFILE"
         }
 
         # Reload the profile, including any abstraction updates
-        if aa_is_enabled; then
+        if aa-enabled --quiet 2>/dev/null; then
             apparmor_parser -r -T -W "$APP_PROFILE" || true
         fi
     fi
 fi
 # End automatically added section
-# Automatically added by dh_systemd_enable
-# This will only remove masks created by d-s-h on package removal.
-deb-systemd-helper unmask cups.path >/dev/null || true
+# Automatically added by dh_systemd_enable/12.1.1
+if [ "$1" = "configure" ] || [ "$1" = "abort-upgrade" ] || [ "$1" = "abort-deconfigure" ] || [ "$1" = "abort-remove" ] ; then
+	# This will only remove masks created by d-s-h on package removal.
+	deb-systemd-helper unmask 'cups.path' >/dev/null || true
 
-# was-enabled defaults to true, so new installations run enable.
-if deb-systemd-helper --quiet was-enabled cups.path; then
-	# Enables the unit on first installation, creates new
-	# symlinks on upgrades if the unit file has changed.
-	deb-systemd-helper enable cups.path >/dev/null || true
-else
-	# Update the statefile to add new symlinks (if any), which need to be
-	# cleaned up on purge. Also remove old symlinks.
-	deb-systemd-helper update-state cups.path >/dev/null || true
-fi
-# End automatically added section
-# Automatically added by dh_systemd_enable
-# This will only remove masks created by d-s-h on package removal.
-deb-systemd-helper unmask cups.service >/dev/null || true
-
-# was-enabled defaults to true, so new installations run enable.
-if deb-systemd-helper --quiet was-enabled cups.service; then
-	# Enables the unit on first installation, creates new
-	# symlinks on upgrades if the unit file has changed.
-	deb-systemd-helper enable cups.service >/dev/null || true
-else
-	# Update the statefile to add new symlinks (if any), which need to be
-	# cleaned up on purge. Also remove old symlinks.
-	deb-systemd-helper update-state cups.service >/dev/null || true
-fi
-# End automatically added section
-# Automatically added by dh_systemd_enable
-# This will only remove masks created by d-s-h on package removal.
-deb-systemd-helper unmask cups.socket >/dev/null || true
-
-# was-enabled defaults to true, so new installations run enable.
-if deb-systemd-helper --quiet was-enabled cups.socket; then
-	# Enables the unit on first installation, creates new
-	# symlinks on upgrades if the unit file has changed.
-	deb-systemd-helper enable cups.socket >/dev/null || true
-else
-	# Update the statefile to add new symlinks (if any), which need to be
-	# cleaned up on purge. Also remove old symlinks.
-	deb-systemd-helper update-state cups.socket >/dev/null || true
-fi
-# End automatically added section
-# Automatically added by dh_installinit
-if [ "$1" = "configure" ] || [ "$1" = "abort-upgrade" ]; then
-	if [ -x "/etc/init.d/cups" ]; then
-		update-rc.d cups defaults >/dev/null
-		invoke-rc.d cups start || exit $?
+	# was-enabled defaults to true, so new installations run enable.
+	if deb-systemd-helper --quiet was-enabled 'cups.path'; then
+		# Enables the unit on first installation, creates new
+		# symlinks on upgrades if the unit file has changed.
+		deb-systemd-helper enable 'cups.path' >/dev/null || true
+	else
+		# Update the statefile to add new symlinks (if any), which need to be
+		# cleaned up on purge. Also remove old symlinks.
+		deb-systemd-helper update-state 'cups.path' >/dev/null || true
 	fi
 fi
 # End automatically added section
-# Automatically added by dh_installdeb
-dpkg-maintscript-helper rm_conffile /etc/cups/cupsd.conf.default 1.7.1-3~ -- "$@"
+# Automatically added by dh_systemd_enable/12.1.1
+if [ "$1" = "configure" ] || [ "$1" = "abort-upgrade" ] || [ "$1" = "abort-deconfigure" ] || [ "$1" = "abort-remove" ] ; then
+	# This will only remove masks created by d-s-h on package removal.
+	deb-systemd-helper unmask 'cups.service' >/dev/null || true
+
+	# was-enabled defaults to true, so new installations run enable.
+	if deb-systemd-helper --quiet was-enabled 'cups.service'; then
+		# Enables the unit on first installation, creates new
+		# symlinks on upgrades if the unit file has changed.
+		deb-systemd-helper enable 'cups.service' >/dev/null || true
+	else
+		# Update the statefile to add new symlinks (if any), which need to be
+		# cleaned up on purge. Also remove old symlinks.
+		deb-systemd-helper update-state 'cups.service' >/dev/null || true
+	fi
+fi
 # End automatically added section
-# Automatically added by dh_installdeb
-dpkg-maintscript-helper rm_conffile /etc/default/cups 1.7.1-6~ -- "$@"
+# Automatically added by dh_systemd_enable/12.1.1
+if [ "$1" = "configure" ] || [ "$1" = "abort-upgrade" ] || [ "$1" = "abort-deconfigure" ] || [ "$1" = "abort-remove" ] ; then
+	# This will only remove masks created by d-s-h on package removal.
+	deb-systemd-helper unmask 'cups.socket' >/dev/null || true
+
+	# was-enabled defaults to true, so new installations run enable.
+	if deb-systemd-helper --quiet was-enabled 'cups.socket'; then
+		# Enables the unit on first installation, creates new
+		# symlinks on upgrades if the unit file has changed.
+		deb-systemd-helper enable 'cups.socket' >/dev/null || true
+	else
+		# Update the statefile to add new symlinks (if any), which need to be
+		# cleaned up on purge. Also remove old symlinks.
+		deb-systemd-helper update-state 'cups.socket' >/dev/null || true
+	fi
+fi
 # End automatically added section
-# Automatically added by dh_installdeb
-dpkg-maintscript-helper mv_conffile /etc/pam.d/cups-daemon /etc/pam.d/cups 1.7.3-2~ -- "$@"
+# Automatically added by dh_installdeb/12.1.1
+dpkg-maintscript-helper rm_conffile /etc/cups/cupsd.conf.default 1.7.1-3\~ -- "$@"
+dpkg-maintscript-helper rm_conffile /etc/default/cups 1.7.1-6\~ -- "$@"
+dpkg-maintscript-helper mv_conffile /etc/pam.d/cups-daemon /etc/pam.d/cups 1.7.3-2\~ -- "$@"
+# End automatically added section
+# Automatically added by dh_installinit/12.1.1
+if [ "$1" = "configure" ] || [ "$1" = "abort-upgrade" ] || [ "$1" = "abort-deconfigure" ] || [ "$1" = "abort-remove" ] ; then
+	if [ -x "/etc/init.d/cups" ]; then
+		update-rc.d cups defaults >/dev/null
+		if [ -n "$2" ]; then
+			_dh_action=restart
+		else
+			_dh_action=start
+		fi
+		invoke-rc.d cups $_dh_action || exit 1
+	fi
+fi
 # End automatically added section
 
 
diff --git a/var/lib/dpkg/info/dbus.postinst b/var/lib/dpkg/info/dbus.postinst
--- a/var/lib/dpkg/info/dbus.postinst
+++ b/var/lib/dpkg/info/dbus.postinst
@@ -26,7 +26,7 @@ fi
 if [ "$1" = configure ]; then
     adduser --system \
             --quiet \
-            --home "$MESSAGEHOME" \
+            --home /nonexistent \
             --no-create-home \
             --disabled-password \
             --group "$MESSAGEUSER"
@@ -69,41 +69,39 @@ if [ "$1" = configure ] && [ -n "$2" ]; then
             /usr/share/update-notifier/notify-reboot-required || true
     fi
 
-    # Create a symlink from the old bus setup to the new locations, so that
-    # dbus-daemon (<< 1.9.18) can reload successfully even though dbus
-    # does not support re-exec'ing itself. These are deliberately not
-    # conffiles so that they won't interfere with us removing the old
-    # conffile or moving it out of the way.
-    #
-    # Keep this until upgrades from versions << 1.9.18 are no longer
-    # supported (it can be removed after Debian 9 is released). It is not
-    # conditional on the version in $2, because we could conceivably
-    # have upgraded 1.8.x -> 1.10.0-1 -> 1.10.0-4 without an intervening
-    # reboot.
-    ln -fns /usr/share/dbus-1/session.conf /etc/dbus-1/session.conf
-    ln -fns /usr/share/dbus-1/system.conf /etc/dbus-1/system.conf
+    # Clean up old compatibility symlinks that were used to upgrade from
+    # Debian 8 to Debian 9. This can be dropped after Debian 10 is released.
+    for bus in system session; do
+        conf="/etc/dbus-1/${bus}.conf"
+        exp_target="/usr/share/dbus-1/${bus}.conf"
+        target="$(readlink -f "${conf}")" || continue
+
+        if [ -h "${conf}" ] && [ "_${target}" = "_${exp_target}" ]; then
+            rm -f "${conf}"
+        fi
+    done
 fi
 
-# Automatically added by dh_installinit
-if [ "$1" = "configure" ] || [ "$1" = "abort-upgrade" ]; then
+# Automatically added by dh_installsystemd/12.1.1
+if [ "$1" = "configure" ] || [ "$1" = "abort-upgrade" ] || [ "$1" = "abort-deconfigure" ] || [ "$1" = "abort-remove" ] ; then
 	# In case this system is running systemd, we need to ensure that all
 	# necessary tmpfiles (if any) are created before starting.
 	if [ -d /run/systemd/system ] ; then
-		systemd-tmpfiles --create /usr/lib/tmpfiles.d/dbus.conf >/dev/null || true
+		systemd-tmpfiles --create dbus.conf >/dev/null || true
 	fi
 fi
 # End automatically added section
-# Automatically added by dh_installinit
-if [ "$1" = "configure" ] || [ "$1" = "abort-upgrade" ]; then
-	if [ -x "/etc/init.d/dbus" ]; then
-		update-rc.d dbus defaults >/dev/null
-		invoke-rc.d dbus start || exit $?
-	fi
-fi
-# End automatically added section
-# Automatically added by dh_installdeb
+# Automatically added by dh_installdeb/12.1.1
 dpkg-maintscript-helper rm_conffile /etc/dbus-1/session.conf 1.10.0-4\~ dbus -- "$@"
 dpkg-maintscript-helper rm_conffile /etc/dbus-1/system.conf 1.10.0-4\~ dbus -- "$@"
+# End automatically added section
+# Automatically added by dh_installinit/12.1.1
+if [ "$1" = "configure" ] || [ "$1" = "abort-upgrade" ] || [ "$1" = "abort-deconfigure" ] || [ "$1" = "abort-remove" ] ; then
+	if [ -x "/etc/init.d/dbus" ]; then
+		update-rc.d dbus defaults >/dev/null
+		invoke-rc.d dbus start || exit 1
+	fi
+fi
 # End automatically added section
 
 
diff --git a/var/lib/dpkg/info/kmod.postinst b/var/lib/dpkg/info/kmod.postinst
--- a/var/lib/dpkg/info/kmod.postinst
+++ b/var/lib/dpkg/info/kmod.postinst
@@ -58,10 +58,10 @@ case "$1" in
   convert_etc_modules "$@"
 esac
 
-# Automatically added by dh_installinit
-if [ "$1" = "configure" ] || [ "$1" = "abort-upgrade" ]; then
+# Automatically added by dh_installinit/12
+if [ "$1" = "configure" ] || [ "$1" = "abort-upgrade" ] || [ "$1" = "abort-deconfigure" ] || [ "$1" = "abort-remove" ] ; then
 	if [ -x "/etc/init.d/kmod" ]; then
-		update-rc.d kmod defaults >/dev/null || exit $?
+		update-rc.d kmod defaults >/dev/null || exit 1
 	fi
 fi
 # End automatically added section
diff --git a/var/lib/dpkg/info/libc6:i386.postinst b/var/lib/dpkg/info/libc6:i386.postinst
--- a/var/lib/dpkg/info/libc6:i386.postinst
+++ b/var/lib/dpkg/info/libc6:i386.postinst
@@ -5,51 +5,6 @@ export LC_ALL=C
 type=$1
 preversion=$2
 
-# element() is a helper function for file-rc:
-element() {
-    local element list IFS
-
-    element="$1"
-
-    [ "$2" = "in" ] && shift
-    list="$2"
-    [ "$list" = "-" ] && return 1
-    [ "$list" = "*" ] && return 0
-
-    IFS=","
-    set -- $list
-    case $element in
-	"$1"|"$2"|"$3"|"$4"|"$5"|"$6"|"$7"|"$8"|"$9")
-	    return 0
-    esac
-    return 1
-}
-
-# filerc (runlevel, service) returns /etc/init.d/service, if service is
-# running in $runlevel:
-filerc() {
-    local runlevel basename
-    runlevel=$1
-    basename=$2
-    while read LINE
-    do
-	case $LINE in
-	    \#*|"") continue
-	esac
-
-	set -- $LINE
-	SORT_NO="$1"; STOP="$2"; START="$3"; CMD="$4"
-	[ "$CMD" = "/etc/init.d/$basename" ] || continue
-
-	if element "$runlevel" in "$START" || element "S" in "$START"
-	then
-	    echo "/etc/init.d/$basename"
-	    return 0
-	fi
-    done < /etc/runlevel.conf
-    echo ""
-}
-
 checkpkgver () {
     local status pkg
     pkg=$1
@@ -74,9 +29,9 @@ then
     # all optimized packages. Due to multiarch, this has to be done
     # independently of the architecture of the package.
     all_upgraded=yes
-    for pkg in libc6.1-alphaev67 libc6-i686 libc6-xen libc0.1-i686 ; do
+    for pkg in libc6.1-alphaev67 libc6-xen ; do
         ver=$(dpkg-query -l $pkg 2>/dev/null | sed -e '/^[a-z][a-z]\s/!d;/^.[nc]/d;' -e "s/^..\s\+$pkg[0-9a-z:]*\s\+//;s/\s.*//g")
-        if [ -n "$ver" ] && [ "$ver" != "2.24-11+deb9u4" ]; then
+        if [ -n "$ver" ] && [ "$ver" != "2.28-10" ]; then
             all_upgraded=no
         fi
     done
@@ -95,7 +50,7 @@ then
     fi
 
     if [ -n "$preversion" ] && [ -x "$(which ischroot)" ] && ! ischroot; then
-	if dpkg --compare-versions "$preversion" lt 2.24; then
+	if dpkg --compare-versions "$preversion" lt 2.28; then
 	    check="apache2.2-common apache apache-ssl apache-perl autofs at"
 	    check="$check boa cucipop courier-authdaemon cron cups exim"
 	    check="$check exim4-base dovecot-common cucipop incron lprng lpr"
@@ -110,37 +65,26 @@ then
 	    check=$(dpkg -s $check 2> /dev/null | egrep '^Package:|^Status:' | awk '{if ($1 ~ /^Package:/) { package=$2 } else if ($0 ~ /^Status: .* installed$/) { print package }}')
 	    # some init scripts don't match the package names
 	    check=$(echo $check | \
-	    	    sed -e's/\bapache2.2-common\b/apache2/g' \
-	    	    	-e's/\bat\b/atd/g' \
-	    	    	-e's/\bdovecot-common\b/dovecot/g' \
-	    	    	-e's/\bexim4-base\b/exim4/g' \
-	    	    	-e's/\blpr\b/lpd/g' \
-	    	    	-e's/\blpr-ppd\b/lpd-ppd/g' \
-	    	    	-e's/\bmysql-server\b/mysql/g' \
-	    	    	-e's/\bsasl2-bin\b/saslauthd/g' \
-	    	    	-e's/\bpostgresql-common\b/postgresql/g' \
-	    )
+		    sed -e's/\bapache2.2-common\b/apache2/g' \
+			-e's/\bat\b/atd/g' \
+			-e's/\bdovecot-common\b/dovecot/g' \
+			-e's/\bexim4-base\b/exim4/g' \
+			-e's/\blpr\b/lpd/g' \
+			-e's/\blpr-ppd\b/lpd-ppd/g' \
+			-e's/\bmysql-server\b/mysql/g' \
+			-e's/\bsasl2-bin\b/saslauthd/g' \
+			-e's/\bsamba\b/smbd/g' \
+			-e's/\bpostgresql-common\b/postgresql/g' \
+		    )
 	    echo
 	    echo "Checking init scripts..."
-	    rl=$(runlevel | sed 's/.*\ //')
 	    for service in $check; do
-	    	if [ -x "`which invoke-rc.d 2>/dev/null`" ]; then
-	    	    invoke-rc.d ${service} status >/dev/null 2>/dev/null && status=0 || status=$?
-	    	    if [ "$status" = "0" ] || [ "$status" = "2" ] ; then
-	    	    	services="$service $services"
-	    	    elif [ "$status" = "100" ] ; then
-	    	    	echo "WARNING: init script for $service not found."
-	    	    fi
-	    	else
-	    	    if [ -f /usr/share/file-rc/rc ] || [ -f /usr/lib/file-rc/rc ] && [ -f /etc/runlevel.conf ]; then
-	    	    	idl=$(filerc $rl $service)
-	    	    else
-	    	    	idl=$(ls /etc/rc${rl}.d/S??${service} 2> /dev/null | head -1)
-	    	    fi
-	    	    if [ -n "$idl" ] && [ -x $idl ]; then
-	    	    	services="$service $services"
-	    	    fi
-	    	fi
+		invoke-rc.d ${service} status >/dev/null 2>/dev/null && status=0 || status=$?
+		if [ "$status" = "0" ] || [ "$status" = "2" ] ; then
+		    services="$service $services"
+		elif [ "$status" = "100" ] ; then
+		    echo "WARNING: init script for $service not found."
+		fi
 	    done
 
 	    if [ -n "$services" ]; then
@@ -197,24 +141,10 @@ then
 		    echo "Restarting services possibly affected by the upgrade:"
 		    failed=""
 		    for service in $services; do
-			# We can't just use a generic rewrite here, as it was
-			# samba in wheezy and smbd in jessie, which confuses.
-			if [ "$service" = "samba" ]; then
-			    if [ -x /etc/init.d/smbd ] || [ -f /etc/init/smbd ]; then
-				service="smbd"
-			    fi
-			fi
-		    	if [ -x "`which invoke-rc.d 2>/dev/null`" ]; then
-			    idl="invoke-rc.d ${service}"
-			elif [ -f /usr/share/file-rc/rc ] || [ -f /usr/lib/file-rc/rc ] && [ -f /etc/runlevel.conf ]; then
-			    idl=$(filerc $rl $service)
-			else
-			    idl=$(ls /etc/rc${rl}.d/S??${service} 2> /dev/null | head -1)
-			fi
 			case "$service" in
 			    gdm)
 				echo -n "  $service: reloading..."
-				if $idl reload > /dev/null 2>&1; then
+				if invoke-rc.d ${service} reload > /dev/null 2>&1; then
 				    echo "done."
 				else
 				    echo "FAILED! ($?)"
@@ -223,7 +153,7 @@ then
 				;;
 			    *)
 				echo -n "  $service: restarting..."
-				if $idl restart > /dev/null 2>&1; then
+				if invoke-rc.d ${service} restart > /dev/null 2>&1; then
 				    echo "done."
 				else
 				    echo "FAILED! ($?)"
@@ -242,7 +172,7 @@ then
 			else
 			    echo "The following services failed to start: $failed"
 			    echo
-			    echo "You will need to start these manually by running \`/etc/init.d/<service> start'"
+			    echo "You will need to start these manually by running \`invoke-rc.d <service> start'"
 			    echo "If the service still fails to start, you may need to file a bug on"
 			    echo "${DPKG_MAINTSCRIPT_PACKAGE}:${DPKG_MAINTSCRIPT_ARCH} or the service involved."
 			    frontend=`echo "$DEBIAN_FRONTEND" | tr '[:upper:]' '[:lower:]'`
@@ -264,7 +194,7 @@ then
 	    else
 		echo "Nothing to restart."
 	    fi
-	fi # end upgrading and $preversion lt 2.24
+	fi # end upgrading and $preversion lt 2.28
     fi # Upgrading
 
     # Restart init.  Currently handles chroots, systemd and upstart, and
@@ -290,21 +220,6 @@ then
         telinit u 2>/dev/null || true ; sleep 1
     fi
 fi
-
-# We now use the multiarch triplet instead of the GNU triplet for the ld.so
-# configuration file, in order to keep a stable path. Remove the old file.
-case ${DPKG_MAINTSCRIPT_ARCH:-$(dpkg --print-architecture)} in
-    hurd-i386)
-        dpkg-maintscript-helper rm_conffile /etc/ld.so.conf.d/i486-gnu.conf 2.19-11~ libc0.3:hurd-i386 -- "$@"
-        dpkg-maintscript-helper rm_conffile /etc/ld.so.conf.d/i486-gnu-gnu.conf 2.19-11~ libc0.3:hurd-i386 -- "$@"
-        ;;
-    i386)
-        dpkg-maintscript-helper rm_conffile /etc/ld.so.conf.d/i486-linux-gnu.conf 2.19-4~ libc6:i386 -- "$@"
-        ;;
-    kfreebsd-i386)
-        dpkg-maintscript-helper rm_conffile /etc/ld.so.conf.d/i486-kfreebsd-gnu.conf 2.19-11~ libc0.1:kfreebsd-i386 -- "$@"
-        ;;
-esac
 
 
 
diff --git a/var/lib/dpkg/info/libc6:i386.preinst b/var/lib/dpkg/info/libc6:i386.preinst
--- a/var/lib/dpkg/info/libc6:i386.preinst
+++ b/var/lib/dpkg/info/libc6:i386.preinst
@@ -144,12 +144,6 @@ then
         # sanity checking for the appropriate kernel on each architecture.
         kernel_ver=`uname -r`
         case ${DPKG_MAINTSCRIPT_ARCH:-$(dpkg --print-architecture)} in
-            amd64|i386)
-                # The GNU libc requires a >= 2.6.32 kernel, found in squeeze or RHEL6
-                kernel_ver_min=2.6.32
-                # But we don't officially support kernels before 3.2
-                kernel_ver_rec=3.2
-                ;;
             *)
                 # The GNU libc requires a >= 3.2 kernel, found in wheezy
                 kernel_ver_min=3.2
@@ -273,29 +267,9 @@ then
         fi
     fi
 
-    # ldconfig might have broken the ld.so symlink in case a biarch package
-    # of the same architecture than the native one has been installed (e.g.:
-    # libc6-amd64:i386 on amd64). Try to detect this by checking that the 
-    # ld.so symlink correctly points to ld-*.so in the slib directory, and 
-    # disabling ldconfig if it is not the case and the new version hasn't
-    # been unpacked yet. The symlink will be fixed when unpacking the new 
-    # libc version and ldconfig will be re-enabled when a new fixed version
-    # is unpacked.
-    if ! readlink -m /lib/ld-linux.so.2 | grep -qE '/lib/i386-linux-gnu/ld-[0-9.]+\.so' ; then
-        # The unpack order is not guaranteed, only disable ldconfig if 
-        # a "broken" version is installed.
-        libc_bin_version=$(dpkg-query -W -f='${Version}' libc-bin)
-        if dpkg --compare-versions "$libc_bin_version" lt "2.18-2"; then
-            echo "Warning: found a potentially broken dynamic loader symlink,"
-            echo "disabling ldconfig to avoid a possible system breakage. It"
-            echo "will be reenabled when a new version of libc-bin is unpacked." 
-            ln -sf /bin/true /sbin/ldconfig
-        fi
-    fi
-
     if [ -n "$preversion" ] && [ -x "$(which ischroot)" ] && ! ischroot; then
 	# NSS authentication trouble guard
-	if dpkg --compare-versions "$preversion" lt 2.24; then
+	if dpkg --compare-versions "$preversion" lt 2.28; then
 	    if pidof xscreensaver xlockmore >/dev/null; then
 		if [ -f /usr/share/debconf/confmodule ] ; then
 		    db_version 2.0
@@ -330,37 +304,26 @@ then
 	    check=$(dpkg -s $check 2> /dev/null | egrep '^Package:|^Status:' | awk '{if ($1 ~ /^Package:/) { package=$2 } else if ($0 ~ /^Status: .* installed$/) { print package }}')
 	    # some init scripts don't match the package names
 	    check=$(echo $check | \
-	    	    sed -e's/\bapache2.2-common\b/apache2/g' \
-	    	    	-e's/\bat\b/atd/g' \
-	    	    	-e's/\bdovecot-common\b/dovecot/g' \
-	    	    	-e's/\bexim4-base\b/exim4/g' \
-	    	    	-e's/\blpr\b/lpd/g' \
-	    	    	-e's/\blpr-ppd\b/lpd-ppd/g' \
-	    	    	-e's/\bmysql-server\b/mysql/g' \
-	    	    	-e's/\bsasl2-bin\b/saslauthd/g' \
-	    	    	-e's/\bpostgresql-common\b/postgresql/g' \
-	    )
+		    sed -e's/\bapache2.2-common\b/apache2/g' \
+			-e's/\bat\b/atd/g' \
+			-e's/\bdovecot-common\b/dovecot/g' \
+			-e's/\bexim4-base\b/exim4/g' \
+			-e's/\blpr\b/lpd/g' \
+			-e's/\blpr-ppd\b/lpd-ppd/g' \
+			-e's/\bmysql-server\b/mysql/g' \
+			-e's/\bsasl2-bin\b/saslauthd/g' \
+			-e's/\bsamba\b/smbd/g' \
+			-e's/\bpostgresql-common\b/postgresql/g' \
+		    )
 	    echo
 	    echo "Checking init scripts..."
-	    rl=$(runlevel | sed 's/.*\ //')
 	    for service in $check; do
-	    	if [ -x "`which invoke-rc.d 2>/dev/null`" ]; then
-	    	    invoke-rc.d ${service} status >/dev/null 2>/dev/null && status=0 || status=$?
-	    	    if [ "$status" = "0" ] || [ "$status" = "2" ] ; then
-	    	    	services="$service $services"
-	    	    elif [ "$status" = "100" ] ; then
-	    	    	echo "WARNING: init script for $service not found."
-	    	    fi
-	    	else
-	    	    if [ -f /usr/share/file-rc/rc ] || [ -f /usr/lib/file-rc/rc ] && [ -f /etc/runlevel.conf ]; then
-	    	    	idl=$(filerc $rl $service)
-	    	    else
-	    	    	idl=$(ls /etc/rc${rl}.d/S??${service} 2> /dev/null | head -1)
-	    	    fi
-	    	    if [ -n "$idl" ] && [ -x $idl ]; then
-	    	    	services="$service $services"
-	    	    fi
-	    	fi
+		invoke-rc.d ${service} status >/dev/null 2>/dev/null && status=0 || status=$?
+		if [ "$status" = "0" ] || [ "$status" = "2" ] ; then
+		    services="$service $services"
+		elif [ "$status" = "100" ] ; then
+		    echo "WARNING: init script for $service not found."
+		fi
 	    done
 
 	    if [ -n "$services" ]; then 
@@ -411,7 +374,7 @@ then
 	            exit 1
 		fi
 	    fi
-	fi # end upgrading and $preversion lt 2.24
+	fi # end upgrading and $preversion lt 2.28
     fi # Upgrading
 
     # This will keep us from using hwcap libs (optimized) during an
@@ -419,25 +382,10 @@ then
     touch /etc/ld.so.nohwcap
 fi
 
-# We now use the multiarch triplet instead of the GNU triplet for the ld.so
-# configuration file, in order to keep a stable path. Remove the old file.
-case ${DPKG_MAINTSCRIPT_ARCH:-$(dpkg --print-architecture)} in
-    hurd-i386)
-        dpkg-maintscript-helper rm_conffile /etc/ld.so.conf.d/i486-gnu.conf 2.19-11~ libc0.3:hurd-i386 -- "$@"
-        dpkg-maintscript-helper rm_conffile /etc/ld.so.conf.d/i486-gnu-gnu.conf 2.19-11~ libc0.3:hurd-i386 -- "$@"
-        ;;
-    i386)
-        dpkg-maintscript-helper rm_conffile /etc/ld.so.conf.d/i486-linux-gnu.conf 2.19-4~ libc6:i386 -- "$@"
-        ;;
-    kfreebsd-i386)
-        dpkg-maintscript-helper rm_conffile /etc/ld.so.conf.d/i486-kfreebsd-gnu.conf 2.19-11~ libc0.1:kfreebsd-i386 -- "$@"
-        ;;
-esac
-
 
 
 if [ -n "$preversion" ]; then
-    if dpkg --compare-versions "$preversion" lt 2.24; then
+    if dpkg --compare-versions "$preversion" lt 2.28; then
        # unconditionally wipe ld.so.cache on major version upgrades; this
        # makes those upgrades a bit slower, but is less error-prone than
        # hoping we notice every time the cache format is changed upstream
diff --git a/var/lib/dpkg/info/man-db.postinst b/var/lib/dpkg/info/man-db.postinst
--- a/var/lib/dpkg/info/man-db.postinst
+++ b/var/lib/dpkg/info/man-db.postinst
@@ -99,12 +99,56 @@ else
     run_mandb "Updating database of manual pages ..." -pq
 fi
 
-# Automatically added by dh_installinit
-if [ "$1" = "configure" ] || [ "$1" = "abort-upgrade" ]; then
+# Automatically added by dh_apparmor/2.13.2-7
+if [ "$1" = "configure" ]; then
+    APP_PROFILE="/etc/apparmor.d/usr.bin.man"
+    if [ -f "$APP_PROFILE" ]; then
+        # Add the local/ include
+        LOCAL_APP_PROFILE="/etc/apparmor.d/local/usr.bin.man"
+
+        test -e "$LOCAL_APP_PROFILE" || {
+            mkdir -p `dirname "$LOCAL_APP_PROFILE"`
+            install --mode 644 /dev/null "$LOCAL_APP_PROFILE"
+        }
+
+        # Reload the profile, including any abstraction updates
+        if aa-enabled --quiet 2>/dev/null; then
+            apparmor_parser -r -T -W "$APP_PROFILE" || true
+        fi
+    fi
+fi
+# End automatically added section
+# Automatically added by dh_systemd_enable/12
+if [ "$1" = "configure" ] || [ "$1" = "abort-upgrade" ] || [ "$1" = "abort-deconfigure" ] || [ "$1" = "abort-remove" ] ; then
+	# This will only remove masks created by d-s-h on package removal.
+	deb-systemd-helper unmask 'man-db.timer' >/dev/null || true
+
+	# was-enabled defaults to true, so new installations run enable.
+	if deb-systemd-helper --quiet was-enabled 'man-db.timer'; then
+		# Enables the unit on first installation, creates new
+		# symlinks on upgrades if the unit file has changed.
+		deb-systemd-helper enable 'man-db.timer' >/dev/null || true
+	else
+		# Update the statefile to add new symlinks (if any), which need to be
+		# cleaned up on purge. Also remove old symlinks.
+		deb-systemd-helper update-state 'man-db.timer' >/dev/null || true
+	fi
+fi
+# End automatically added section
+# Automatically added by dh_installinit/12
+if [ "$1" = "configure" ] || [ "$1" = "abort-upgrade" ] || [ "$1" = "abort-deconfigure" ] || [ "$1" = "abort-remove" ] ; then
 	# In case this system is running systemd, we need to ensure that all
 	# necessary tmpfiles (if any) are created before starting.
 	if [ -d /run/systemd/system ] ; then
-		systemd-tmpfiles --create /usr/lib/tmpfiles.d/man-db.conf >/dev/null || true
+		systemd-tmpfiles --create man-db.conf >/dev/null || true
+	fi
+fi
+# End automatically added section
+# Automatically added by dh_systemd_start/12
+if [ "$1" = "configure" ] || [ "$1" = "abort-upgrade" ] || [ "$1" = "abort-deconfigure" ] || [ "$1" = "abort-remove" ] ; then
+	if [ -d /run/systemd/system ]; then
+		systemctl --system daemon-reload >/dev/null || true
+		deb-systemd-invoke start 'man-db.service' 'man-db.timer' >/dev/null || true
 	fi
 fi
 # End automatically added section
diff --git a/var/lib/dpkg/info/passwd.postinst b/var/lib/dpkg/info/passwd.postinst
--- a/var/lib/dpkg/info/passwd.postinst
+++ b/var/lib/dpkg/info/passwd.postinst
@@ -39,12 +39,12 @@ esac
 # Run shadowconfig only on new installs
 [ -z "$2" ] && shadowconfig on
 
-# Automatically added by dh_installinit
-if [ "$1" = "configure" ] || [ "$1" = "abort-upgrade" ]; then
+# Automatically added by dh_installinit/11.3.5
+if [ "$1" = "configure" ] || [ "$1" = "abort-upgrade" ] || [ "$1" = "abort-deconfigure" ] || [ "$1" = "abort-remove" ] ; then
 	# In case this system is running systemd, we need to ensure that all
 	# necessary tmpfiles (if any) are created before starting.
 	if [ -d /run/systemd/system ] ; then
-		systemd-tmpfiles --create /usr/lib/tmpfiles.d/passwd.conf >/dev/null || true
+		systemd-tmpfiles --create passwd.conf >/dev/null || true
 	fi
 fi
 # End automatically added section
diff --git a/var/lib/dpkg/info/plymouth.postinst b/var/lib/dpkg/info/plymouth.postinst
--- a/var/lib/dpkg/info/plymouth.postinst
+++ b/var/lib/dpkg/info/plymouth.postinst
@@ -28,17 +28,17 @@ case "${1}" in
 		;;
 esac
 
-# Automatically added by dh_installinit
-if [ "$1" = "configure" ] || [ "$1" = "abort-upgrade" ]; then
+# Automatically added by dh_installinit/12.1.1
+if [ "$1" = "configure" ] || [ "$1" = "abort-upgrade" ] || [ "$1" = "abort-deconfigure" ] || [ "$1" = "abort-remove" ] ; then
 	if [ -x "/etc/init.d/plymouth" ]; then
-		update-rc.d plymouth start . 2 3 4 5 . stop . 0 6 . >/dev/null || exit $?
+		update-rc.d plymouth start . 2 3 4 5 . stop . 0 6 . >/dev/null || exit 1
 	fi
 fi
 # End automatically added section
-# Automatically added by dh_installinit
-if [ "$1" = "configure" ] || [ "$1" = "abort-upgrade" ]; then
+# Automatically added by dh_installinit/12.1.1
+if [ "$1" = "configure" ] || [ "$1" = "abort-upgrade" ] || [ "$1" = "abort-deconfigure" ] || [ "$1" = "abort-remove" ] ; then
 	if [ -x "/etc/init.d/plymouth-log" ]; then
-		update-rc.d plymouth-log start . S . >/dev/null || exit $?
+		update-rc.d plymouth-log start . S . >/dev/null || exit 1
 	fi
 fi
 # End automatically added section
diff --git a/var/lib/dpkg/info/procps.postinst b/var/lib/dpkg/info/procps.postinst
--- a/var/lib/dpkg/info/procps.postinst
+++ b/var/lib/dpkg/info/procps.postinst
@@ -96,16 +96,16 @@ esac
 # dh_installdeb will replace this with shell code automatically
 # generated by other debhelper scripts.
 
-# Automatically added by dh_installinit
-if [ "$1" = "configure" ] || [ "$1" = "abort-upgrade" ]; then
-	if [ -x "/etc/init.d/procps" ]; then
-		update-rc.d procps defaults >/dev/null || exit $?
-	fi
-fi
-# End automatically added section
-# Automatically added by dh_installmenu
+# Automatically added by dh_installmenu/11.3.2
 if [ "$1" = "configure" ] && [ -x "`which update-menus 2>/dev/null`" ]; then
 	update-menus
+fi
+# End automatically added section
+# Automatically added by dh_installinit/11.3.2
+if [ "$1" = "configure" ] || [ "$1" = "abort-upgrade" ] || [ "$1" = "abort-deconfigure" ] || [ "$1" = "abort-remove" ] ; then
+	if [ -x "/etc/init.d/procps" ]; then
+		update-rc.d procps defaults >/dev/null || exit 1
+	fi
 fi
 # End automatically added section
 
diff --git a/var/lib/dpkg/info/sudo.postinst b/var/lib/dpkg/info/sudo.postinst
--- a/var/lib/dpkg/info/sudo.postinst
+++ b/var/lib/dpkg/info/sudo.postinst
@@ -8,17 +8,15 @@ if [ -L /etc/alternatives/sudo ]; then
 	rm /etc/alternatives/sudo
 fi
 
+# remove legacy conffile no longer delivered
+
+if [ -f /etc/sudoers.dist ]; then
+	rm /etc/sudoers.dist
+fi
+
 # complain if no sudoers file is present
 if [ ! -f /etc/sudoers ];then
 	echo "WARNING:  /etc/sudoers not present!";
-fi
-
-# handle state directory transition from /var/run/sudo to /var/lib/sudo,
-# moving any existing content over to avoid re-lecturing existing users
-if [ -d "/var/run/sudo" ];then
-    mkdir -p /var/lib/sudo
-    (cd /var/run/sudo ; tar cf - .) | (cd /var/lib/sudo ; tar xf -)
-    rm -rf /var/run/sudo
 fi
 
 # make sure sudoers has the correct permissions and owner/group
@@ -29,6 +27,30 @@ fi
 
 # if we've gotten this far .. remove the saved, unchanged old sudoers file
 rm -f /etc/sudoers.pre-conffile
+
+# Automatically added by dh_installinit/12.1.1
+if [ "$1" = "configure" ] || [ "$1" = "abort-upgrade" ] || [ "$1" = "abort-deconfigure" ] || [ "$1" = "abort-remove" ] ; then
+	# In case this system is running systemd, we need to ensure that all
+	# necessary tmpfiles (if any) are created before starting.
+	if [ -d /run/systemd/system ] ; then
+		systemd-tmpfiles --create sudo.conf >/dev/null || true
+	fi
+fi
+# End automatically added section
+# Automatically added by dh_installinit/12.1.1
+if [ "$1" = "configure" ] || [ "$1" = "abort-upgrade" ] || [ "$1" = "abort-deconfigure" ] || [ "$1" = "abort-remove" ] ; then
+	if [ -x "/etc/init.d/sudo" ]; then
+		update-rc.d sudo defaults >/dev/null
+		if [ -n "$2" ]; then
+			_dh_action=restart
+		else
+			_dh_action=start
+		fi
+		invoke-rc.d sudo $_dh_action || exit 1
+	fi
+fi
+# End automatically added section
+
 
 # make sure we have a sudo group
 
@@ -63,18 +85,3 @@ echo "Creating group 'sudo' with gid = $gid";
 groupadd -g $gid sudo
 
 echo ""
-
-# Automatically added by dh_installinit
-if [ "$1" = "configure" ] || [ "$1" = "abort-upgrade" ]; then
-	if [ -x "/etc/init.d/sudo" ]; then
-		update-rc.d sudo defaults >/dev/null
-		if [ -n "$2" ]; then
-			_dh_action=restart
-		else
-			_dh_action=start
-		fi
-		invoke-rc.d sudo $_dh_action || exit $?
-	fi
-fi
-# End automatically added section
-
diff --git a/var/lib/dpkg/info/systemd.postinst b/var/lib/dpkg/info/systemd.postinst
--- a/var/lib/dpkg/info/systemd.postinst
+++ b/var/lib/dpkg/info/systemd.postinst
@@ -28,10 +28,8 @@ if [ "$1" = "triggered" ]; then
     exit 0
 fi
 
-# Enable getty and remote-fs.target by default on new installs, and on
-# upgrades from old systemd versions (where the symlinks included as deb
-# content, and will thus have been removed by dpkg during the upgrade).
-if dpkg --compare-versions "$2" lt "214-1"; then
+# Enable getty and remote-fs.target by default on new installs
+if [ -z "$2" ]; then
     systemctl enable getty@tty1.service || true
     systemctl enable remote-fs.target || true
 fi
@@ -47,7 +45,7 @@ if [ -e /lib/systemd/system/ondemand.service ] && dpkg --compare-versions "$2" l
 fi
 
 # Do a one-time migration of the local time setting
-if dpkg --compare-versions "$2" lt "33-1"; then
+if [ -z "$2" ]; then
     if [ -f /etc/default/rcS ]; then
         . /etc/default/rcS
     fi
@@ -57,13 +55,7 @@ if dpkg --compare-versions "$2" lt "33-1"; then
 fi
 
 # Do a one-time migration of the TMPTIME setting
-if dpkg --compare-versions "$2" lt "204-9"; then
-    # Fix up potentially broken tmp.conf, see Debian#738862
-    if [ -e /etc/tmpfiles.d/tmp.conf ]; then
-        sed -i '/^# Clear \/var\/tmp/d' /etc/tmpfiles.d/tmp.conf
-        sed -i 's,^\(d /var/tmp\),#\1,g' /etc/tmpfiles.d/tmp.conf
-    fi
-
+if [ -z "$2" ]; then
     if [ -f /etc/default/rcS ]; then
         . /etc/default/rcS
     fi
@@ -82,7 +74,7 @@ EOF
 fi
 
 # Do a one-time migration of the RAMTMP setting
-if dpkg --compare-versions "$2" lt "204-8"; then
+if [ -z "$2" ]; then
     if [ -f /etc/default/rcS ]; then
         . /etc/default/rcS
     fi
@@ -102,36 +94,36 @@ fi
 systemd-machine-id-setup
 
 # Setup system users and groups
-addgroup --system systemd-journal
+addgroup --quiet --system systemd-journal
+
+# We need to stop running services before we call adduser
+RESTART=""
+if dpkg --compare-versions "$2" lt-nl "239-6"; then
+    for s in systemd-networkd systemd-timesyncd systemd-resolved ; do
+        if _systemctl -q is-active $s; then
+            _systemctl stop $s
+            RESTART="$s $RESTART"
+        fi
+    done
+fi
 
 adduser --quiet --system --group --no-create-home --home /run/systemd \
     --gecos "systemd Time Synchronization" systemd-timesync
-adduser --quiet --system --group --no-create-home --home /run/systemd/netif \
-    --gecos "systemd Network Management" systemd-network
-adduser --quiet --system --group --no-create-home --home /run/systemd/resolve \
-    --gecos "systemd Resolver" systemd-resolve
 adduser --quiet --system --group --no-create-home --home /run/systemd \
-    --gecos "systemd Bus Proxy" systemd-bus-proxy
+    --gecos "systemd Network Management" systemd-network
+adduser --quiet --system --group --no-create-home --home /run/systemd \
+    --gecos "systemd Resolver" systemd-resolve
+
+# Remove old state directory of systemd-timesyncd
+if dpkg --compare-versions "$2" lt-nl "240-3~"; then
+    if [ -L /var/lib/systemd/timesync ] ; then
+        rm /var/lib/systemd/timesync
+        rm -rf /var/lib/private/systemd/timesync
+    fi
+fi
 
 # Initial update of the Message Catalogs database
 _update_catalog
-
-# Re-run systemctl enable for any service that was enabled when preinst was run.
-if dpkg --compare-versions "$2" ge "204" && [ -e /run/systemd/was-enabled ]; then
-    while read UNIT ; do
-        # 220-6 stopped shipping tmp.mount, transition it on machines which had
-        # it enabled
-        if [ "$UNIT" = tmp.mount ] && dpkg --compare-versions "$2" lt-nl "220-6~"; then
-            if [ ! -e /etc/systemd/system/tmp.mount ]; then
-                echo "moving enabled tmp.mount to /etc/systemd/system/..."
-                cp /usr/share/systemd/tmp.mount /etc/systemd/system/tmp.mount
-                # clean up the symlink, to have it re-created below
-                systemctl disable $UNIT
-            fi
-        fi
-        systemctl enable $UNIT || true
-    done </run/systemd/was-enabled || true
-fi
 
 if [ -n "$2" ]; then
     _systemctl daemon-reexec || true
@@ -140,6 +132,15 @@ if [ -n "$2" ]; then
     _systemctl try-restart systemd-networkd.service || true
     _systemctl try-restart systemd-resolved.service || true
     _systemctl try-restart systemd-timesyncd.service || true
+    _systemctl try-restart systemd-journald.service || true
+fi
+
+# Restart services which we stopped earlier
+# This needs to run after daemon-rexec
+if dpkg --compare-versions "$2" lt-nl "239-6"; then
+    for s in $RESTART ; do
+        _systemctl start $s
+    done
 fi
 
 # Cleanup hwclock-save.service, which was shipped in jessie.
@@ -150,34 +151,45 @@ if dpkg --compare-versions "$2" lt-nl "228-5~"; then
    done
 fi
 
-# Automatically added by dh_installinit
-if [ "$1" = "configure" ] || [ "$1" = "abort-upgrade" ]; then
+if dpkg --compare-versions "$2" lt-nl "235-3~"; then
+    # systemd-bus-proxyd got dropped before stretch, and never created any file
+    deluser --system systemd-bus-proxy || true
+fi
+
+if dpkg --compare-versions "$2" lt-nl "236-1~"; then
+    # Clean up old /var/lib/systemd/clock on upgrade.
+    # The clock file used by systemd-timesyncd is now stored in
+    # StateDirectory=systemd/timesync.
+    rm -f /var/lib/systemd/clock
+fi
+
+if dpkg --compare-versions "$2" lt-nl "239-12~"; then
+    # clean up bogus "nobody" group from #912525; ensure that it's a system group
+    if getent group nobody >/dev/null; then
+        delgroup --system nobody || true
+    fi
+fi
+
+# Automatically added by dh_installinit/12.1.1
+if [ "$1" = "configure" ] || [ "$1" = "abort-upgrade" ] || [ "$1" = "abort-deconfigure" ] || [ "$1" = "abort-remove" ] ; then
 	# In case this system is running systemd, we need to ensure that all
 	# necessary tmpfiles (if any) are created before starting.
 	if [ -d /run/systemd/system ] ; then
-		systemd-tmpfiles --create /usr/lib/tmpfiles.d/debian.conf /usr/lib/tmpfiles.d/home.conf /usr/lib/tmpfiles.d/journal-nocow.conf /usr/lib/tmpfiles.d/legacy.conf /usr/lib/tmpfiles.d/systemd-nologin.conf /usr/lib/tmpfiles.d/systemd.conf /usr/lib/tmpfiles.d/tmp.conf /usr/lib/tmpfiles.d/var.conf /usr/lib/tmpfiles.d/x11.conf >/dev/null || true
+		systemd-tmpfiles --create debian.conf home.conf journal-nocow.conf legacy.conf systemd-nologin.conf systemd.conf tmp.conf var.conf x11.conf >/dev/null || true
 	fi
 fi
 # End automatically added section
-# Automatically added by dh_installdeb
-dpkg-maintscript-helper rm_conffile /etc/bash_completion.d/systemctl-bash-completion.sh 204-1~ -- "$@"
-# End automatically added section
-# Automatically added by dh_installdeb
-dpkg-maintscript-helper rm_conffile /etc/bash_completion.d/systemd-bash-completion.sh 204-1~ -- "$@"
-# End automatically added section
-# Automatically added by dh_installdeb
-dpkg-maintscript-helper mv_conffile /etc/systemd/systemd-logind.conf /etc/systemd/logind.conf 204-1~ -- "$@"
-# End automatically added section
-# Automatically added by dh_installdeb
-dpkg-maintscript-helper mv_conffile /etc/systemd/systemd-journald.conf /etc/systemd/journald.conf 204-1~ -- "$@"
-# End automatically added section
-# Automatically added by dh_installdeb
-dpkg-maintscript-helper rm_conffile /etc/dbus-1/system.d/org.freedesktop.machine1.conf 228-5~ -- "$@"
-# End automatically added section
-# Automatically added by dh_installdeb
-dpkg-maintscript-helper rm_conffile /etc/X11/xinit/xinitrc.d/50-systemd-user.sh 228-3~ -- "$@"
-# End automatically added section
-# Automatically added by dh_installdeb
-dpkg-maintscript-helper rm_conffile /etc/systemd/bootchart.conf 230-1~ -- "$@"
+# Automatically added by dh_installdeb/12.1.1
+dpkg-maintscript-helper rm_conffile /etc/X11/xinit/xinitrc.d/50-systemd-user.sh 228-3\~ -- "$@"
+dpkg-maintscript-helper rm_conffile /etc/systemd/bootchart.conf 230-1\~ -- "$@"
+dpkg-maintscript-helper rm_conffile /etc/dbus-1/system.d/org.freedesktop.hostname1.conf 233-3\~ -- "$@"
+dpkg-maintscript-helper rm_conffile /etc/dbus-1/system.d/org.freedesktop.locale1.conf 233-3\~ -- "$@"
+dpkg-maintscript-helper rm_conffile /etc/dbus-1/system.d/org.freedesktop.login1.conf 233-3\~ -- "$@"
+dpkg-maintscript-helper rm_conffile /etc/dbus-1/system.d/org.freedesktop.machine1.conf 228-5\~ -- "$@"
+dpkg-maintscript-helper rm_conffile /etc/dbus-1/system.d/org.freedesktop.network1.conf 233-3\~ -- "$@"
+dpkg-maintscript-helper rm_conffile /etc/dbus-1/system.d/org.freedesktop.resolve1.conf 233-3\~ -- "$@"
+dpkg-maintscript-helper rm_conffile /etc/dbus-1/system.d/org.freedesktop.systemd1.conf 233-3\~ -- "$@"
+dpkg-maintscript-helper rm_conffile /etc/dbus-1/system.d/org.freedesktop.timedate1.conf 233-3\~ -- "$@"
+dpkg-maintscript-helper rm_conffile /etc/dbus-1/system.d/org.freedesktop.systemd-shim.conf 239-15\~ systemd-shim -- "$@"
 # End automatically added section
 
diff --git a/var/lib/dpkg/info/udev.postinst b/var/lib/dpkg/info/udev.postinst
--- a/var/lib/dpkg/info/udev.postinst
+++ b/var/lib/dpkg/info/udev.postinst
@@ -20,7 +20,7 @@ in_debootstrap() {
     return 0
   fi
   return 1
-} 
+}
 
 can_start_udevd() {
   if [ ! -d /sys/class/ ]; then
@@ -42,11 +42,6 @@ update_initramfs() {
 }
 
 upgrade_fixes() {
-  if dpkg --compare-versions "$2" lt "204-1"; then
-    # We dropped udev-mtab with udev 204.
-    update-rc.d udev-mtab remove
-  fi
-
   if dpkg --compare-versions "$2" lt "226-1"; then
     update-rc.d udev-finish remove
   fi
@@ -90,29 +85,15 @@ Driver=virtio_net
 NamePolicy=onboard kernel
 EOF
   fi
+
+  # new Default-Stop (see #791944)
+  if dpkg --compare-versions "$2" lt-nl "239-8"; then
+    update-rc.d -f udev remove
+  fi
 }
 
 update_hwdb() {
   systemd-hwdb --usr update || true
-}
-
-# In udev-204, we ship systemd-udevd.service (upstream name), whereas previous
-# versions used udev.service. We replace udev.service with a symlink to
-# systemd-udevd.service, but systemd (both 44 and 204) exposes weird behavior:
-# After a daemon-reload, it forgets about the /sbin/udevd process in the
-# udev.service cgroup, so a restart will lead to having two udevd processes
-# running — one in the udev.service cgroup and one in the systemd-udevd.service
-# cgroup.
-#
-# To fix this, we explicitly stop udev.service and the corresponding sockets,
-# then issue the daemon-reload, then restart the new systemd-udevd.service (via
-# invoke-rc.d).
-handle_service_rename() {
-  if dpkg --compare-versions "$2" lt "204-1"; then
-    if [ -d /run/systemd/system ]; then
-      systemctl stop udev.service udev-control.socket udev-kernel.socket >/dev/null 2>&1 || true
-    fi
-  fi
 }
 
 case "$1" in
@@ -121,7 +102,13 @@ case "$1" in
     update_hwdb
 
     # Add new system group used by udev rules
-    addgroup --system input
+    addgroup --quiet --system input
+
+    # Make /dev/kvm accessible to kvm group
+    addgroup --quiet --system kvm
+
+    # Make /dev/dri/renderD* accessible to render group
+    addgroup --quiet --system render
 
     if [ -z "$2" ]; then # first install
       if ! chrooted && ! in_debootstrap; then
@@ -131,9 +118,6 @@ case "$1" in
       upgrade_fixes "$@"
       if ! chrooted; then
 	if can_start_udevd; then
-	  handle_service_rename
-	  # This is necessary for the handle_service_rename case, but does not
-	  # hurt in general (invoke-rc.d does it, too).
 	  if [ -d /run/systemd/system ] ; then
 	    systemctl daemon-reload || true
 	  fi
@@ -151,33 +135,22 @@ case "$1" in
     ;;
 esac
 
-# Automatically added by dh_installinit
-if [ "$1" = "configure" ] || [ "$1" = "abort-upgrade" ]; then
+# Automatically added by dh_installdeb/12.1.1
+dpkg-maintscript-helper rm_conffile /etc/init.d/udev-finish 226-1\~ -- "$@"
+dpkg-maintscript-helper rm_conffile /etc/init/udev-finish.conf 226-1\~ -- "$@"
+dpkg-maintscript-helper rm_conffile /etc/init/udev-fallback-graphics.conf 226-1\~ -- "$@"
+dpkg-maintscript-helper symlink_to_dir /usr/share/doc/udev libudev1 221-2\~ -- "$@"
+dpkg-maintscript-helper rm_conffile /etc/modprobe.d/fbdev-blacklist.conf 229-6\~ -- "$@"
+dpkg-maintscript-helper rm_conffile /etc/init/udev.conf 233-1\~ -- "$@"
+dpkg-maintscript-helper rm_conffile /etc/init/udevmonitor.conf 233-1\~ -- "$@"
+dpkg-maintscript-helper rm_conffile /etc/init/udevtrigger.conf 233-1\~ -- "$@"
+# End automatically added section
+# Automatically added by dh_installinit/12.1.1
+if [ "$1" = "configure" ] || [ "$1" = "abort-upgrade" ] || [ "$1" = "abort-deconfigure" ] || [ "$1" = "abort-remove" ] ; then
 	if [ -x "/etc/init.d/udev" ]; then
-		update-rc.d udev defaults >/dev/null || exit $?
+		update-rc.d udev defaults >/dev/null || exit 1
 	fi
 fi
-# End automatically added section
-# Automatically added by dh_installdeb
-dpkg-maintscript-helper rm_conffile /etc/init.d/udev-mtab 204-1~ -- "$@"
-# End automatically added section
-# Automatically added by dh_installdeb
-dpkg-maintscript-helper rm_conffile /etc/udev/links.conf 204-9~ -- "$@"
-# End automatically added section
-# Automatically added by dh_installdeb
-dpkg-maintscript-helper rm_conffile /etc/init.d/udev-finish 226-1~ -- "$@"
-# End automatically added section
-# Automatically added by dh_installdeb
-dpkg-maintscript-helper rm_conffile /etc/init/udev-finish.conf 226-1~ -- "$@"
-# End automatically added section
-# Automatically added by dh_installdeb
-dpkg-maintscript-helper rm_conffile /etc/init/udev-fallback-graphics.conf 226-1~ -- "$@"
-# End automatically added section
-# Automatically added by dh_installdeb
-dpkg-maintscript-helper symlink_to_dir /usr/share/doc/udev libudev1 221-2~ -- "$@"
-# End automatically added section
-# Automatically added by dh_installdeb
-dpkg-maintscript-helper rm_conffile /etc/modprobe.d/fbdev-blacklist.conf 229-6~ -- "$@"
 # End automatically added section
 
 
diff --git a/var/lib/dpkg/info/util-linux.postinst b/var/lib/dpkg/info/util-linux.postinst
--- a/var/lib/dpkg/info/util-linux.postinst
+++ b/var/lib/dpkg/info/util-linux.postinst
@@ -4,36 +4,43 @@ set -e
 update-alternatives --install /usr/bin/pager pager /bin/more 50 \
 	--slave /usr/share/man/man1/pager.1.gz pager.1.gz \
 	/usr/share/man/man1/more.1.gz
-update-alternatives --install /usr/bin/pager pager /usr/bin/pg 10 \
-	--slave /usr/share/man/man1/pager.1.gz pager.1.gz \
-	/usr/share/man/man1/pg.1.gz
 
-# hwclock works on all Linux architectures, except s390 (and s390x, of course).
-if [ "$(uname -s)" = "Linux" ]; then
-	model=$(uname -m)
-	if [ ${model%x} != "s390" ]; then
-		# work around that initscripts package might still be
-		# in "unpacked" (not yet configured) state and insserv
-		# will fail on hwclock.sh if Required scripts are not
-		# processed yet. See http://bugs.debian.org/823665
-		# (We can't add initscripts dependency to util-linux because
-		# that would introduce a dependency cycle via
-		# sysvinit-utils<->initscripts<->util-linux
-		# because of Depends/Breaks relations. Ideally the hwclock.sh
-		# scripts should just be moved over to initscripts pkg, but
-		# moving conffiles between packages is problematic.)
-		if dpkg-query -W --showformat '${Status}\n' initscripts | grep -q unpacked ; then
-			if [ -x /etc/init.d/mountkernfs.sh ]; then
-				update-rc.d mountkernfs.sh         defaults >/dev/null || exit $?
-			fi
-			if [ -x /etc/init.d/mountdevsubfs.sh ]; then
-				update-rc.d mountdevsubfs.sh       defaults >/dev/null || exit $?
-			fi
-		fi
+# We stopped shipping the 'pg' utility, so remove it as a pager
+# alternative on upgrades from Stretch.
+update-alternatives --remove pager /usr/bin/pg
 
-		update-rc.d -f hwclock.sh remove >/dev/null 2>&1 || true
-		update-rc.d hwclock.sh defaults > /dev/null
+# Automatically added by dh_installinit/12
+if [ "$1" = "configure" ] || [ "$1" = "abort-upgrade" ] || [ "$1" = "abort-deconfigure" ] || [ "$1" = "abort-remove" ] ; then
+	if [ -x "/etc/init.d/hwclock.sh" ]; then
+		update-rc.d hwclock.sh defaults >/dev/null || exit 1
 	fi
 fi
+# End automatically added section
+# Automatically added by dh_installsystemd/12
+if [ "$1" = "configure" ] || [ "$1" = "abort-upgrade" ] || [ "$1" = "abort-deconfigure" ] || [ "$1" = "abort-remove" ] ; then
+	if deb-systemd-helper debian-installed 'fstrim.timer'; then
+		# This will only remove masks created by d-s-h on package removal.
+		deb-systemd-helper unmask 'fstrim.timer' >/dev/null || true
 
+		if deb-systemd-helper --quiet was-enabled 'fstrim.timer'; then
+			# Create new symlinks, if any.
+			deb-systemd-helper enable 'fstrim.timer' >/dev/null || true
+		fi
+	fi
+
+	# Update the statefile to add new symlinks (if any), which need to be cleaned
+	# up on purge. Also remove old symlinks.
+	deb-systemd-helper update-state 'fstrim.timer' >/dev/null || true
+fi
+# End automatically added section
+# Automatically added by dh_installsystemd/12
+if [ "$1" = "configure" ] || [ "$1" = "abort-upgrade" ] || [ "$1" = "abort-deconfigure" ] || [ "$1" = "abort-remove" ] ; then
+	if [ -d /run/systemd/system ]; then
+		systemctl --system daemon-reload >/dev/null || true
+		if [ -n "$2" ]; then
+			deb-systemd-invoke try-restart 'fstrim.service' 'fstrim.timer' >/dev/null || true
+		fi
+	fi
+fi
+# End automatically added section
 
diff --git a/var/lib/dpkg/info/wpasupplicant.postinst b/var/lib/dpkg/info/wpasupplicant.postinst
--- a/var/lib/dpkg/info/wpasupplicant.postinst
+++ b/var/lib/dpkg/info/wpasupplicant.postinst
@@ -32,5 +32,35 @@ case "$1" in
 		;;
 esac
 
+# Automatically added by dh_installsystemd/12.1.1
+if [ "$1" = "configure" ] || [ "$1" = "abort-upgrade" ] || [ "$1" = "abort-deconfigure" ] || [ "$1" = "abort-remove" ] ; then
+	# This will only remove masks created by d-s-h on package removal.
+	deb-systemd-helper unmask 'wpa_supplicant.service' >/dev/null || true
+
+	# was-enabled defaults to true, so new installations run enable.
+	if deb-systemd-helper --quiet was-enabled 'wpa_supplicant.service'; then
+		# Enables the unit on first installation, creates new
+		# symlinks on upgrades if the unit file has changed.
+		deb-systemd-helper enable 'wpa_supplicant.service' >/dev/null || true
+	else
+		# Update the statefile to add new symlinks (if any), which need to be
+		# cleaned up on purge. Also remove old symlinks.
+		deb-systemd-helper update-state 'wpa_supplicant.service' >/dev/null || true
+	fi
+fi
+# End automatically added section
+# Automatically added by dh_installsystemd/12.1.1
+if [ "$1" = "configure" ] || [ "$1" = "abort-upgrade" ] || [ "$1" = "abort-deconfigure" ] || [ "$1" = "abort-remove" ] ; then
+	if [ -d /run/systemd/system ]; then
+		systemctl --system daemon-reload >/dev/null || true
+		if [ -n "$2" ]; then
+			_dh_action=restart
+		else
+			_dh_action=start
+		fi
+		deb-systemd-invoke $_dh_action 'wpa_supplicant.service' >/dev/null || true
+	fi
+fi
+# End automatically added section
 
 exit 0
