dist-upgrade to jessie
This upgrades the entire system. Some conflicts were encountered by apt
in config files. This includes initscripts, which were replaced by the
latest version from the package and sysctl.conf, /etc/default/ntpdate
and dnsmasq.conf, which were left untouched.

For configuring acpid (and possibly others), /proc needed to be mounted.

diff --git a/usr/bin/apt-key b/usr/bin/apt-key
--- a/usr/bin/apt-key
+++ b/usr/bin/apt-key
@@ -3,27 +3,41 @@
 set -e
 unset GREP_OPTIONS
 
-# We don't use a secret keyring, of course, but gpg panics and
-# implodes if there isn't one available
-SECRETKEYRING="$(mktemp)"
-trap "rm -f '${SECRETKEYRING}'" 0 HUP INT QUIT ILL ABRT FPE SEGV PIPE TERM
-GPG_CMD="gpg --ignore-time-conflict --no-options --no-default-keyring --secret-keyring ${SECRETKEYRING}"
+GPG_CMD="gpg --ignore-time-conflict --no-options --no-default-keyring"
 
-if [ "$(id -u)" -eq 0 ]; then
-	# we could use a tmpfile here too, but creation of this tends to be time-consuming
-	eval $(apt-config shell TRUSTDBDIR Dir::Etc/d)
-	GPG_CMD="$GPG_CMD --trustdb-name ${TRUSTDBDIR}/trustdb.gpg"
-fi
+# gpg needs (in different versions more or less) files to function correctly,
+# so we give it its own homedir and generate some valid content for it
+GPGHOMEDIR="$(mktemp -d)"
+CURRENTTRAP="${CURRENTTRAP} rm -rf '${GPGHOMEDIR}';"
+trap "${CURRENTTRAP}" 0 HUP INT QUIT ILL ABRT FPE SEGV PIPE TERM
+chmod 700 "$GPGHOMEDIR"
+# We don't use a secret keyring, of course, but gpg panics and
+# implodes if there isn't one available - and writeable for imports
+SECRETKEYRING="${GPGHOMEDIR}/secring.gpg"
+touch $SECRETKEYRING
+GPG_CMD="$GPG_CMD --homedir $GPGHOMEDIR"
+# create the trustdb with an (empty) dummy keyring
+# older gpgs required it, newer gpgs even warn that it isn't needed,
+# but require it nonetheless for some commands, so we just play safe
+# here for the foreseeable future and create a dummy one
+$GPG_CMD --quiet --check-trustdb --keyring $SECRETKEYRING >/dev/null 2>&1
+# tell gpg that it shouldn't try to maintain a trustdb file
+GPG_CMD="$GPG_CMD --no-auto-check-trustdb --trust-model always"
 
 GPG="$GPG_CMD"
 
-MASTER_KEYRING=""
-ARCHIVE_KEYRING_URI=""
-#MASTER_KEYRING=/usr/share/keyrings/debian-master-keyring.gpg
-#ARCHIVE_KEYRING_URI=http://ftp.debian.org/debian/debian-archive-keyring.gpg
+APT_DIR="/"
+eval $(apt-config shell APT_DIR Dir)
 
-ARCHIVE_KEYRING=/usr/share/keyrings/debian-archive-keyring.gpg
-REMOVED_KEYS=/usr/share/keyrings/debian-archive-removed-keys.gpg
+MASTER_KEYRING=''
+eval $(apt-config shell MASTER_KEYRING APT::Key::MasterKeyring)
+ARCHIVE_KEYRING='/usr/share/keyrings/debian-archive-keyring.gpg'
+eval $(apt-config shell ARCHIVE_KEYRING APT::Key::ArchiveKeyring)
+REMOVED_KEYS='/usr/share/keyrings/debian-archive-removed-keys.gpg'
+eval $(apt-config shell REMOVED_KEYS APT::Key::RemovedKeys)
+ARCHIVE_KEYRING_URI=''
+eval $(apt-config shell ARCHIVE_KEYRING_URI APT::Key::ArchiveKeyringURI)
+TMP_KEYRING=${APT_DIR}/var/lib/apt/keyrings/maybe-import-keyring.gpg
 
 requires_root() {
 	if [ "$(id -u)" -ne 0 ]; then
@@ -32,10 +46,20 @@ requires_root() {
 	fi
 }
 
+# gpg defaults to mode 0600 for new keyrings. Create one with 0644 instead.
+init_keyring() {
+    for path; do
+        if ! [ -e "$path" ]; then
+            touch -- "$path"
+            chmod 0644 -- "$path"
+        fi
+    done
+}
+
 add_keys_with_verify_against_master_keyring() {
     ADD_KEYRING=$1
     MASTER=$2
-    
+
     if [ ! -f "$ADD_KEYRING" ]; then
 	echo "ERROR: '$ADD_KEYRING' not found"
 	return
@@ -50,12 +74,28 @@ add_keys_with_verify_against_master_keyring() {
     #   all keys that are exported must have a valid signature
     #   from a key in the $distro-master-keyring
     add_keys=`$GPG_CMD --keyring $ADD_KEYRING --with-colons --list-keys | grep ^pub | cut -d: -f5`
+    all_add_keys=`$GPG_CMD --keyring $ADD_KEYRING --with-colons --list-keys | grep ^[ps]ub | cut -d: -f5`
     master_keys=`$GPG_CMD --keyring $MASTER --with-colons --list-keys | grep ^pub | cut -d: -f5`
-    for add_key in $add_keys; do
-	ADDED=0
+
+    # ensure there are no colisions LP: #857472
+    for all_add_key in $all_add_keys; do
 	for master_key in $master_keys; do
-	    if $GPG_CMD --keyring $ADD_KEYRING --list-sigs --with-colons $add_key | grep ^sig | cut -d: -f5 | grep -q $master_key; then
-		$GPG_CMD --quiet --batch --keyring $ADD_KEYRING --export $add_key | $GPG --import
+            if [ "$all_add_key" = "$master_key" ]; then
+                echo >&2 "Keyid collision for '$all_add_key' detected, operation aborted"
+                return 1
+            fi
+        done
+    done
+    
+    for add_key in $add_keys; do
+        # export the add keyring one-by-one
+        rm -f $TMP_KEYRING
+        $GPG_CMD --keyring $ADD_KEYRING --output $TMP_KEYRING --export $add_key 
+        # check if signed with the master key and only add in this case
+        ADDED=0
+	for master_key in $master_keys; do
+	    if $GPG_CMD --keyring $MASTER --keyring $TMP_KEYRING --check-sigs --with-colons $add_key | grep '^sig:!:' | cut -d: -f5 | grep -q $master_key; then
+		$GPG --import $TMP_KEYRING
 		ADDED=1
 	    fi
 	done
@@ -63,12 +103,20 @@ add_keys_with_verify_against_master_keyring() {
 	    echo >&2 "Key '$add_key' not added. It is not signed with a master key"
 	fi
     done
+    rm -f $TMP_KEYRING
 }
 
 # update the current archive signing keyring from a network URI
 # the archive-keyring keys needs to be signed with the master key
 # (otherwise it does not make sense from a security POV)
 net_update() {
+    # Disabled for now as code is insecure (LP: #1013639 (and 857472, 1013128))
+    APT_KEY_NET_UPDATE_ENABLED=""
+    eval $(apt-config shell APT_KEY_NET_UPDATE_ENABLED APT::Key::Net-Update-Enabled)
+    if [ -z "$APT_KEY_NET_UPDATE_ENABLED" ]; then
+        exit 1
+    fi
+
     if [ -z "$ARCHIVE_KEYRING_URI" ]; then
 	echo >&2 "ERROR: Your distribution is not supported in net-update as no uri for the archive-keyring is set"
 	exit 1
@@ -80,15 +128,15 @@ net_update() {
 	echo >&2 "ERROR: an installed wget is required for a network-based update"
 	exit 1
     fi
-    if [ ! -d /var/lib/apt/keyrings ]; then
-	mkdir -p /var/lib/apt/keyrings
+    if [ ! -d ${APT_DIR}/var/lib/apt/keyrings ]; then
+	mkdir -p ${APT_DIR}/var/lib/apt/keyrings
     fi
-    keyring=/var/lib/apt/keyrings/$(basename $ARCHIVE_KEYRING)
+    keyring=${APT_DIR}/var/lib/apt/keyrings/$(basename $ARCHIVE_KEYRING_URI)
     old_mtime=0
     if [ -e $keyring ]; then
 	old_mtime=$(stat -c %Y $keyring)
     fi
-    (cd  /var/lib/apt/keyrings; wget -q -N $ARCHIVE_KEYRING_URI)
+    (cd  ${APT_DIR}/var/lib/apt/keyrings; wget --timeout=90 -q -N $ARCHIVE_KEYRING_URI)
     if [ ! -e $keyring ]; then
 	return
     fi
@@ -129,6 +177,60 @@ update() {
     fi
 }
 
+remove_key_from_keyring() {
+    local GPG="$GPG_CMD --keyring $1"
+    # check if the key is in this keyring: the key id is in the 5 column at the end
+    if ! $GPG --with-colons --list-keys 2>&1 | grep -q "^pub:[^:]*:[^:]*:[^:]*:[0-9A-F]*$2:"; then
+	return
+    fi
+    if [ ! -w "$1" ]; then
+	echo >&2 "Key ${2} is in keyring ${1}, but can't be removed as it is read only."
+	return
+    fi
+    # check if it is the only key in the keyring and if so remove the keyring altogether
+    if [ '1' = "$($GPG --with-colons --list-keys | grep "^pub:[^:]*:[^:]*:[^:]*:[0-9A-F]\+:" | wc -l)" ]; then
+	mv -f "$1" "${1}~" # behave like gpg
+	return
+    fi
+    # we can't just modify pointed to files as these might be in /usr or something
+    local REALTARGET
+    if [ -L "$1" ]; then
+	REALTARGET="$(readlink -f "$1")"
+	mv -f "$1" "${1}.dpkg-tmp"
+	cp -a "$REALTARGET" "$1"
+	ls "$(dirname $1)"
+    fi
+    # delete the key from the keyring
+    $GPG --batch --delete-key --yes "$2"
+    if [ -n "$REALTARGET" ]; then
+	# the real backup is the old link, not the copy we made
+	mv -f "${1}.dpkg-tmp" "${1}~"
+    fi
+}
+
+remove_key() {
+    requires_root
+
+    # if a --keyring was given, just remove from there
+    if [ -n "$FORCED_KEYRING" ]; then
+	remove_key_from_keyring "$FORCED_KEYRING" "$1"
+    else
+	# otherwise all known keyrings are up for inspection
+	local TRUSTEDFILE="/etc/apt/trusted.gpg"
+	eval $(apt-config shell TRUSTEDFILE Apt::GPGV::TrustedKeyring)
+	eval $(apt-config shell TRUSTEDFILE Dir::Etc::Trusted/f)
+	remove_key_from_keyring "$TRUSTEDFILE" "$1"
+	TRUSTEDPARTS="/etc/apt/trusted.gpg.d"
+	eval $(apt-config shell TRUSTEDPARTS Dir::Etc::TrustedParts/d)
+	if [ -d "$TRUSTEDPARTS" ]; then
+	    for trusted in $(run-parts --list "$TRUSTEDPARTS" --regex '^.*\.gpg$'); do
+		remove_key_from_keyring "$trusted" "$1"
+	    done
+	fi
+    fi
+    echo "OK"
+}
+
 
 usage() {
     echo "Usage: apt-key [--keyring file] [command] [arguments]"
@@ -148,39 +250,54 @@ usage() {
     echo "If no specific keyring file is given the command applies to all keyring files."
 }
 
-# Determine on which keyring we want to work
-if [ "$1" = "--keyring" ]; then
-        #echo "keyfile given"
-	shift
-	TRUSTEDFILE="$1"
-	if [ -r "$TRUSTEDFILE" ] || [ "$2" = 'add' ]; then
-		GPG="$GPG --keyring $TRUSTEDFILE --primary-keyring $TRUSTEDFILE"
-	else
-		echo >&2 "Error: The specified keyring »$TRUSTEDFILE« is missing or not readable"
-		exit 1
-	fi
-	shift
-# otherwise use the default
-else
-	#echo "generate list"
-	TRUSTEDFILE="/etc/apt/trusted.gpg"
-	eval $(apt-config shell TRUSTEDFILE Apt::GPGV::TrustedKeyring)
-	eval $(apt-config shell TRUSTEDFILE Dir::Etc::Trusted/f)
-	if [ -r "$TRUSTEDFILE" ]; then
-		GPG="$GPG --keyring $TRUSTEDFILE"
-	fi
-	GPG="$GPG --primary-keyring $TRUSTEDFILE"
-	TRUSTEDPARTS="/etc/apt/trusted.gpg.d"
-	eval $(apt-config shell TRUSTEDPARTS Dir::Etc::TrustedParts/d)
-	if [ -d "$TRUSTEDPARTS" ]; then
-		#echo "parts active"
-		for trusted in $(run-parts --list $TRUSTEDPARTS --regex '^.*\.gpg$'); do
-			#echo "part -> $trusted"
-			GPG="$GPG --keyring $trusted"
-		done
-	fi
+while [ -n "$1" ]; do
+   case "$1" in
+      --keyring)
+	 shift
+	 TRUSTEDFILE="$1"
+	 FORCED_KEYRING="$1"
+	 if [ -r "$TRUSTEDFILE" ] || [ "$2" = 'add' ] || [ "$2" = 'adv' ]; then
+	    GPG="$GPG --keyring $TRUSTEDFILE --primary-keyring $TRUSTEDFILE"
+	 else
+	    echo >&2 "Error: The specified keyring »$TRUSTEDFILE« is missing or not readable"
+	    exit 1
+	 fi
+	 shift
+	 ;;
+      --fakeroot)
+	 requires_root() { true; }
+	 shift
+	 ;;
+      --*)
+	 echo >&2 "Unknown option: $1"
+	 usage
+	 exit 1;;
+      *)
+	 break;;
+   esac
+done
+
+if [ -z "$TRUSTEDFILE" ]; then
+   TRUSTEDFILE="/etc/apt/trusted.gpg"
+   eval $(apt-config shell TRUSTEDFILE Apt::GPGV::TrustedKeyring)
+   eval $(apt-config shell TRUSTEDFILE Dir::Etc::Trusted/f)
+   if [ -r "$TRUSTEDFILE" ]; then
+      GPG="$GPG --keyring $TRUSTEDFILE"
+   fi
+   GPG="$GPG --primary-keyring $TRUSTEDFILE"
+   TRUSTEDPARTS="/etc/apt/trusted.gpg.d"
+   eval $(apt-config shell TRUSTEDPARTS Dir::Etc::TrustedParts/d)
+   if [ -d "$TRUSTEDPARTS" ]; then
+      # strip / suffix as gpg will double-slash in that case (#665411)
+      STRIPPED_TRUSTEDPARTS="${TRUSTEDPARTS%/}"
+      if [ "${STRIPPED_TRUSTEDPARTS}/" = "$TRUSTEDPARTS" ]; then
+	 TRUSTEDPARTS="$STRIPPED_TRUSTEDPARTS"
+      fi
+      for trusted in $(run-parts --list "$TRUSTEDPARTS" --regex '^.*\.gpg$'); do
+	 GPG="$GPG --keyring $trusted"
+      done
+   fi
 fi
-#echo "COMMAND: $GPG"
 
 command="$1"
 if [ -z "$command" ]; then
@@ -198,33 +315,40 @@ fi
 case "$command" in
     add)
         requires_root
+        init_keyring "$TRUSTEDFILE"
         $GPG --quiet --batch --import "$1"
         echo "OK"
         ;;
     del|rm|remove)
-        requires_root
-        $GPG --quiet --batch --delete-key --yes "$1"
-        echo "OK"
+        init_keyring "$TRUSTEDFILE"
+	remove_key "$1"
         ;;
     update)
+        init_keyring "$TRUSTEDFILE"
 	update
 	;;
     net-update)
+        init_keyring "$TRUSTEDFILE"
 	net_update
 	;;
     list)
+        init_keyring "$TRUSTEDFILE"
         $GPG --batch --list-keys
         ;;
     finger*)
+        init_keyring "$TRUSTEDFILE"
         $GPG --batch --fingerprint
         ;;
     export)
+        init_keyring "$TRUSTEDFILE"
         $GPG --armor --export "$1"
         ;;
     exportall)
+        init_keyring "$TRUSTEDFILE"
         $GPG --armor --export
         ;;
     adv*)
+        init_keyring "$TRUSTEDFILE"
         echo "Executing: $GPG $*"
         $GPG $*
         ;;
diff --git a/usr/bin/dpkg-maintscript-helper b/usr/bin/dpkg-maintscript-helper
--- a/usr/bin/dpkg-maintscript-helper
+++ b/usr/bin/dpkg-maintscript-helper
@@ -1,6 +1,6 @@
 #!/bin/sh
 #
-# Copyright © 2007,2011-2012 Guillem Jover <guillem@debian.org>
+# Copyright © 2007,2011-2013 Guillem Jover <guillem@debian.org>
 # Copyright © 2010 Raphaël Hertzog <hertzog@debian.org>
 # Copyright © 2008 Joey Hess <joeyh@debian.org>
 # Copyright © 2005 Scott James Remnant (original implementation on www.dpkg.org)
@@ -16,10 +16,10 @@
 # GNU General Public License for more details.
 #
 # You should have received a copy of the GNU General Public License
-# along with this program.  If not, see <http://www.gnu.org/licenses/>.
+# along with this program.  If not, see <https://www.gnu.org/licenses/>.
 
 # The conffile related functions are inspired by
-# http://wiki.debian.org/DpkgConffileHandling
+# https://wiki.debian.org/DpkgConffileHandling
 
 # This script is documented in dpkg-maintscript-helper(1)
 
@@ -32,14 +32,14 @@ rm_conffile() {
 	local PACKAGE="$3"
 	if [ "$LASTVERSION" = "--" ]; then
 		LASTVERSION=""
-		PACKAGE="$DPKG_MAINTSCRIPT_PACKAGE"
+		PACKAGE="$DPKG_MAINTSCRIPT_PACKAGE${DPKG_MAINTSCRIPT_ARCH:+:$DPKG_MAINTSCRIPT_ARCH}"
 	fi
 	if [ "$PACKAGE" = "--" -o -z "$PACKAGE" ]; then
-		PACKAGE="$DPKG_MAINTSCRIPT_PACKAGE"
+		PACKAGE="$DPKG_MAINTSCRIPT_PACKAGE${DPKG_MAINTSCRIPT_ARCH:+:$DPKG_MAINTSCRIPT_ARCH}"
 	fi
 	# Skip remaining parameters up to --
 	while [ "$1" != "--" -a $# -gt 0 ]; do shift; done
-	[ $# -gt 0 ] || badusage
+	[ $# -gt 0 ] || badusage "missing arguments after --"
 	shift
 
 	[ -n "$PACKAGE" ] || error "couldn't identify the package"
@@ -61,7 +61,7 @@ rm_conffile() {
 	postinst)
 		if [ "$1" = "configure" ] && [ -n "$2" ] &&
 		   dpkg --compare-versions "$2" le-nl "$LASTVERSION"; then
-			finish_rm_conffile $CONFFILE
+			finish_rm_conffile "$CONFFILE"
 		fi
 		;;
 	postrm)
@@ -72,7 +72,7 @@ rm_conffile() {
 		if [ "$1" = "abort-install" -o "$1" = "abort-upgrade" ] &&
 		   [ -n "$2" ] &&
 		   dpkg --compare-versions "$2" le-nl "$LASTVERSION"; then
-			abort_rm_conffile "$CONFFILE"
+			abort_rm_conffile "$CONFFILE" "$PACKAGE"
 		fi
 		;;
 	*)
@@ -86,16 +86,14 @@ prepare_rm_conffile() {
 	local PACKAGE="$2"
 
 	[ -e "$CONFFILE" ] || return 0
+	ensure_package_owns_file "$PACKAGE" "$CONFFILE" || return 0
 
 	local md5sum="$(md5sum $CONFFILE | sed -e 's/ .*//')"
 	local old_md5sum="$(dpkg-query -W -f='${Conffiles}' $PACKAGE | \
 		sed -n -e "\' $CONFFILE ' { s/ obsolete$//; s/.* //; p }")"
 	if [ "$md5sum" != "$old_md5sum" ]; then
-		echo "Obsolete conffile $CONFFILE has been modified by you."
-		echo "Saving as $CONFFILE.dpkg-bak ..."
 		mv -f "$CONFFILE" "$CONFFILE.dpkg-backup"
 	else
-		echo "Moving obsolete conffile $CONFFILE out of the way..."
 		mv -f "$CONFFILE" "$CONFFILE.dpkg-remove"
 	fi
 }
@@ -104,6 +102,8 @@ finish_rm_conffile() {
 	local CONFFILE="$1"
 
 	if [ -e "$CONFFILE.dpkg-backup" ]; then
+		echo "Obsolete conffile $CONFFILE has been modified by you."
+		echo "Saving as $CONFFILE.dpkg-bak ..."
 		mv -f "$CONFFILE.dpkg-backup" "$CONFFILE.dpkg-bak"
 	fi
 	if [ -e "$CONFFILE.dpkg-remove" ]; then
@@ -114,6 +114,9 @@ finish_rm_conffile() {
 
 abort_rm_conffile() {
 	local CONFFILE="$1"
+	local PACKAGE="$2"
+
+	ensure_package_owns_file "$PACKAGE" "$CONFFILE" || return 0
 
 	if [ -e "$CONFFILE.dpkg-remove" ]; then
 		echo "Reinstalling $CONFFILE that was moved away"
@@ -135,14 +138,14 @@ mv_conffile() {
 	local PACKAGE="$4"
 	if [ "$LASTVERSION" = "--" ]; then
 		LASTVERSION=""
-		PACKAGE="$DPKG_MAINTSCRIPT_PACKAGE"
+		PACKAGE="$DPKG_MAINTSCRIPT_PACKAGE${DPKG_MAINTSCRIPT_ARCH:+:$DPKG_MAINTSCRIPT_ARCH}"
 	fi
 	if [ "$PACKAGE" = "--" -o -z "$PACKAGE" ]; then
-		PACKAGE="$DPKG_MAINTSCRIPT_PACKAGE"
+		PACKAGE="$DPKG_MAINTSCRIPT_PACKAGE${DPKG_MAINTSCRIPT_ARCH:+:$DPKG_MAINTSCRIPT_ARCH}"
 	fi
 	# Skip remaining parameters up to --
 	while [ "$1" != "--" -a $# -gt 0 ]; do shift; done
-	[ $# -gt 0 ] || badusage
+	[ $# -gt 0 ] || badusage "missing arguments after --"
 	shift
 
 	[ -n "$PACKAGE" ] || error "couldn't identify the package"
@@ -164,14 +167,14 @@ mv_conffile() {
 	postinst)
 		if [ "$1" = "configure" ] && [ -n "$2" ] &&
 		   dpkg --compare-versions "$2" le-nl "$LASTVERSION"; then
-			finish_mv_conffile "$OLDCONFFILE" "$NEWCONFFILE"
+			finish_mv_conffile "$OLDCONFFILE" "$NEWCONFFILE" "$PACKAGE"
 		fi
 		;;
 	postrm)
 		if [ "$1" = "abort-install" -o "$1" = "abort-upgrade" ] &&
 		   [ -n "$2" ] &&
 		   dpkg --compare-versions "$2" le-nl "$LASTVERSION"; then
-			abort_mv_conffile "$OLDCONFFILE"
+			abort_mv_conffile "$OLDCONFFILE" "$PACKAGE"
 		fi
 		;;
 	*)
@@ -186,6 +189,8 @@ prepare_mv_conffile() {
 
 	[ -e "$CONFFILE" ] || return 0
 
+	ensure_package_owns_file "$PACKAGE" "$CONFFILE" || return 0
+
 	local md5sum="$(md5sum $CONFFILE | sed -e 's/ .*//')"
 	local old_md5sum="$(dpkg-query -W -f='${Conffiles}' $PACKAGE | \
 		sed -n -e "\' $CONFFILE ' { s/ obsolete$//; s/.* //; p }")"
@@ -197,10 +202,12 @@ prepare_mv_conffile() {
 finish_mv_conffile() {
 	local OLDCONFFILE="$1"
 	local NEWCONFFILE="$2"
+	local PACKAGE="$3"
 
 	rm -f $OLDCONFFILE.dpkg-remove
 
 	[ -e "$OLDCONFFILE" ] || return 0
+	ensure_package_owns_file "$PACKAGE" "$OLDCONFFILE" || return 0
 
 	echo "Preserving user changes to $NEWCONFFILE (renamed from $OLDCONFFILE)..."
 	mv -f "$NEWCONFFILE" "$NEWCONFFILE.dpkg-new"
@@ -209,6 +216,9 @@ finish_mv_conffile() {
 
 abort_mv_conffile() {
 	local CONFFILE="$1"
+	local PACKAGE="$2"
+
+	ensure_package_owns_file "$PACKAGE" "$CONFFILE" || return 0
 
 	if [ -e "$CONFFILE.dpkg-remove" ]; then
 		echo "Reinstalling $CONFFILE that was moved away"
@@ -216,7 +226,274 @@ abort_mv_conffile() {
 	fi
 }
 
+##
+## Functions to replace a symlink with a directory
+##
+symlink_to_dir() {
+	local SYMLINK="$1"
+	local SYMLINK_TARGET="$2"
+	local LASTVERSION="$3"
+	local PACKAGE="$4"
+
+	if [ "$LASTVERSION" = "--" ]; then
+		LASTVERSION=""
+		PACKAGE="$DPKG_MAINTSCRIPT_PACKAGE${DPKG_MAINTSCRIPT_ARCH:+:$DPKG_MAINTSCRIPT_ARCH}"
+	fi
+	if [ "$PACKAGE" = "--" -o -z "$PACKAGE" ]; then
+		PACKAGE="$DPKG_MAINTSCRIPT_PACKAGE${DPKG_MAINTSCRIPT_ARCH:+:$DPKG_MAINTSCRIPT_ARCH}"
+	fi
+
+	# Skip remaining parameters up to --
+	while [ "$1" != "--" -a $# -gt 0 ]; do shift; done
+	[ $# -gt 0 ] || badusage "missing arguments after --"
+	shift
+
+	[ -n "$DPKG_MAINTSCRIPT_NAME" ] || \
+		error "environment variable DPKG_MAINTSCRIPT_NAME is required"
+	[ -n "$PACKAGE" ] || error "cannot identify the package"
+	[ -n "$SYMLINK" ] || error "symlink parameter is missing"
+	[ "${SYMLINK#/}" = "$SYMLINK" ] && \
+		error "symlink pathname is not an absolute path"
+	[ -n "$SYMLINK_TARGET" ] || error "original symlink target is missing"
+	[ -n "$1" ] || error "maintainer script parameters are missing"
+
+	debug "Executing $0 symlink_to_dir in $DPKG_MAINTSCRIPT_NAME" \
+	      "of $DPKG_MAINTSCRIPT_PACKAGE"
+	debug "SYMLINK=$SYMLINK -> $SYMLINK_TARGET PACKAGE=$PACKAGE" \
+	      "LASTVERSION=$LASTVERSION ACTION=$1 PARAM=$2"
+
+	case "$DPKG_MAINTSCRIPT_NAME" in
+	preinst)
+		if [ "$1" = "install" -o "$1" = "upgrade" ] &&
+		   [ -n "$2" ] && [ -h "$SYMLINK" ] &&
+		   symlink_match "$SYMLINK" "$SYMLINK_TARGET" &&
+		   dpkg --compare-versions "$2" le-nl "$LASTVERSION"; then
+			mv -f "$SYMLINK" "${SYMLINK}.dpkg-backup"
+		fi
+		;;
+	postinst)
+		# We cannot bail depending on the version, as here we only
+		# know what was the last configured version, and we might
+		# have been unpacked, then upgraded with an unpack and thus
+		# never been configured before.
+		if [ "$1" = "configure" ] && [ -h "${SYMLINK}.dpkg-backup" ] &&
+		   symlink_match "${SYMLINK}.dpkg-backup" "$SYMLINK_TARGET"
+		then
+			rm -f "${SYMLINK}.dpkg-backup"
+		fi
+		;;
+	postrm)
+		if [ "$1" = "purge" ] && [ -h "${SYMLINK}.dpkg-backup" ]; then
+		    rm -f "${SYMLINK}.dpkg-backup"
+		fi
+		if [ "$1" = "abort-install" -o "$1" = "abort-upgrade" ] &&
+		   [ -n "$2" ] &&
+		   [ ! -e "$SYMLINK" ] && [ -h "${SYMLINK}.dpkg-backup" ] &&
+		   symlink_match "${SYMLINK}.dpkg-backup" "$SYMLINK_TARGET" &&
+		   dpkg --compare-versions "$2" le-nl "$LASTVERSION"; then
+			echo "Restoring backup of $SYMLINK ..."
+			mv "${SYMLINK}.dpkg-backup" "$SYMLINK"
+		fi
+		;;
+	*)
+		debug "$0 symlink_to_dir not required in $DPKG_MAINTSCRIPT_NAME"
+		;;
+	esac
+}
+
+##
+## Functions to replace a directory with a symlink
+##
+dir_to_symlink() {
+	local PATHNAME="$1"
+	local SYMLINK_TARGET="$2"
+	local LASTVERSION="$3"
+	local PACKAGE="$4"
+
+	if [ "$LASTVERSION" = "--" ]; then
+		LASTVERSION=""
+		PACKAGE="$DPKG_MAINTSCRIPT_PACKAGE${DPKG_MAINTSCRIPT_ARCH:+:$DPKG_MAINTSCRIPT_ARCH}"
+	fi
+	if [ "$PACKAGE" = "--" -o -z "$PACKAGE" ]; then
+		PACKAGE="$DPKG_MAINTSCRIPT_PACKAGE${DPKG_MAINTSCRIPT_ARCH:+:$DPKG_MAINTSCRIPT_ARCH}"
+	fi
+
+	# Skip remaining parameters up to --
+	while [ "$1" != "--" -a $# -gt 0 ]; do shift; done
+	[ $# -gt 0 ] || badusage "missing arguments after --"
+	shift
+
+	[ -n "$DPKG_MAINTSCRIPT_NAME" ] || \
+		error "environment variable DPKG_MAINTSCRIPT_NAME is required"
+	[ -n "$PACKAGE" ] || error "cannot identify the package"
+	[ -n "$PATHNAME" ] || error "directory parameter is missing"
+	[ "${PATHNAME#/}" = "$PATHNAME" ] && \
+		error "directory parameter is not an absolute path"
+	[ -n "$SYMLINK_TARGET" ] || error "new symlink target is missing"
+	[ -n "$1" ] || error "maintainer script parameters are missing"
+
+	debug "Executing $0 dir_to_symlink in $DPKG_MAINTSCRIPT_NAME" \
+	      "of $DPKG_MAINTSCRIPT_PACKAGE"
+	debug "PATHNAME=$PATHNAME SYMLINK_TARGET=$SYMLINK_TARGET" \
+	      "PACKAGE=$PACKAGE LASTVERSION=$LASTVERSION ACTION=$1 PARAM=$2"
+
+	case "$DPKG_MAINTSCRIPT_NAME" in
+	preinst)
+		if [ "$1" = "install" -o "$1" = "upgrade" ] &&
+		   [ -n "$2" ] &&
+		   [ ! -h "$PATHNAME" ] && [ -d "$PATHNAME" ] &&
+		   dpkg --compare-versions "$2" le-nl "$LASTVERSION"; then
+			prepare_dir_to_symlink "$PACKAGE" "$PATHNAME"
+		fi
+		;;
+	postinst)
+		# We cannot bail depending on the version, as here we only
+		# know what was the last configured version, and we might
+		# have been unpacked, then upgraded with an unpack and thus
+		# never been configured before.
+		if [ "$1" = "configure" ] &&
+		   [ -d "${PATHNAME}.dpkg-backup" ] &&
+		   [ ! -h "$PATHNAME" ] && [ -d "$PATHNAME" ] &&
+		   [ -f "$PATHNAME/.dpkg-staging-dir" ]; then
+			finish_dir_to_symlink "$PATHNAME" "$SYMLINK_TARGET"
+		fi
+		;;
+	postrm)
+		if [ "$1" = "purge" ] && [ -d "${PATHNAME}.dpkg-backup" ]; then
+		    rm -rf "${PATHNAME}.dpkg-backup"
+		fi
+		if [ "$1" = "abort-install" -o "$1" = "abort-upgrade" ] &&
+		   [ -n "$2" ] &&
+		   [ -d "${PATHNAME}.dpkg-backup" ] &&
+		   [ \( ! -h "$PATHNAME" -a -d "$PATHNAME" -a \
+		        -f "$PATHNAME/.dpkg-staging-dir" \) -o \
+		     \( -h "$PATHNAME" -a \
+		        \( "$(readlink $PATHNAME)" = "$SYMLINK_TARGET" -o \
+		           "$(readlink -f $PATHNAME)" = "$SYMLINK_TARGET" \) \) ] &&
+		   dpkg --compare-versions "$2" le-nl "$LASTVERSION"; then
+			abort_dir_to_symlink "$PATHNAME"
+		fi
+		;;
+	*)
+		debug "$0 dir_to_symlink not required in $DPKG_MAINTSCRIPT_NAME"
+		;;
+	esac
+}
+
+prepare_dir_to_symlink()
+{
+	local PACKAGE="$1"
+	local PATHNAME="$2"
+
+	# If there are conffiles we should not perform the switch.
+	if dpkg-query -W -f='${Conffiles}' "$PACKAGE" | \
+	   grep -q "$PATHNAME/."; then
+		error "directory '$PATHNAME' contains conffiles," \
+		      "cannot switch to symlink"
+	fi
+
+	# If there are locally created files or files owned by another package
+	# we should not perform the switch.
+	find "$PATHNAME" -print0 | xargs -0 -n1 sh -c '
+		package="$1"
+		file="$2"
+		if ! dpkg-query -L "$package" | grep -q -x "$file"; then
+			exit 1
+		fi
+		exit 0
+	' check-files-ownership "$PACKAGE" || \
+		error "directory '$PATHNAME' contains files not owned by" \
+		      "package $PACKAGE, cannot switch to symlink"
+
+	# At this point, we know that the directory either contains no files,
+	# or only non-conffiles owned by the package.
+	#
+	# To do the switch we cannot simply replace it with the final symlink
+	# just yet, because dpkg needs to remove any file present in the old
+	# package that have disappeared in the new one, and we do not want to
+	# lose files resolving to the same pathname in the symlink target.
+	#
+	# We cannot replace the directory with a staging symlink either,
+	# because dpkg will update symlinks to their new target.
+	#
+	# So we need to create a staging directory, to avoid removing files
+	# from other packages, and to trap any new files in the directory
+	# to move them to their correct place later on.
+	mv -f "$PATHNAME" "${PATHNAME}.dpkg-backup"
+	mkdir "$PATHNAME"
+
+	# Mark it as a staging directory, so that we can track things.
+	touch "$PATHNAME/.dpkg-staging-dir"
+}
+
+finish_dir_to_symlink()
+{
+	local PATHNAME="$1"
+	local SYMLINK_TARGET="$2"
+
+	# Move the contents of the staging directory to the symlink target,
+	# as those are all new files installed between this package being
+	# unpacked and configured.
+	local ABS_SYMLINK_TARGET
+	if [ "${SYMLINK_TARGET#/}" = "$SYMLINK_TARGET" ]; then
+		ABS_SYMLINK_TARGET="$(dirname "$PATHNAME")/$SYMLINK_TARGET"
+	else
+		ABS_SYMLINK_TARGET="$SYMLINK_TARGET"
+	fi
+	rm "$PATHNAME/.dpkg-staging-dir"
+	find "$PATHNAME" -mindepth 1 -print0 | \
+		xargs -0 -i% mv -f "%" "$ABS_SYMLINK_TARGET/"
+
+	# Remove the staging directory.
+	rmdir "$PATHNAME"
+
+	# Do the actual switch.
+	ln -s "$SYMLINK_TARGET" "$PATHNAME"
+
+	# We are left behind the old files owned by this package in the backup
+	# directory, just remove it.
+	rm -rf "${PATHNAME}.dpkg-backup"
+}
+
+abort_dir_to_symlink()
+{
+	local PATHNAME="$1"
+
+	echo "Restoring backup of $PATHNAME ..."
+	if [ -h "$PATHNAME" ]; then
+		rm -f "$PATHNAME"
+	else
+		# The staging directory must be empty, as no other package
+		# should have been unpacked inbetween.
+		rm -f "$PATHNAME/.dpkg-staging-dir"
+		rmdir "$PATHNAME"
+	fi
+
+	mv "${PATHNAME}.dpkg-backup" "$PATHNAME"
+}
+
 # Common functions
+ensure_package_owns_file() {
+	local PACKAGE="$1"
+	local FILE="$2"
+
+	if ! dpkg-query -L "$PACKAGE" | grep -q -x "$FILE"; then
+		debug "File '$FILE' not owned by package " \
+		      "'$PACKAGE', skipping $command"
+		return 1
+	fi
+	return 0
+}
+
+symlink_match()
+{
+	local SYMLINK="$1"
+	local SYMLINK_TARGET="$2"
+
+	[ "$(readlink $SYMLINK)" = "$SYMLINK_TARGET" ] || \
+	[ "$(readlink -f $SYMLINK)" = "$SYMLINK_TARGET" ]
+}
+
 debug() {
 	if [ -n "$DPKG_DEBUG" ]; then
 		echo "DEBUG: $PROGNAME: $*" >&2
@@ -224,12 +501,12 @@ debug() {
 }
 
 error() {
-	echo "$PROGNAME: error: $1" >&2
+	echo "$PROGNAME: error: $*" >&2
 	exit 1
 }
 
 warning() {
-	echo "$PROGNAME: warning: $1" >&2
+	echo "$PROGNAME: warning: $*" >&2
 }
 
 usage() {
@@ -244,13 +521,21 @@ Commands:
 	postrm.
   mv_conffile <old-conf> <new-conf> [<last-version> [<package>]]
 	Rename a conffile. Must be called in preinst, postinst and postrm.
+  symlink_to_dir <pathname> <old-symlink-target> [<last-version> [<package>]]
+	Replace a symlink with a directory. Must be called in preinst,
+	postinst and postrm.
+  dir_to_symlink <pathname> <new-symlink-target> [<last-version> [<package>]]
+	Replace a directory with a symlink. Must be called in preinst,
+	postinst and postrm.
   help
 	Display this usage information.
 END
 }
 
 badusage() {
-	usage
+	echo "$PROGNAME: error: $1" >&2
+	echo >&2
+	echo "Use '$PROGNAME help' for program usage information." >&2
 	exit 1
 }
 
@@ -258,15 +543,15 @@ badusage() {
 set -e
 
 PROGNAME=$(basename $0)
-version="1.16.10"
+version="1.17.24"
 command="$1"
-[ $# -gt 0 ] || badusage
+[ $# -gt 0 ] || badusage "missing command"
 shift
 
 case "$command" in
 supports)
 	case "$1" in
-	rm_conffile|mv_conffile)
+	rm_conffile|mv_conffile|symlink_to_dir|dir_to_symlink)
 		code=0
 		;;
 	*)
@@ -289,6 +574,12 @@ rm_conffile)
 mv_conffile)
 	mv_conffile "$@"
 	;;
+symlink_to_dir)
+	symlink_to_dir "$@"
+	;;
+dir_to_symlink)
+	dir_to_symlink "$@"
+	;;
 --help|help|-?)
 	usage
 	;;
@@ -301,13 +592,8 @@ mv_conffile)
 	END
 	;;
 *)
-	cat >&2 <<-END
-	$PROGNAME: error: command $command is unknown
-	Hint: upgrading dpkg to a newer version might help.
-
-	END
-	usage
-	exit 1
+	badusage "command $command is unknown
+Hint: upgrading dpkg to a newer version might help."
 esac
 
 exit 0
diff --git a/usr/lib/git-core/git-submodule b/usr/lib/git-core/git-submodule
--- a/usr/lib/git-core/git-submodule
+++ b/usr/lib/git-core/git-submodule
@@ -9,7 +9,7 @@ USAGE="[--quiet] add [-b <branch>] [-f|--force] [--name <name>] [--reference <re
    or: $dashless [--quiet] status [--cached] [--recursive] [--] [<path>...]
    or: $dashless [--quiet] init [--] [<path>...]
    or: $dashless [--quiet] deinit [-f|--force] [--] <path>...
-   or: $dashless [--quiet] update [--init] [--remote] [-N|--no-fetch] [-f|--force] [--rebase] [--reference <repository>] [--merge] [--recursive] [--] [<path>...]
+   or: $dashless [--quiet] update [--init] [--remote] [-N|--no-fetch] [-f|--force] [--checkout|--merge|--rebase] [--reference <repository>] [--recursive] [--] [<path>...]
    or: $dashless [--quiet] summary [--cached|--files] [--summary-limit <n>] [commit] [--] [<path>...]
    or: $dashless [--quiet] foreach [--recursive] <command>
    or: $dashless [--quiet] sync [--recursive] [--] [<path>...]"
@@ -235,11 +235,17 @@ module_name()
 		sed -n -e 's|^submodule\.\(.*\)\.path '"$re"'$|\1|p' )
 	test -z "$name" &&
 	die "$(eval_gettext "No submodule mapping found in .gitmodules for path '\$sm_path'")"
-	echo "$name"
+	printf '%s\n' "$name"
 }
 
 #
 # Clone a submodule
+#
+# $1 = submodule path
+# $2 = submodule name
+# $3 = URL to clone
+# $4 = reference repository to reuse (empty for independent)
+# $5 = depth argument for shallow clones (empty for deep)
 #
 # Prior to calling, cmd_update checks that a possibly existing
 # path is not a git repository.
@@ -285,9 +291,6 @@ module_clone()
 	# resolve any symlinks that might be present in $PWD
 	a=$(cd_to_toplevel && cd "$gitdir" && pwd)/
 	b=$(cd_to_toplevel && cd "$sm_path" && pwd)/
-	# normalize Windows-style absolute paths to POSIX-style absolute paths
-	case $a in [a-zA-Z]:/*) a=/${a%%:*}${a#*:} ;; esac
-	case $b in [a-zA-Z]:/*) b=/${b%%:*}${b#*:} ;; esac
 	# Remove all common leading directories after a sanity check
 	if test "${a#$b}" != "$a" || test "${b#$a}" != "$b"; then
 		die "$(eval_gettext "Gitdir '\$a' is part of the submodule path '\$b' or vice versa")"
@@ -302,10 +305,10 @@ module_clone()
 	b=${b%/}
 
 	# Turn each leading "*/" component into "../"
-	rel=$(echo $b | sed -e 's|[^/][^/]*|..|g')
-	echo "gitdir: $rel/$a" >"$sm_path/.git"
+	rel=$(printf '%s\n' "$b" | sed -e 's|[^/][^/]*|..|g')
+	printf '%s\n' "gitdir: $rel/$a" >"$sm_path/.git"
 
-	rel=$(echo $a | sed -e 's|[^/][^/]*|..|g')
+	rel=$(printf '%s\n' "$a" | sed -e 's|[^/][^/]*|..|g')
 	(clear_local_git_env; cd "$sm_path" && GIT_WORK_TREE=. git config core.worktree "$rel/$b")
 }
 
@@ -386,11 +389,11 @@ cmd_add()
 	sm_path=$2
 
 	if test -z "$sm_path"; then
-		sm_path=$(echo "$repo" |
+		sm_path=$(printf '%s\n' "$repo" |
 			sed -e 's|/$||' -e 's|:*/*\.git$||' -e 's|.*[/:]||g')
 	fi
 
-	if test -z "$repo" -o -z "$sm_path"; then
+	if test -z "$repo" || test -z "$sm_path"; then
 		usage
 	fi
 
@@ -447,7 +450,7 @@ Use -f if you really want to add it." >&2
 	# perhaps the path exists and is already a git repo, else clone it
 	if test -e "$sm_path"
 	then
-		if test -d "$sm_path"/.git -o -f "$sm_path"/.git
+		if test -d "$sm_path"/.git || test -f "$sm_path"/.git
 		then
 			eval_gettextln "Adding existing repo at '\$sm_path' to the index"
 		else
@@ -805,17 +808,10 @@ cmd_update()
 			update_module=$update
 		else
 			update_module=$(git config submodule."$name".update)
-			case "$update_module" in
-			'')
-				;; # Unset update mode
-			checkout | rebase | merge | none)
-				;; # Known update modes
-			!*)
-				;; # Custom update command
-			*)
-				die "$(eval_gettext "Invalid update mode '$update_module' for submodule '$name'")"
-				;;
-			esac
+			if test -z "$update_module"
+			then
+				update_module="checkout"
+			fi
 		fi
 
 		displaypath=$(relative_path "$prefix$sm_path")
@@ -836,7 +832,7 @@ Maybe you want to use 'update --init'?")"
 			continue
 		fi
 
-		if ! test -d "$sm_path"/.git -o -f "$sm_path"/.git
+		if ! test -d "$sm_path"/.git && ! test -f "$sm_path"/.git
 		then
 			module_clone "$sm_path" "$name" "$url" "$reference" "$depth" || exit
 			cloned_modules="$cloned_modules;$name"
@@ -861,11 +857,11 @@ Maybe you want to use 'update --init'?")"
 			die "$(eval_gettext "Unable to find current ${remote_name}/${branch} revision in submodule path '\$sm_path'")"
 		fi
 
-		if test "$subsha1" != "$sha1" -o -n "$force"
+		if test "$subsha1" != "$sha1" || test -n "$force"
 		then
 			subforce=$force
 			# If we don't already have a -f flag and the submodule has never been checked out
-			if test -z "$subsha1" -a -z "$force"
+			if test -z "$subsha1" && test -z "$force"
 			then
 				subforce="-f"
 			fi
@@ -884,11 +880,16 @@ Maybe you want to use 'update --init'?")"
 			case ";$cloned_modules;" in
 			*";$name;"*)
 				# then there is no local change to integrate
-				update_module= ;;
+				update_module=checkout ;;
 			esac
 
 			must_die_on_failure=
 			case "$update_module" in
+			checkout)
+				command="git checkout $subforce -q"
+				die_msg="$(eval_gettext "Unable to checkout '\$sha1' in submodule path '\$displaypath'")"
+				say_msg="$(eval_gettext "Submodule path '\$displaypath': checked out '\$sha1'")"
+				;;
 			rebase)
 				command="git rebase"
 				die_msg="$(eval_gettext "Unable to rebase '\$sha1' in submodule path '\$displaypath'")"
@@ -908,10 +909,7 @@ Maybe you want to use 'update --init'?")"
 				must_die_on_failure=yes
 				;;
 			*)
-				command="git checkout $subforce -q"
-				die_msg="$(eval_gettext "Unable to checkout '\$sha1' in submodule path '\$displaypath'")"
-				say_msg="$(eval_gettext "Submodule path '\$displaypath': checked out '\$sha1'")"
-				;;
+				die "$(eval_gettext "Invalid update mode '$update_module' for submodule '$name'")"
 			esac
 
 			if (clear_local_git_env; cd "$sm_path" && $command "$sha1")
@@ -1033,7 +1031,7 @@ cmd_summary() {
 	then
 		head=$rev
 		test $# = 0 || shift
-	elif test -z "$1" -o "$1" = "HEAD"
+	elif test -z "$1" || test "$1" = "HEAD"
 	then
 		# before the first commit: compare with an empty tree
 		head=$(git hash-object -w -t tree --stdin </dev/null)
@@ -1058,17 +1056,21 @@ cmd_summary() {
 		while read mod_src mod_dst sha1_src sha1_dst status sm_path
 		do
 			# Always show modules deleted or type-changed (blob<->module)
-			test $status = D -o $status = T && echo "$sm_path" && continue
+			if test "$status" = D || test "$status" = T
+			then
+				printf '%s\n' "$sm_path"
+				continue
+			fi
 			# Respect the ignore setting for --for-status.
 			if test -n "$for_status"
 			then
 				name=$(module_name "$sm_path")
 				ignore_config=$(get_submodule_config "$name" ignore none)
-				test $status != A -a $ignore_config = all && continue
+				test $status != A && test $ignore_config = all && continue
 			fi
 			# Also show added or modified modules which are checked out
 			GIT_DIR="$sm_path/.git" git-rev-parse --git-dir >/dev/null 2>&1 &&
-			echo "$sm_path"
+			printf '%s\n' "$sm_path"
 		done
 	)
 
@@ -1124,7 +1126,7 @@ cmd_summary() {
 		*)
 			errmsg=
 			total_commits=$(
-			if test $mod_src = 160000 -a $mod_dst = 160000
+			if test $mod_src = 160000 && test $mod_dst = 160000
 			then
 				range="$sha1_src...$sha1_dst"
 			elif test $mod_src = 160000
@@ -1161,7 +1163,7 @@ cmd_summary() {
 			# i.e. deleted or changed to blob
 			test $mod_dst = 160000 && echo "$errmsg"
 		else
-			if test $mod_src = 160000 -a $mod_dst = 160000
+			if test $mod_src = 160000 && test $mod_dst = 160000
 			then
 				limit=
 				test $summary_limit -gt 0 && limit="-$summary_limit"
@@ -1232,7 +1234,11 @@ cmd_status()
 			say "U$sha1 $displaypath"
 			continue
 		fi
-		if test -z "$url" || ! test -d "$sm_path"/.git -o -f "$sm_path"/.git
+		if test -z "$url" ||
+		{
+			! test -d "$sm_path"/.git &&
+			! test -f "$sm_path"/.git
+		}
 		then
 			say "-$sha1 $displaypath"
 			continue;
@@ -1305,7 +1311,7 @@ cmd_sync()
 		./*|../*)
 			# rewrite foo/bar as ../.. to find path from
 			# submodule work tree to superproject work tree
-			up_path="$(echo "$sm_path" | sed "s/[^/][^/]*/../g")" &&
+			up_path="$(printf '%s\n' "$sm_path" | sed "s/[^/][^/]*/../g")" &&
 			# guarantee a trailing /
 			up_path=${up_path%/}/ &&
 			# path from submodule work tree to submodule origin repo
@@ -1401,7 +1407,7 @@ then
 fi
 
 # "--cached" is accepted only by "status" and "summary"
-if test -n "$cached" && test "$command" != status -a "$command" != summary
+if test -n "$cached" && test "$command" != status && test "$command" != summary
 then
 	usage
 fi
diff --git a/usr/share/initramfs-tools/hooks/intel_microcode b/usr/share/initramfs-tools/hooks/intel_microcode
--- a/usr/share/initramfs-tools/hooks/intel_microcode
+++ b/usr/share/initramfs-tools/hooks/intel_microcode
@@ -1,10 +1,12 @@
 #!/bin/sh
-# intel-microcode initramfs-tools hook script
-# Copyright (C) 2012 Henrique de Moraes Holschuh <hmh@hmh.eng.br>
-# Released under the GPL v2 or later license
+# intel-microcode initramfs-tools hook script version 3
+# Copyright (C) 2012-2014 Henrique de Moraes Holschuh <hmh@debian.org>
+# Released under the GNU GPL v2 or later license
 #
-# Generates a copy of the minimal microcode for the current system if
-# possible, and installs it in the initramfs.
+# Generates a copy of the Intel microcode (by default tailored to the
+# running system), and installs it in the early initramfs.
+#
+# iucode_tool v1.0 or later is required.
 #
 
 PREREQ=""
@@ -27,7 +29,7 @@ esac
 verbose()
 {
 	if [ "${verbose}" = "y" ] ; then
-		echo "intel-microcode: $@"
+		echo "intel-microcode: $*"
 	fi
 	:
 }
@@ -39,52 +41,110 @@ else
 fi
 
 IUCODE_TOOL=$(command -v iucode_tool)
-if [ -z "${IUCODE_TOOL}" -a -x /usr/sbin/iucode_tool ] ; then
+if [ -z "${IUCODE_TOOL}" ] && [ -x /usr/sbin/iucode_tool ] ; then
 	IUCODE_TOOL=/usr/sbin/iucode_tool
 fi
 
 IUCODE_FW_DIR=/lib/firmware/intel-ucode
+IUCODE_TOOL_INITRAMFS=auto
 IUCODE_TOOL_EXTRA_OPTIONS=
 IUCODE_TOOL_SCANCPUS=yes
 [ -r ${IUCODE_CONFIG} ] && . ${IUCODE_CONFIG}
 
+[ -z "${IUCODE_TOOL_INITRAMFS}" ] && IUCODE_TOOL_INITRAMFS=no
+
+case "${IUCODE_TOOL_INITRAMFS}" in
+    no|0)
+	verbose "intel-microcode: disabled by ${IUCODE_CONFIG}"
+	exit 0
+	;;
+    auto|early)
+	;;
+    yes|1)
+	IUCODE_TOOL_INITRAMFS=early
+	echo "W: intel-microcode: initramfs mode not supported, using early initramfs mode" >&2
+	;;
+    *)
+	echo "E: intel-microcode: invalid IUCODE_TOOL_INITRAMFS, using automatic mode" >&2
+	IUCODE_TOOL_INITRAMFS=auto
+esac
+
+# don't do anything unless there's an Intel processor in the system in auto mode
+if [ "${IUCODE_TOOL_INITRAMFS}" = "auto" ] ; then
+	grep -q "^vendor_id[[:blank:]]*:[[:blank:]]*.*GenuineIntel" /proc/cpuinfo || {
+		verbose "no Intel processors detected, nothing to do"
+		exit 0
+	}
+fi
+
+# we require iucode_tool, but something is broken
 if [ ! -x "${IUCODE_TOOL}" ] ; then
-	verbose "iucode_tool not found, advanced functionality not available"
-	IUCODE_TOOL=
+	echo "E: intel-microcode: cannot run iucode_tool!" >&2
+	exit 0
 fi
 
-if [ -z "${IUCODE_TOOL}" -o "${IUCODE_TOOL_SCANCPUS}" != "yes" ] ; then
-	verbose "Adding microcode for all Intel processor models"
+# Blacklist all kernel versions before v3.10, as they don't support early
+# initramfs mode.
+#
+# This doesn't blacklist early 3.10 kernels in the LTS branches, we don't have
+# enough information at the initramfs-tools layer, due to the way Debian and
+# Ubuntu version kernel packages.
+if dpkg --compare-versions "${version}" lt 3.10 ; then
+       echo "E: intel-microcode: unsupported kernel version!" >&2
+       exit 0
+fi
+
+if [ "${IUCODE_TOOL_SCANCPUS}" != "yes" ] ; then
+	verbose "adding microcode for either all or selected Intel processor models"
 else
-	verbose "Adding microcode for currently online Intel processors"
-	grep -q cpu/cpuid /proc/devices || modprobe cpuid
-	if grep -q cpu/cpuid /proc/devices ; then
-		IUCODE_TOOL_OPTIONS="${IUCODE_TOOL_OPTIONS} --scan-system"
-	else
-		# compatibility with iucode-tool << 0.8.2
-		echo "intel-microcode: cpuid MSR kernel support missing"
-		echo "intel-microcode: disabling IUCODE_TOOL_SCANCPUS option"
-	fi
+	verbose "adding microcode for currently online and selected Intel processors"
+	grep -q cpu/cpuid /proc/devices || modprobe -q cpuid
+	IUCODE_TOOL_OPTIONS="${IUCODE_TOOL_OPTIONS} --scan-system"
 fi
 
-# Generate firmware dir
-mkdir -m 755 -p "${DESTDIR}${IUCODE_FW_DIR}"
+# paranoia
+[ -z "${DESTDIR}" ] && {
+	echo "E: intel-microcode: DESTDIR empty!" >&2
+	exit 1
+}
+[ -z "${IUCODE_FW_DIR}" ] && {
+	echo "E: intel-microcode: IUCODE_FW_DIR empty!" >&2
+	exit 1
+}
 
-if [ -x "${IUCODE_TOOL}" ] ; then
-	( find /usr/share/misc -maxdepth 1 -type f -name 'intel-microcode*' -print0 ;
-	  find "${IUCODE_FW_DIR}" -maxdepth 0 -type d -print0 ) 2>/dev/null | \
-		xargs -0 -r -x \
-		   ${IUCODE_TOOL} ${IUCODE_TOOL_OPTIONS} \
-			--write-firmware="${DESTDIR}${IUCODE_FW_DIR}" \
-			${IUCODE_TOOL_EXTRA_OPTIONS}
-else
-	cp -rf "${IUCODE_FW_DIR}/." "${DESTDIR}${IUCODE_FW_DIR}/."
-fi
+# include the microcode module in the initramfs for logging purposes, but
+# ensure it will have no microcode data files to load.  This is also a safety
+# net: we don't want it to be acidentally loaded outside the initramfs.
+#
+# This shouldn't be expensive, as the in-kernel firmware loader is quite
+# fast at detecting missing data files and doesn't wait for them.
+#
+# note: force_load will load a blacklisted module. We depend on that behavior.
+force_load microcode
+[ -d "${DESTDIR}${IUCODE_FW_DIR}" ] && rm -fr "${DESTDIR}${IUCODE_FW_DIR}"
 
-if ! rmdir "${DESTDIR}${IUCODE_FW_DIR}" 2>/dev/null ; then
-	# The directory was not empty, so we have work to do
-	verbose "installing Intel processor microcode update support into initramfs..."
-	force_load microcode
-fi
+# generate early initramfs image and prepend
+verbose "using early initramfs microcode update mode (Linux v3.10 and later)..."
+EFW=$(mktemp "${TMPDIR:-/var/tmp}/mkinitramfs-EFW_XXXXXXXXXX") || {
+	echo "E: intel-microcode: cannot create temporary file" >&2
+	exit 1
+    }
+( find /usr/share/misc -maxdepth 1 -type f -name 'intel-microcode*' -print0 ;
+  find "${IUCODE_FW_DIR}" -maxdepth 0 -type d -print0 ) 2>/dev/null \
+| xargs -0 -r -x ${IUCODE_TOOL} ${IUCODE_TOOL_OPTIONS} \
+		--write-earlyfw="${EFW}" --overwrite \
+		${IUCODE_TOOL_EXTRA_OPTIONS} \
+&& prepend_earlyinitramfs "${EFW}" && {
+	rm "${EFW}"
+	exit 0
+}
+
+# usually we get here when initramfs-tools is missing prepend_earlyinitramfs()
+# or when iucode_tool does not support --write-earlyfw, i.e. when old versions
+# of these tools are installed.
+
+rm "${EFW}" || true
+
+echo "E: intel-microcode: failed to create or prepend the early initramfs to the initramfs" >&2
 
 :
diff --git a/var/lib/dpkg/info/python2.7-minimal.postinst b/var/lib/dpkg/info/python2.7-minimal.postinst
--- a/var/lib/dpkg/info/python2.7-minimal.postinst
+++ b/var/lib/dpkg/info/python2.7-minimal.postinst
@@ -8,10 +8,6 @@ if [ ! -f /etc/python2.7/sitecustomize.py ]; then
 EOF
 fi
 
-syssite=/usr/lib/python2.7/site-packages
-localsite=/usr/local/lib/python2.7/dist-packages
-syslink=../../${localsite#/usr/*}
-
 case "$1" in
     configure)
         # Create empty directories in /usr/local
@@ -20,14 +16,12 @@ case "$1" in
             chmod 2775 /usr/local/lib/python2.7 2> /dev/null || true
             chown root:staff /usr/local/lib/python2.7 2> /dev/null || true
         fi
+	localsite=/usr/local/lib/python2.7/dist-packages
         if [ ! -e $localsite ]; then
             mkdir -p $localsite 2> /dev/null || true
             chmod 2775 $localsite 2> /dev/null || true
             chown root:staff $localsite 2> /dev/null || true
         fi
-	#if [ ! -h $syssite ]; then
-	#    ln -s $syslink $syssite
-	#fi
 
 	if which update-binfmts >/dev/null; then
 	    update-binfmts --import python2.7
@@ -37,13 +31,21 @@ case "$1" in
 esac
 
 if [ "$1" = configure ]; then
-    (
-    files=$(dpkg -L python2.7-minimal | sed -n '/^\/usr\/lib\/python2.7\/.*\.py$/p')
-	python2.7 /usr/lib/python2.7/py_compile.py $files
+    if ls -L /usr/lib/python2.7/sitecustomize.py >/dev/null 2>&1; then
+	filt='cat'
+    else
+	filt='fgrep -v sitecustomize.py'
+    fi
+    files=$(dpkg -L libpython2.7-minimal:i386 \
+		| sed -n '/^\/usr\/lib\/python2.7\/.*\.py$/p' | $filt)
+    if [ -n "$files" ]; then
+	python2.7 -E -S /usr/lib/python2.7/py_compile.py $files
 	if grep -sq '^byte-compile[^#]*optimize' /etc/python/debian_config; then
-	    python2.7 -O /usr/lib/python2.7/py_compile.py $files
+	    python2.7 -E -S -O /usr/lib/python2.7/py_compile.py $files
 	fi
-    )
+    else
+	echo >&2 "python2.7-minimal: can't get files for byte-compilation"
+    fi
     bc=no
     if [ -z "$2" ] || dpkg --compare-versions "$2" lt 2.7-9 \
         || [ -f /var/lib/python/python2.7_installed ]; then
diff --git a/var/lib/dpkg/info/systemd.postinst b/var/lib/dpkg/info/systemd.postinst
--- a/var/lib/dpkg/info/systemd.postinst
+++ b/var/lib/dpkg/info/systemd.postinst
@@ -3,23 +3,26 @@
 set -e
 
 _systemctl() {
-    if [ -e /sys/fs/cgroup/systemd ]; then
+    if [ -d /run/systemd/system ]; then
         systemctl "$@"
     fi
 }
 
-if [ "$1" = triggered ]; then
-    /lib/systemd/debian-enable-units
+_update_catalog() {
+    journalctl --update-catalog || true
+}
+
+# Update Message Catalogs database in response to dpkg trigger
+if [ "$1" = "triggered" ]; then
+    _update_catalog
     exit 0
 fi
 
-# Run the script after the initial installation or once on upgrades
-if [ -z "$2" ] || dpkg --compare-versions "$2" lt "44-9"; then
-    /lib/systemd/debian-enable-units
-fi
-
-if [ -n "$2" ]; then
-    _systemctl daemon-reexec || true
+# Cleanup state files from the auto-enabler which we used in wheezy
+if dpkg --compare-versions "$2" lt "204-1"; then
+    rm -f /var/lib/systemd/enabled-units
+    rm -f /var/lib/systemd/run-debian-enable-units
+    rm -f /var/lib/systemd/*.symlinks
 fi
 
 # Do a one-time migration of the local time setting
@@ -33,7 +36,13 @@ if dpkg --compare-versions "$2" lt "33-1"; then
 fi
 
 # Do a one-time migration of the TMPTIME setting
-if dpkg --compare-versions "$2" lt "36-2"; then
+if dpkg --compare-versions "$2" lt "204-9"; then
+    # Fix up potentially broken tmp.conf, see Debian#738862
+    if [ -e /etc/tmpfiles.d/tmp.conf ]; then
+        sed -i '/^# Clear \/var\/tmp/d' /etc/tmpfiles.d/tmp.conf
+        sed -i 's,^\(d /var/tmp\),#\1,g' /etc/tmpfiles.d/tmp.conf
+    fi
+
     if [ -f /etc/default/rcS ]; then
         . /etc/default/rcS
     fi
@@ -41,18 +50,28 @@ if dpkg --compare-versions "$2" lt "36-2"; then
         case "$TMPTIME" in
             -*|infinite|infinity)
                 cat > /etc/tmpfiles.d/tmp.conf <<EOF
-# Automatically migrated from TMPTIME in /etc/default/rcS
-# Clear /var/tmp as in /usr/lib/tmpfiles.d/tmp.conf, but avoid clearing /tmp
-d /var/tmp 1777 root root 30d
+# Avoid clearing /tmp by shipping an empty /etc/tmpfiles.d/tmp.conf file
+# which overrides /usr/lib/tmpfiles.d/tmp.conf.
+# This file was automatically created because of local modifications in
+# /etc/default/rcS where TMPTIME was set to infinite.
 EOF
                 ;;
         esac
     fi
 fi
 
-# Create /run/initctl → /dev/initctl compat symlink on upgrades
-if [ -e /sys/fs/cgroup/systemd ]; then
-    _systemctl restart systemd-initctl.socket || true
+# Do a one-time migration of the RAMTMP setting
+if dpkg --compare-versions "$2" lt "204-8"; then
+    if [ -f /etc/default/rcS ]; then
+        . /etc/default/rcS
+    fi
+    if [ -f /etc/default/tmpfs ]; then
+        . /etc/default/tmpfs
+    fi
+    if [ "$RAMTMP" = "yes" ]; then
+        # systemctl enable will work even when systemd is not the active PID 1.
+        systemctl enable tmp.mount || true
+    fi
 fi
 
 if dpkg --compare-versions "$2" lt "40-1"; then
@@ -62,14 +81,77 @@ if dpkg --compare-versions "$2" lt "40-1"; then
     if [ -d /lib/init/rw ]; then
         rmdir --ignore-fail-on-non-empty /lib/init/rw || true
     fi
-
-    # Create /run/initctl → /dev/initctl compat symlink on upgrades
-    if [ -e /sys/fs/cgroup/systemd ]; then
-        ln -sf /dev/initctl /run/initctl
-    fi
 fi
 
+# Create /etc/machine-id
 systemd-machine-id-setup
+
+# Setup system users and groups
+addgroup --quiet --system systemd-journal
+
+adduser --quiet --system --group --no-create-home --home /run/systemd \
+    --gecos "systemd Time Synchronization" systemd-timesync
+adduser --quiet --system --group --no-create-home --home /run/systemd/netif \
+    --gecos "systemd Network Management" systemd-network
+adduser --quiet --system --group --no-create-home --home /run/systemd/resolve \
+    --gecos "systemd Resolver" systemd-resolve
+adduser --quiet --system --group --no-create-home --home /run/systemd \
+    --gecos "systemd Bus Proxy" systemd-bus-proxy
+
+# Initial update of the Message Catalogs database
+_update_catalog
+
+# Make systemd-detect-virt utility usable for non-root users
+setcap cap_dac_override,cap_sys_ptrace=ep /usr/bin/systemd-detect-virt || true
+
+# We don’t ship /var/log/journal currently, so only run the following fix for
+# systems where the administrator has explicitly enabled persistent logging by
+# creating /var/log/journal.
+if [ -d /var/log/journal ]; then
+    # Grant read access to /var/log/journal for members of the adm group
+    # via a filesystem ACL. This makes them able to read the journal.
+    # Failure is ignored since there might be file systems mounted without
+    # ACL support.
+    setfacl -R -nm g:adm:rx,d:g:adm:rx /var/log/journal || true
+fi
+
+if [ -n "$2" ]; then
+    _systemctl daemon-reexec || true
+    _systemctl try-restart systemd-logind.service || true
+    _systemctl try-restart systemd-networkd.service || true
+    _systemctl try-restart systemd-resolved.service || true
+    _systemctl try-restart systemd-timesyncd.service || true
+fi
+
+# Enable getty and remote-fs.target by default on new installs, and on
+# upgrades from old systemd versions (where the symlinks included as deb
+# content, and will thus have been removed by dpkg during the upgrade).
+if dpkg --compare-versions "$2" lt "214-1"; then
+    systemctl enable getty@tty1.service || true
+    systemctl enable remote-fs.target || true
+fi
+
+# Re-run systemctl enable for any service that was enabled when preinst was run.
+if dpkg --compare-versions "$2" ge "204"; then
+    while read UNIT ; do
+        systemctl enable $UNIT || true
+    done </run/systemd/was-enabled || true
+fi
+
+# The /dev/log socket and /dev/initctl FIFO have been moved to /run and
+# replaced by symlinks. Create the symlinks manually on upgrades as well.
+# (https://bugs.debian.org/761340). Note that this will break the current
+# journal as we cannot restart it properly (https://bugs.debian.org/771122) so
+# this is mostly an one-time upgrade path from wheezy.
+if dpkg --compare-versions "$2" lt-nl "215-3"; then
+    if [ -p /run/systemd/initctl/fifo ] && [ ! -L /dev/initctl ]; then
+         ln -sf /run/systemd/initctl/fifo /dev/initctl
+    fi
+    if [ -S /run/systemd/journal/dev-log ] && [ ! -L /dev/log ]; then
+         ln -sf /run/systemd/journal/dev-log /dev/log
+    fi
+    _systemctl try-restart systemd-journald.service || true
+fi
 
 # Automatically added by dh_installdeb
 dpkg-maintscript-helper rm_conffile /etc/lsb-base-logging.sh 25-1~ systemd -- "$@"
@@ -84,6 +166,15 @@ dpkg-maintscript-helper rm_conffile /etc/tmpfiles.d/systemd.conf 29-1~ systemd -
 dpkg-maintscript-helper rm_conffile /etc/tmpfiles.d/x11.conf 29-1~ systemd -- "$@"
 # End automatically added section
 # Automatically added by dh_installdeb
-dpkg-maintscript-helper mv_conffile /etc/bash_completion.d/systemctl-bash-completion.sh /etc/bash_completion.d/systemd-bash-completion.sh 44-2~ systemd -- "$@"
+dpkg-maintscript-helper rm_conffile /etc/bash_completion.d/systemctl-bash-completion.sh 204-1~ systemd -- "$@"
+# End automatically added section
+# Automatically added by dh_installdeb
+dpkg-maintscript-helper rm_conffile /etc/bash_completion.d/systemd-bash-completion.sh 204-1~ systemd -- "$@"
+# End automatically added section
+# Automatically added by dh_installdeb
+dpkg-maintscript-helper mv_conffile /etc/systemd/systemd-logind.conf /etc/systemd/logind.conf 204-1~ systemd -- "$@"
+# End automatically added section
+# Automatically added by dh_installdeb
+dpkg-maintscript-helper mv_conffile /etc/systemd/systemd-journald.conf /etc/systemd/journald.conf 204-1~ systemd -- "$@"
 # End automatically added section
 
